### ISSUE TITLE
Replace deprecated blueprintjs components

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#1001]
**Is your feature request related to a problem? Please describe.**
We use a few deprecated blueprintjs components. This could lead to bugs unnoticed.

**Describe the solution you'd like**
Replace all deprecated components with the 'newer' counterparts.

Deprecated Components:
- (DateInput)
- IResizeEntry
- Select

**Describe alternatives you've considered**
/

**Additional context**
The deprecated blueprintjs date input was removed, because it didn't work properly. The newer component might fix this (we currently use dateinput from material, as it just did not work properly). #1003 

Updating date input is blocked by https://github.com/palantir/blueprint/issues/5699

**Comment by michael-markl** [comment]
I cannot access https://chat.tuerantuer.org/digitalfabrik/pl/qzsn9itzwtf1pfgndyjg3jopqw
Would be nice, if you could list the deprecated blueprintjs components in the issue description
