### ISSUE TITLE
Name is not transfered to PDF

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1021]
**Describe the bug**
When creating a single card (Nürnberg) the entered name from the inputform dos't appear in the PDF.

**To Reproduce**
1. create a single card with valid Data
2. print the card
3. observe missing name

**Expected behavior**
The name is filled in at the top field in the PDF

**Comment by f1sh1918** [comment]
he letterhead only gonna be filled if an address field was filled. so only for csv import. The form input will not affect the letterhead. We can discuss if that should happened but it works as designed imo.

**Comment by f1sh1918** [comment]
works as designed
