### ISSUE TITLE
Special caracters lower the name limit

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1022]
**Describe the bug**
Special characters lower the 30 chars limit 
seems to me like checking bytes not characters

**To Reproduce**
1. create a CSV with 29 chars name
2. append special character 'ä'
3. import file
4. observe wrong name

**Expected behavior**
The limit should count characters regardles of encoding

**Additional context**
Also as leading and trailing spaces are stripped, multiple spaces in between count to the length of name, but will be replaced by a single space. This leads to wrong marked names in the list with less than 30 character.

**Comment by f1sh1918** [comment]
This should be discussed. Maybe we should check once the amount of chars and then the encoded chars, since this bug happens due to encoding.
- for encoded data 50chars are fine in the qr code.
- for space on the card 30 chars are fine.
