### ISSUE TITLE
Fix typo "bayrisch" in Approval-Mail

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/entitlementcard#1042]
"Ihr Antrag zur Bayrischen Ehrenamtskarte wurde erfolgreich eingereicht. " contains a typo. It should be "Bayerischen Ehrenamtskarte".

**Comment by Docmale** [comment]
I see a totally different text: "Erfolgreich gesendet
Ihr Antrag für die Ehrenamtskarte wurde erfolgreich übermittelt.
Über den Fortschritt Ihres Antrags werden Sie per E-Mail informiert.
Sie können das Fenster jetzt schließen."
