### ISSUE TITLE
Only Card Type "Digitale Karte" should be ticked per default in request form

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/entitlementcard#1044]
The StMAS wants to have the checkbox "Digitale Karte" ticked per default.

**Comment by michael-markl** [comment]
@dkehne Currently, both digitale and physikalische Karte are ticked by default.

**Comment by sarahsporck** [comment]
@dkehne ping

**Comment by dkehne** [comment]
The answer is: only "Digitale Karte" should be ticked by default. One could also think about changing the order. Digitale Karte first, physische Karte second. You may decide that on your own.
