### ISSUE TITLE
Golden EAK shows as invalid despite being valid

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#1049]
**Describe the bug**

A volunteer (Landkreis Kulmbach, EAK) activated its GOLDEN card by scanning an activation code.

The "Ausweisen"-Tab shows their golden card including their name, but below, there is the following error message:
"Ihre Karte ist ungültig. Sie wurde entweder widerrufen oder auf einem anderen Gerät aktiviert."

On a different device (without some specific security setting) activating the card worked without problems.

Unclear:
* Did the error message show directly after scanning the Ausweisen Tab
* What kind of seurity setting is activated?

**To Reproduce**

**TODO:** Describe steps to reproduce the behavior.

**Expected behavior**

There should not be an error message, but instead a QR Code after succesfully activating the code.

**Smartphone:**
 - Device: ?
 - OS: Android
 - Version ?

**Comment by f1sh1918** [comment]
@michael-markl can we get the device and platform version? specific android version?
