### ISSUE TITLE
Backend does not verify length of CardInfoHash for "addCards" endpoint

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#1054]
**Describe the bug**
The backend does not verify the length of CardInfoHash in the addCards endpoint.
We should make sure it has a specified length. https://github.com/digitalfabrik/entitlementcard/blob/7a93f4de064b4d3649450aead8e6972bc9914b71/backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/webservice/schema/CardMutationService.kt#L26

I think, we generate SHA-256 hashes in the administration frontend. We should check the hash size received in the backend.

**Comment by sarahsporck** [comment]
Currently we only base64 encode the card hash. Should we change that? What would be the advantage of using SHA-256 hashes here?

**Comment by michael-markl** [comment]
> Currently we only base64 encode the card hash. 

And the card hash is produced using SHA-256.

The issue is only about checking that the backend actually receives a hash of the correct size.

**Comment by sarahsporck** [comment]
Ahh. I looked at the wrong line. Alrighty. I'll do this :)
