### ISSUE TITLE
Update Akzeptanzpartner for Nuremberg-Pass

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/entitlementcard#1057]
We have received a new list from nuremberg with updates information. It can be found here: https://nextcloud.tuerantuer.org/index.php/f/4774065

Before using the document, please check the data cells that are marked yellow - the format might not fit.
Additionally add the coordinates for the new entries (if manually neccessary)

**Comment by dkehne** [comment]
Please make the following adjustments for the coordinates if possible:

Spielzeugmuseum

- die Kachel auf der Karte ist falsch gesetzt. Aktuell befindet sich diese auf der Karlstraße zwischen Sozialgericht und Augustinerhof. Das Spielzeugmuseum befindet sich aber tatsächlich nördlich der Augustinerstraße gegenüber der Mündung Schustergasse.

Museum Industriekultur

- die Kachel wird von der Kachel der Tafelhalle überlagert und über den Kartenmodus nicht aufrufbar. Es ist auch nicht erkennbar, dass sich dort zwei Kacheln (also auch zwei Einrichtungen befinden). Die Kachel für das Museum Industriekultur müsste im gleichen Gebäude etwas weiter westlich, an der Mittelachse des Gebäudes, wo die gestrichelte Linie anlandet, gesetzt werden.

**Comment by f1sh1918** [comment]
1. besser bekomm ich das nicht gesetzt
<img width="256" alt="image" src="https://github.com/digitalfabrik/entitlementcard/assets/37902063/29223fcc-cd8a-42eb-a588-969281bfaf63">

2. jetzt ist beides klickbar
<img width="264" alt="image" src="https://github.com/digitalfabrik/entitlementcard/assets/37902063/dcf0162d-744b-4415-9545-e4dfcf3ded9b">

Werde das jetzt updaten auf prod

**Comment by f1sh1918** [comment]
@dkehne csv was updated on prod server and will be imported with the next scheduled import job (should be every second day)
