### ISSUE TITLE
Create card from application

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1075]
As a service user i want to create cards directly from application. So a manual filling is not needed

## Acceptance Criteria:
 - add a button "Karte erstellen"
 - with a click on the button you will be forwarded to the "Einzelne Karten erstellen" page
 - input fields will be filled with the application data

## Technical Tasks:
 - add a button "Karte erstellen" to the bottom of the application
 - button will be shown only if logged in as a service user
 - click on the button forwards to the 'cards/add' route and passes attributes via queryParams
 - the input fields should be filled with the values of the queryParams
 - queryParams should be optional, test that Sozialpass will not break

**Comment by sarahsporck** [comment]
Blocked by #1082

**Comment by sarahsporck** [comment]
@hauf-toni I think we need a design for this. Currently the application is quite cluttered with lot's of buttons and stuff.
For context: 
As a 'Mitarbeiter einer Stadt' I want to view, export and delete entitlementcard applications. To ease the workflow from application to a created card, we add a functionality to create a card from an application. This is what this ticket is about.

However the button bar is now quite full and there is too much information at once at the bottom of the Application. Could you come up with a better design for this?

<img width="800" alt="Bildschirmfoto 2023-08-28 um 10 07 03" src="https://github.com/digitalfabrik/entitlementcard/assets/28013368/0afeda0a-b94b-43bf-bc65-70b50cd99a9e">
<img width="200" alt="Bildschirmfoto 2023-08-28 um 10 07 48" src="https://github.com/digitalfabrik/entitlementcard/assets/28013368/8f60c067-2e99-4872-92e6-cf4b5dbdf95a">
<img width="586" alt="Bildschirmfoto 2023-08-28 um 10 09 42" src="https://github.com/digitalfabrik/entitlementcard/assets/28013368/013c226d-ac33-4c3e-a97e-340797d03c35">

**Comment by sarahsporck** [comment]
Maybe moving the expand into the header is an option (check out https://m2.material.io/components/cards#behavior). And last info: this view is only used in web so no reason to stress about mobile for now :)

**Comment by hauf-toni** [comment]
👋 design proposal can be found [here](https://www.figma.com/file/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?type=design&node-id=31%3A1226&mode=design&t=uV7kx23srnS0TirO-1)

**Comment by f1sh1918** [comment]
nice design proposal @hauf-toni 
Unfortunately i think this includes a lot of redesign which we will not get payed and has some difficulties on how the data is structured which i added in the comment in figma. Maybe we can keep this idea for future because i like it :)

Maybe should think for now for an easier solution. An idea of me was just to move the Button into the next line and a divider or sth similar. The different colors are fine :)

<img width="603" alt="image" src="https://github.com/digitalfabrik/entitlementcard/assets/37902063/a44cca64-60c4-4e9e-8a77-dd401f5184ac">
