### ISSUE TITLE
Date cannot be inserted nicely for 01-02-2024

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#1077]
**Describe the bug**
Nürnberg would like to enter a date by just using the keyboard, but when entering 01-02-2024 as a start date, 10-02-2024 is the result.

**To Reproduce**
1. Go to create card
2. Click on the start date field
3. Type (exactly 01022024) 
4. See that date is actually 10.02.2024

---
EDIT: 
We got some more valuse which proposedly don't work:

|Eingabe per Tastatur|	Ausgabe/Anzeige|
|-|-|
|01022023	|10.02.2023|
|01031969	|10.03.1969|
|01021977	|10.02.1977|

---

**Expected behavior**
The date is 01.02.2024.

**Additional context**

**Comment by sarahsporck** [comment]
On-hold until we hear from Daniel.

**Comment by michael-markl** [comment]
Unfortunately, the interaction with date input fields depends a bit on the browser, however I guess every browser allows to enter a date using the keyboard only.
I would not classify this as a bug, though. It's also non-trivial to fix. Most likely, we would have to use yet another dependency just for the datepicker.

I'd recommend to respond with something along the following lines:
There's a way to enter a date with your keyboard only but it depends on your browser. On Firefox, simply enter all numbers (single-digit days and months prefixed with "0")  in succession (e.g.  `01022024`) (Firefox recognizes the intentionally placed zero-prefixes) and on Chromium-based browsers, press `<TAB>` in the case of a single-digit day between 1 and 3 and in the case of January, e.g.  `01<TAB>01<TAB>2024` -> 01.01.2024, `0401<TAB>2024` -> 04.01.2024, `04022024` -> 04.02.2024. On Safari (which does the best thing imo) press `<TAB>` after every group (no matter how large your numbers are): `01<TAB>02<TAB>2024`

**Comment by sarahsporck** [comment]
Then our solution is use firefox, as Nuernberg decided to "depriorize" this issue in favor of parametrized urls
