### ISSUE TITLE
[Sozialpass] Switch PassId and Passnumber

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1081]
As a user i don't need the passnumber anymore for the sozialticket but only the passId for the DE-Ticket so i only want to have this passID on the card to not be confused about different numbers/id.

**Note:** To ensure backward compatibility in the app we keep the passnumber extension that was already delivered in the QR-Code and just rename the labels for the druckerei user.

## Acceptance Criteria:
 - PassId form field is removed from create cards
 - The passId will be shown in the printed and digital card
 - The passNr will be removed from the back of the printed card

## Technical Tasks:
 - Remove passId extension for the sozialpass (!!!)
 - adjust the labels from passName to passId in the csv import and create card form (buildConfig)
 - ensure that the activity log has the correct table header PassID
 - remove passnumber in the csv import example file
 - adjust the pdf template to only show the passId (printed card)
 
 Blocked:**Should be deployed after 10th of november**

**Comment by SteffiStuffel** [comment]
@f1sh1918 why is this blocked?

**Comment by f1sh1918** [comment]
> @f1sh1918 why is this blocked?

We need a final clearance when this should be deployed due to some  Regulation with the PassNumber which was needed to get certain social aid but will be obsolet starting next year
