### ISSUE TITLE
[Sozialpass] Add multiple cards (Design)

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1085]
Please provide a design for multi cards view

- Swipe area to navigate between cards and barcodes
- Delete Button/Icon to delete the particular card

relates to #1084

**Comment by hauf-toni** [comment]
Design-proposal can be found [here](https://www.figma.com/file/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?type=design&node-id=1%3A35&mode=design&t=dVBz5V00K5kFQ85e-1)

**Comment by f1sh1918** [comment]
<img width="257" alt="image" src="https://github.com/digitalfabrik/entitlementcard/assets/37902063/e194f266-0344-4e5f-8c48-3acd0a11c0fb">

<img width="253" alt="image" src="https://github.com/digitalfabrik/entitlementcard/assets/37902063/8403bce4-436b-45dc-94a7-8b55f4309a01">

**Comment by hauf-toni** [comment]
version 2 of the design proposal can be found here: [🟣](https://www.figma.com/file/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?type=design&node-id=1%3A35&mode=design&t=Wknp3S25hvyoAfep-1) @f1sh1918 @sarahsporck

**Comment by f1sh1918** [comment]
@hauf-toni 
Here is the verification result modal. I think we could just adjust the headline and make a second action
<img width="310" alt="image" src="https://github.com/digitalfabrik/entitlementcard/assets/37902063/a04ece8c-99ef-4a67-95c5-31616ab58704">

**Comment by michael-markl** [comment]
@hauf-toni Can you make the design publicly available?

**Comment by f1sh1918** [comment]
@hauf-toni i'm all good with the design alternative that you proposed :)
Not sure if we have primary and secondary button like that but the delete button should be highlighted anyways

**Comment by hauf-toni** [comment]
@michael-markl your requests have to be accepted first, so that the design files can be viewed. unfortunately, the project cannot be made publicly available to everyone. of course, every staff member who wants to will get access to the designs.

**Comment by michael-markl** [comment]
> unfortunately, the project cannot be made publicly available to everyone

Is this a technical limitation of Figma for our license model or so?

It seems, for files that I create on Figma, I could set the visibility to "Everyone with the link can view".

**Comment by hauf-toni** [comment]
> It seems, for files that I create on Figma, I could set the visibility to "Everyone with the link can view".

good point; i'll make sure that the link is always set like this. 
this way everyone who belongs to the team "digitalfabrik" can see the file. for this membership you have to be approved.

**Comment by f1sh1918** [comment]
@hauf-toni there are some small adjustments missing. If we need to clarify sth let me know!
