### ISSUE TITLE
[Sozialpass] Adjust PDF Layout (Design)

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1086]
The PDF Layout should be adjusted according to the model attached

[Schablone_Anschrift_Datev (002).pdf](https://github.com/digitalfabrik/entitlementcard/files/12358571/Schablone_Anschrift_Datev.002.pdf)

**Comment by sarahsporck** [comment]
Wouldn't this become obsolete with the pdf-export?

**Comment by dkehne** [comment]
Yes but it was paid already so if the adjustments are possible, please merge it @hauf-toni - 
it was requested for the time until we can finally export the passes as CSV. This may take some more weeks/month because we haven't even made a proposal because the external partner still hasn't answered how they want to get the binary-data-matrix..

**Comment by sarahsporck** [comment]
Ah okay. Didn't want to interrupt the workflow here. Thank you for this information @dkehne.

**Comment by hauf-toni** [comment]
The updated PDF can be found [📍 here](https://nextcloud.tuerantuer.org/index.php/f/5248020). 
Some further thoughts: in the attached png you can see the new distances; not much has changed, but the content areas for the _address field_ (X:18,5mm, Y:68,5mm, W:57mm, H:20mm) as well as for the _D-Ticket Nürnbergpass-ID_ (X:135mm, Y:85, W: 44mm, H:5mm) are new. If you still want the address field to be editable manually, please let me know and I will change it in the new PDF.
![2309-Ehrenamtskarte-Nürnberg-content-areas](https://github.com/digitalfabrik/entitlementcard/assets/123894307/3a8bd361-57e3-459c-a0a9-563f041d3f50)

**Comment by f1sh1918** [comment]
@sarahsporck i tested the new template and i can still edit the address field so it should be fine?!

**Comment by sarahsporck** [comment]
Jep. The editible fields from the template are not persisted in the generated pdf. Therefore, the fields are generated programmatically.

**Comment by f1sh1918** [comment]
resolved by #1087
