### ISSUE TITLE
Fehler beim Ausführen von "insertBefore" auf "Node"

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/entitlementcard#1121]
**Describe the bug**
Beim Öffnen der Digitalen Druckerei über den Anmeldebutton „Eingehende Anträge“ erscheint eine Fehlermeldung auf meinem PC. Wenn ich in der oberen Leiste auf „Eingehende Anträge“ gehe, erscheinen allerdings die digitalen Anträge ganz normal. Somit kann ich die Anträge auch bearbeiten und die Behebung dieser Störung ist nicht wirklich eilig. Ich wollte Sie dennoch über diese Fehlermeldung informieren.

![Screenshot Fehlermeldung digitale Druckerei, eingehende Anträge](https://github.com/digitalfabrik/entitlementcard/assets/4182469/1150b6b3-a515-46fa-9027-465dbd3e22b3)

**Comment by f1sh1918** [comment]
@dkehne can you reproduce that on live system?

**Comment by f1sh1918** [comment]
@sarahsporck, @ztefanie , @steffenkleinle  can anyone reproduce this on any browser?

**Comment by sarahsporck** [comment]
Nope. Cannot reproduce this. Neither in firefox nor safari.

**Comment by f1sh1918** [comment]
@dkehne are there any updates?

**Comment by f1sh1918** [comment]
close as not reproduceable and were never reported anymore
