### ISSUE TITLE
Fix `can not parse "accepting_stores" to a i16`

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#1140]
**Describe the bug**
It seems there is an error in our accepting stores `index.json`. But no clue what's not working.

**To Reproduce**
1. Go to `http://localhost:5002/tiles/accepting_stores/rpc/index.json`
2. See error

**Expected behavior**
See the accepting stores.

**Screenshots**

**Additional context**
https://github.com/digitalfabrik/entitlementcard/pull/1134#discussion_r1350148341

**Comment by f1sh1918** [comment]
duplicate with [#1366](https://github.com/digitalfabrik/entitlementcard/issues/1366)
