### ISSUE TITLE
Create CI pipeline

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1146]
**Is your feature request related to a problem? Please describe.**
Create a proper ci pipeline for druckerei, backend, flutter apps, release notes, Mattermost notification, etc
Consider that we maybe need release notes different for each app. F.e. we provide multi cards only for sozialpass, so it shouldn't be shown for entitlement card

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ztefanie** [comment]
Closed in favor of https://github.com/digitalfabrik/entitlementcard/issues/1158
