### ISSUE TITLE
Change sentence "Falls Sie denken, die Angaben seien fälschlicherweise, hätten wir Sie gemacht, die Angaben zu widersprechen."

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/entitlementcard#1149]
There is a wrong sentence reported by a user (maybe in one of the mail templates): Falls Sie denken, die Angaben seien fälschlicherweise, hätten wir Sie gemacht, die Angaben zu widersprechen.

Don't know where is occurs but needs to be changed to a correct (easy understable) German sentence

**Comment by f1sh1918** [comment]
@dkehne i really don't know where they got that from but in our verification template the following is written:

"Sie wurden gebeten, die Angaben eines Antrags auf Ehrenamtskarte zu bestätigen. Die Antragsstellerin oder der
          Antragssteller hat Sie als Kontaktperson der Organisation `{verification.organizationName}` angegeben. Im
          Folgenden können Sie den zugehörigen Antrag einsehen. Wir bitten Sie, die enthaltenen Angaben, welche die
          Organisation `{verification.organizationName}` betreffen, zu bestätigen. Falls Sie denken, die Angaben wurden
          fälschlicherweise gemacht, bitten wir Sie, den Angaben zu widersprechen."
          
I don't think we have to change anything. If you have a proposal for an easier sentence just let me know

**Comment by f1sh1918** [comment]
we don't use this sentence in any mail
