### ISSUE TITLE
Setup automatic release notes handling

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/entitlementcard#1165]
Think of a good way to handle release notes. 

Options:
1) Automatic handling like in integreat can be done. We can add a field to which apps a release note belongs
2) We can not handle release notes automatically. So it needs to be done manually.

Other options?

**Comment by sarahsporck** [comment]
Alternative -> https://docs.github.com/de/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release 
But this cannot generate different release notes per app of course.

**Comment by ztefanie** [comment]
@sarahsporck Are different release notes needed for entitlementcard and nuernberg?

**Comment by sarahsporck** [comment]
currently we use the same release notes for both applications. I guess there are use cases for different release notes, but currently not really a thing. What do you think @f1sh1918

**Comment by f1sh1918** [comment]
Yes we definitly need release notes per project. Maybe also for native Apps and administration (just for testing)

**Comment by sarahsporck** [comment]
> Yes we definitly need release notes per project. I set the stores notes manually in the stores and they differ quite often. I think we also need native & administration. So in the end we should have in mattermost 4 notifications. 2 for each project

Then I think the github enpoint is not an option and we should use the same approach as in Integreat.

**Comment by f1sh1918** [comment]
additionally to sarahs post, i don't think that the release notes that are generated contain suitable wording for store release notes that are understandable for users.
I know that we discussed a lot about this topic but i think we should use the same approach that in integreat @ztefanie ?!

**Comment by ztefanie** [comment]
We can think about this, not sure if it is worth the effort.

**Comment by f1sh1918** [comment]
> We can think about / discuss this, not sure if it is worth the effort.

Hm i think we also could use a general description for the releases in the stores. Like
"Wir arbeiten kontinuierlich daran die App zu verbessern...etc"

**Comment by ztefanie** [comment]
> > We can think about / discuss this, not sure if it is worth the effort.
> 
> Hm i think we also could use a general description for the releases in the stores. Like "Wir arbeiten kontinuierlich daran die App zu verbessern...etc"

I think we can start with this, as it is good enough, we also can add a link to the releases page
with a hint, "for a details list of improvments, feel free to checkout out https://github.com/digitalfabrik/entitlementcard/releases"
or something similar, if we later in the future, need / want the improvements in the stores, we can still do it. So I think the easier way is good enough for now.
