### ISSUE TITLE
Push search and map routes to the root stack

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#1170]
**Is your feature request related to a problem? Please describe.**
Reasoning can be found in #420 .

**Describe the solution you'd like**
We discussed this and decided it makes sense to push routes to the root navigation stack in the search and map tabs.

**Additional context**
#420

**Comment by michael-markl** [comment]
Fixed in commit https://github.com/digitalfabrik/entitlementcard/commit/dcad66ef372ea4e9ba4b52193a25396b128d71e3
