### ISSUE TITLE
[Sozialpass] Translate the build configs

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/entitlementcard#1177]
**Is your feature request related to a problem? Please describe.**
Quite some localizations live in the build config atm. In order to provide the app in english, these should be translated.

**Describe the solution you'd like**
Add translations to the build configs. This is not really nice but perhaps not otherwise possible.

**Describe alternatives you've considered**
For localizations that only differ in the app name, we could add those to the .arb files introduced in #904 and pass the app name as parameter.

**Additional context**
Part of #1174.

**Comment by f1sh1918** [comment]
Hi @steffenkleinle,
i found this package to init multiple arb files. Not sure if that helps you but maybe you could somehow provide a general arb file and a project specific arb file and load both, the second one conditionally depending on the project :
https://github.com/Innim/flutter_multiple_localization

**Comment by steffenkleinle** [comment]
> Hi @steffenkleinle, i found this package to init multiple arb files. Not sure if that helps you but maybe you could somehow provide a general arb file and a project specific arb file and load both, the second one conditionally depending on the project : https://github.com/Innim/flutter_multiple_localization

Thanks for researching! I sadly think that this package is not compatible to the default flutter localization since there everything that is needed (including delegates and messages) are autogenerated. However, I came to conclusion that the default flutter l10n is not enough anyway, so I had to change the library. I changed to https://github.com/slang-i18n/slang in #1188.

**Comment by steffenkleinle** [comment]
Done in #1189.
