### ISSUE TITLE
Reactivate deleted card

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1184]
**Is your feature request related to a problem? Please describe.**

Currently a card can only be activated and used on one device. If the activation code will be used on another device, the user gets a notification that the card will be deactivated on the other device. 
With the multi card implementation the user is able delete a card and reactivate.
In this case the user will also be notified that the card will be deactivated on the other device, which is not the case

**Describe the solution you'd like**
- set the `totpSecret` to null on card deletion
- The `firstActivationDate` shouldn't be overwritten since it may be used for statistics
- Show the already activated dialog only if the `totpSecret` is set

**Additional context**
Here is the discussion: https://github.com/digitalfabrik/entitlementcard/pull/1142#issuecomment-1772227549

**Comment by f1sh1918** [comment]
@steffenkleinle maybe this can also labeled as a bug. 
Feel free to add suggestions for implementation

**Comment by michael-markl** [comment]
I believe, instead of adding an `active` column to the cards table, we can also simply set the `totp-secret` to `NULL`. (It's also NULL before the first activation).
`firstActivationDate` should only be written if it has not been written yet, so this should not be a problem.

**Comment by f1sh1918** [comment]
alright good point. i'm gonna adjust the description

**Comment by michael-markl** [comment]
Its still unclear how to authorize the deletion. Probably using an otp code, but we should likely not use the same code as we use for verification.

**Comment by f1sh1918** [comment]
#1266 might be good enough to not put more effort into this?

**Comment by f1sh1918** [comment]
resolved with #1266
