### ISSUE TITLE
[Sozialpass] Localize dates

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/entitlementcard#1186]
**Is your feature request related to a problem? Please describe.**
At the moment all dates in the app use german date format (DD.MM.YYYY).

**Describe the solution you'd like**
The format of the shown dates should depend on the current locale.

**Describe alternatives you've considered**
None.

**Additional context**
There is built in flutter functionality to do this: https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#messages-with-dates

Part of #1174.

**Comment by michael-markl** [comment]
It might actually be better not to localize the dates, at least not the ones shown on the card itself. It might be very confusing for German verifiers to see an American date format (month/day/year).
Not sure, if you already discussed this, though.

**Comment by f1sh1918** [comment]
what is your opinion @dkehne ?
Can we close this issue?

**Comment by dkehne** [comment]
my opinion is to stay with the german-date-format everywhere. It should not be a problem if we have the English-Version of the App and German locaization of dates. I also see the confusion-aspect by switching month and day-position.

**Comment by f1sh1918** [comment]
perfect so i'm gonna close that issue

**Comment by f1sh1918** [comment]
perfect so i'm gonna close that issue
