### ISSUE TITLE
System mail does not visualize umlauts the right way

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/entitlementcard#1191]
I have no further bug description except the fact that the person has on devices where the umlauts are not show right has also the problem that the link does not work when copied/pasted, even it works from other devices where the umlauts are shown correctly. 
<img width="802" alt="278582684-1c63d02d-2fa7-4fea-8284-352b5ea51216" src="https://github.com/digitalfabrik/entitlementcard/assets/4182469/68eff933-be28-494d-b52b-ae58ec074ec2">

**Comment by ztefanie** [comment]
This is an encoding problem, the mail in the screenshot is displayed in `iso 8859-1`, but we have a header saying it should be displayed in `utf8`. I opened a PR change dit to `UTF-8` as this is the correct wording, as this can fix the error for some users, see:

> The charset value should be utf-8, not any other values such as utf8. Using utf8, for example, is a common mistake, and even though it is valid nowadays as the [specifications](https://encoding.spec.whatwg.org/#names-and-labels) and browsers now alias utf8 to utf-8, that wasn’t the case in the past, so things might break in [some older browsers](https://twitter.com/jacobrossi/status/591435377291866112). The same may be true for other agents (non-browsers) that may scan/get the content and may not have the alias.
[source](https://webhint.io/docs/user-guide/hints/hint-meta-charset-utf-8/#:~:text=The%20charset%20value%20should%20be,break%20in%20some%20older%20browsers.)

But this error can also occure when users force their mail client to use another encoding as we put in the header. So if this error does not disappear for the user, i recomment checking the settings or updating the client.

We also can make sure the link only contains ASCI chars, but I think it alread does, to at least ensure the link is always working.
