### ISSUE TITLE
Android invalid certificate

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1202]
**Describe the bug**
This bug was created by sentry. Seems like on android 7 our backend can't be reached due to a certificate error

**To Reproduce**
1. Start android emulator with android 7
2. Run production build
3. Check error

**Expected behavior**
The app can connect to the backend

```js
HandshakeException: Handshake error in client (OS Error: 
I/flutter (12573): 	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:393)), originalStackTrace: #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
I/flutter (12573): #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
I/flutter (12573): #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:918:54)
I/flutter (12573): #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1047:19)
I/flutter (12573): <asynchronous suspension>
```

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 7
- Network: wifi

Solution: Provide [certificate](https://stackoverflow.com/a/71090239)

**Additional context**
[Sentry log](https://sentry.tuerantuer.org/organizations/digitalfabrik/issues/4192/?project=4)

**Comment by f1sh1918** [comment]
couldn't reproduce with emulator on android 7. Card activation worked fine

**Comment by f1sh1918** [comment]
i've read in some blogs that this may happen if there is no internet connection. On emulator i couldn't reproduce that. The "Keine Verbindung möglich" exception is appearing

**Comment by maxammann** [comment]
Good catch! So the solution is to upgrade Dart?

**Comment by f1sh1918** [comment]
> Good catch! So the solution is to upgrade Dart?
> 

No the solution is to provide an extra certificate for older Android Versions as far as I understood
