### ISSUE TITLE
Notes for applications

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1206]
As a service user i want to be able to create and edit a note on an application to save additional information about the progress of the application

## Acceptance Criteria:
 - A service user i can create, edit and view note by clicking a button on the application form
 - the note will be deleted with the application

## Technical Tasks:
 - [ ] implement a CTA button to open a dialog where the user can create/update a note
 - [ ] implement the note form with texts and buttons.
 - [ ] maybe it makes sense to limit the amount of chars

**Comment by hauf-toni** [comment]
Design Proposal can be found [📌 here](https://www.figma.com/file/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?type=design&node-id=290%3A47&mode=design&t=IBS2a6MVaGwSntJl-1)

**Comment by hauf-toni** [comment]
@f1sh1918 V2 (show note when application is opened) can be found in the Figma-File linked above
