### ISSUE TITLE
Print DeepLink on pdf

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1212]
**Is your feature request related to a problem? Please describe.**
As a user i want to have a deep link as an alternative to activate the card.

**Describe the solution you'd like**
- There should be a section on pdf that "you can activate the card by this link(hyperlink)" or sth similar, if you have already installed the app (-> check pdf)
- PDF for entitlementcard should be adjusted
- url should use `https` scheme and `activationCode` should be encoded

Example:
`https://staging.bayern.ehrenamtskarte.app/activation/code#<activationCode>/`

**Design**
Updated pdf can be found in the las comment

**Comment by dkehne** [comment]
Guten Tag,

Ihr Antrag zur Bayerischen Ehrenamtskarte wurde bewilligt. 

Die Bayerische Ehrenamtskarte wird Ihnen in den nächsten Tagen zusammen mit einer Anleitung zur Einrichtung der digitalen Karte auf Ihrem Smartphone zugestellt. 

Sollten Sie App „Ehrenamtskarte Bayern“ bereits eingerichtet haben können Sie Ihre digitale Karte auf vielen Endgeräte auch vorab schon aktivieren. Klicken Sie dazu von Ihrem Gerät, auf dem die App installiert ist, auf den folgenden Link: [[DeepLink]

**Comment by hauf-toni** [comment]
Here is my suggestion for the PDF with an included DeepLink (Placement info in png)
[240212-Ehrenamtskarte-Bayern.pdf](https://github.com/digitalfabrik/entitlementcard/files/14237749/240212-Ehrenamtskarte-Bayern.pdf)

<img width="200" alt="size DeepLink" src="https://github.com/digitalfabrik/entitlementcard/assets/123894307/89ecdf79-8578-486f-a336-d34f5f54ad95">

**Comment by f1sh1918** [comment]
> 240212-Ehrenamtskarte-Bayern.pdf

Alternativ können Sie auf dem Gerät, auf dem Sie
die App bereits installiert haben , auf folgenden Link
klicken, um ihre Karte zu aktivieren:

i would add this last part. Do bullet points look strange? It may make sense to add them @hauf-toni

**Comment by hauf-toni** [comment]
How about this version:
[220213-Ehrenamtskarte-Bayern.pdf](https://github.com/digitalfabrik/entitlementcard/files/14260378/220213-Ehrenamtskarte-Bayern-V1_0.pdf) @f1sh1918

**Comment by f1sh1918** [comment]
> How about this version:
> [220213-Ehrenamtskarte-Bayern.pdf](https://github.com/digitalfabrik/entitlementcard/files/14260378/220213-Ehrenamtskarte-Bayern-V1_0.pdf) @f1sh1918 
> 

Looks good just a whitespace too much before the comma in Variante 2 @hauf-toni

**Comment by hauf-toni** [comment]
[PDF](https://github.com/digitalfabrik/entitlementcard/files/14265256/2402-Ehrenamtskarte-Bayern.pdf)

Hab die Größe des QR-Codes folgendermaßen angepasst. Seid ihr damit d'accord oder wollt ihr bei der alten Größe bleiben?


![Image](https://github.com/digitalfabrik/entitlementcard/assets/123894307/17741cc7-4d0a-4532-a7a4-eeef88aed803)
