### ISSUE TITLE
Add POIs to favorites

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1214]
As a user I want to add pois to favorites to find them easier on the map and store list

## Acceptance Criteria:
 - a store can be added to favorites by clicking favorites cta button on the store detailpage (icon changes to filled)
 - the store will be marked with a favorite icon on the map instead of the category icon. The icon should have the same size as the other icons
 - In the ButtomNavigationBar a "Favorite" item should be added that navigates to the favorites page
 - the favorites page contains a list of acceptance stores the user added to favorites. It should behave like the of the search page. (click on the item -> store detail page)
 - a favorite store can be removed from favorites on the store detail page by clicking the favorites button (icon changes to outlined)
 - the favorites will be saved on the device, so they will maintain after the app was closed

## Technical Tasks:
 - add a favorite icon to the mapstyle repository
 - provide the functionality to add/remove a store to the favorites on the store detail page. save the information on the device
 - mark the favorites with the favorites icon on the map
 - add a "favorite" BottomNavigationBar item
 - add a favorite page that shows store favorites. style similar to the search list
 
 ## Design:
- provide an material icon for the favorites
- provide a cta/toggle for the detail page to add the store to favorites
- provide a design that includes a new favorite item in the BottomActionBar
- provide a design for the favorites pages that should be similar/equal to the SearchList

## Some additional info:
To simplify this issue #750 should be done before

**Comment by IsabellaTG** [comment]
@f1sh1918 please review: https://www.figma.com/file/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?type=design&node-id=280%3A445&mode=design&t=wYIZWn6bcdOdFw8W-1

**Comment by f1sh1918** [comment]
@IsabellaTG i addressed some comments to you

**Comment by seluianova** [comment]
@dkehne could you please tell me if we need the ability to enable/disable this feature in the configuration per project?

**Comment by dkehne** [comment]
@seluianova no, we do not need to. it can be published for all projects
