### ISSUE TITLE
Mark processed applications

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1215]
**Is your feature request related to a problem? Please describe.**
As a service user i want to see a mark when a card was created from an application, to avoid multiple card creation for an application

**Describe the solution you'd like**
- add a column to the application table "cardCreated" (boolean, default= false)
- create a database migration to add this field
- when a card was created from an application set "cardCreated" field to true
- adjust the button text of "Karte erstellen" to "Karte erneut erstellen" if the "cardCreated" field is true
- add the filter checkbox in the AppStatus bar relates to #1216  ,  this can also be done in a separate tasks

**Comment by f1sh1918** [comment]
@dkehne in the nextcloud file is written that we should use sth like "Karte wurde bereits 1x erstellt"
Is it really needed to count that? A flag with `true/false` should be sufficient?

**Comment by dkehne** [comment]
@f1sh1918 a true/false flag is sufficient!

**Comment by hauf-toni** [comment]
While working on #1216 , I discovered that these two new functions have great potential to be implemented together and in interaction with each other.
This would have the advantage that users would perceive the change as less big, as it would feel more like one new feature than two. they would also have a central point in the interface where they can organize applications. You can find my design proposal [📌 here](https://www.figma.com/file/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?type=design&node-id=392%3A6485&mode=design&t=HMI5f8Vb19qX1QD9-1).

**Comment by hauf-toni** [comment]
as discussed with @f1sh1918 this issue will also be solved by implementing the design of #1216

**Comment by f1sh1918** [comment]
@hauf-toni i think this was a misunderstanding. Even if the issue is included in the design you mentioned this task can be done separately. There is no "hard" relation between these two tasks. Even if the filter bar is not visible yet the button label can be changed and also the rest of the needed functionality implemented as mentioned in the description.
