### ISSUE TITLE
Group applications by status

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1216]
As a user I want the be able to filter the applications by status. Currently the applications are only sorted

## Acceptance Criteria:
 - A filterbar will be displayed to the user -> design
 - Different filter options will be shown: Declined/Accepted/Open(Mixed verification status) /All
 - All applications is the default choice
 - Click on a filter option filters the applications by their status
 - Next to the status label is a tooltip button to explain the different status options.

## Technical Tasks:
 - Implement the status bar
 - filter the application by status
 - Select all applications by default
 - add tooltip information about the different application status, use a similar implementation than in "Benutzer verwalten"

Design: https://www.figma.com/file/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?type=design&node-id=392-6485&mode=design&t=tUxeUreZ8wW9JYf3-0

**Comment by michael-markl** [comment]
Applicants might withdraw their application in the middle of the approval process. Simply removing them from the administrators' view leads to them not knowing whether a colleague or the admin himself has deleted the application (possibly by accident) or if the user has withdrawn it. Still displaying it, but showing that it has been withdrawn makes it much clearer for the admin to understand what happened. He/She can then decide to delete it afterwards (or keep it and clarify possibly remaining questions about the application).

**Comment by f1sh1918** [comment]
ah right thats true. Currently we have no status `withdraw` but just a flag. We should think about adding it as a status (but what color ?)because the user wants to see it at instant and not just when collapsed
