### ISSUE TITLE
Version 3.2.3 can't be installed

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1237]
**Describe the bug**
I can not install the version 3.2.3 over the installed version 3.2.2. This applies for Bayern and Nürnberg on emulator and real device (Android)

**Screenshots**
![image](https://github.com/digitalfabrik/entitlementcard/assets/21236324/b5d5e494-d28c-4583-be78-f07eaabc97b2)

**Comment by f1sh1918** [comment]
@Docmale for Bayern it shows the same package Name?

**Comment by f1sh1918** [comment]
just tested 3.2.2 (prod) to update 3.2.3(beta) in play store and it worked. Can anyone confirm this error while installing new beta version?
@dkehne @michael-markl @sarahsporck

**Comment by Docmale** [comment]
Das ist völlig verrückt:
Auf einem anderen Emulator (Pixel_3a_API_34) habe ich per Store ohne Probleme Bayern aktualisiert. Nürnberg ebenfalls, allerdings ist der Emulator am Ende des Updates abgestürzt – passiert manchmal.

Auf dem ursprünglichen Emulator (Pixel_3a_API_33) Hat sich jetzt Nürnberg problemlos aktualisiert, aber Bayern zeigt nach wie vor den Fehler.

Auf meinem alten Handy (android 9) hat sich nach einem Fehlversuch jetzt Nürnberg aktualisiert, aber Bayern zeigt nach wie vor den Fehler

Auf meinem aktuellen Handy (Android 13) geht nach wie vor kein Update.
Auf meinem Tablet (Android 11) sind beide im Hintergrund aktualisiert worden.

**Comment by Docmale** [comment]
Auf dem einen Emulator API 33 nur über manuell gedownloadete apks, da hier kein Playsstore existiert. Für das Tablet (Android 9) nur über Playstore.
Für den anderen Emulator und die anderen physischen Geräte will ich dass noch mal nachstellen. Hier kann es sein, das ich auch die apk verwendet habe. Mehr Information folgt.

**Comment by Docmale** [comment]
I don’t have to mix up manually downloaded apk’s with new versions from play store. When using exclusively the play store no problem occurs.
