### ISSUE TITLE
Search loads very long on staging server

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#124]
The deployed backend on the staging server needs very long to respond to a search query.
The local version is very fast (at least for me and @maxammann )

**Comment by maxammann** [comment]
@Schedulaar is this tested, should I redeploy this?

**Comment by Schedulaar** [comment]
I'm not sure whether I actually deployed it, but I could reproduce the slow loading behavior locally and fixed it locally
