### ISSUE TITLE
Update Akzeptanzpartnerlist for Nuremberg-Pass

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/entitlementcard#1259]
We have received in new list for the Akzeptanzpartner: https://nextcloud.tuerantuer.org/index.php/f/6011222 
Maybe the data need to be formatted before.

**Comment by dkehne** [comment]
...on hold. There is a new list incoming.

**Comment by f1sh1918** [comment]
updated the list on the server. Import should be executed within the next two days
https://github.com/digitalfabrik/sozialpass-nuernberg-data/pull/10
