### ISSUE TITLE
Publish APK Files in GitHub again.

### ISSUE THREAD

**Issue by vthejay** [digitalfabrik/entitlementcard#1263]
As a user I want to download the APK Files directly from Github (especially in devices where Google Play is not installed)

The APKs are no longer available for the newer releases.
Please do release the APK Files for Bayern-FLOSS to Github.

Thanks.

**Comment by f1sh1918** [comment]
@vthejay currently we have to create the releases manually.
We have already an open issue for creating them automatically
https://github.com/digitalfabrik/entitlementcard/issues/1232

**Comment by ztefanie** [comment]
Done in https://github.com/digitalfabrik/entitlementcard/pull/1264
