### ISSUE TITLE
Adjust reactivation message card active on another device

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1266]
**Is your feature request related to a problem? Please describe.**
Currently the user might be confused if the card was activated on another device and then deleted and activated on a new device that a message will be shown that the card will be deactivated on the other device. 
Current message: "Ihre Karte ist bereits auf einem anderen Gerät aktiviert. Wenn Sie Ihre Karte auf diesem Gerät aktivieren, wird sie auf Ihrem anderen Gerät automatisch deaktiviert."

**Describe the solution you'd like**
Ihre Karte wurde bereits auf einem anderen Gerät aktiviert. Wenn Sie Ihre Karte auf diesem Gerät aktivieren, wird sie auf Ihrem anderen Gerät automatisch deaktiviert, falls sie dort noch aktiv ist.

**Describe alternatives you've considered**
Maybe someone finds a better wording.

**Additional context**
There is also a way with firebase notification to send a message on app uninstall but this may be quite difficult to implement for the use case

**Comment by seluianova** [comment]
> Maybe someone finds a better wording.

Maybe like this, to make it a little shorter?

#### Karte auf diesem Gerät aktivieren?
Ihre Karte wurde bereits auf einem anderen Gerät aktiviert. Wenn Sie fortfahren, wird Ihre Karte automatisch auf dem anderen Gerät deaktiviert, falls sie dort noch aktiv ist.
