### ISSUE TITLE
Update maplibre to latest

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1268]
**Is your feature request related to a problem? Please describe.**
We are still using an old version depending on a revision from march 23.

**Describe the solution you'd like**
We should update to the ref/tag of the latest version

**Additional context**
[Latest release](https://github.com/maplibre/flutter-maplibre-gl/releases/tag/0.18.0)

**Comment by maxammann** [comment]
What issues do you experience with the current version? I heard something about rendering issues.

**Comment by f1sh1918** [comment]
> What issues do you experience with the current version? I heard something about rendering issues.

I think you can find these issues in Sentry. There are no visible issues but lots of error reports. But we also have the for integreat. 
I mainly updated to get rid off the mapbox dep
