### ISSUE TITLE
Show distance to user location for stores

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1283]
As a user i would like to know the distance from my position to the acceptance store. This is an indicator how relevant a search result is for me

## Acceptance Criteria:
 - On the search page is a distance displayed for every list item if the location is enabled f.e. "1,0km entfernt"

## Technical Tasks:
 - add a distance label for every list item if user location is enabled

**Comment by michael-markl** [comment]
This is already implemented, but I just noticed, that there is a bug in the backend right now that prohibits that the distance is shown...
