### ISSUE TITLE
PDF Step Text misaligned

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1289]
**Describe the bug**
The text of the steps is misaligned for sozialpass pdf

<img width="446" alt="image" src="https://github.com/digitalfabrik/entitlementcard/assets/37902063/87c99492-638d-4917-a61b-786eaa3cbab2">

**To Reproduce**
1. Create a sozialpass card

**Expected behavior**
Text should be aligned properly

**Comment by f1sh1918** [comment]
hi @hauf-toni , seems like the pdf-template for sozialpass is misaligned
https://github.com/digitalfabrik/entitlementcard/blob/main/administration/src/project-configs/nuernberg/pdf-template.pdf

**Comment by f1sh1918** [comment]
@hauf-toni 
this part somehow looks a bit misaligned. check the double "nn"
<img width="389" alt="image" src="https://github.com/digitalfabrik/entitlementcard/assets/37902063/6809736e-eed6-4d5d-ae1d-bd7b55f38b6e">

**Comment by hauf-toni** [comment]
@f1sh1918 I can't really explain where this comes from, but I checked the pdf again and re-exported and uploaded it
