### ISSUE TITLE
Enable eslint rule "@typescript-eslint/no-unnecessary-condition"

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#1296]
**Is your feature request related to a problem? Please describe.**
I realized we sometimes have used optional chains or conditions where it was not necessary. There is a linting rule for this. Enable it.

**Describe the solution you'd like**
Linting shows me an error when i accidentally check a type even though it is known.
For this you have to set "parserOptions.project" to "tsconfig.json".

**Comment by steffenkleinle** [comment]
Perhaps it makes sense to use the eslint config from integreat. Perhpas we are too strict there though.

**Comment by steffenkleinle** [comment]
Already done in #1604.
