### ISSUE TITLE
Setup backend test database

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#1318]
To write tests for the endpoints we generally need a Database Connection.
That's why we need a test DB.
There are two approaches:
1. Use the local DB And fill it with test data (this is the approach the cms uses)
➕  db can be evaluated even after running the tests to simplify debugging
➕  can be used to load (fixed) test data for development testing
➖  local db could become corrupted if test data and other local data clashes. Especially if we use fixed unique keys in the test data this option can become unstable
➖ probably more effort to set up in the CI

2. Use an In-Memory DB with only the necessary data. This is often the quick and ea
➕ often easy setup
➕ static test data ensures that you always get the same result
➖ test performance can be bad and does not scale well with more tests

**Comment by deen13** [comment]
Hey @sarahsporck, have you come across [testcontainers](https://testcontainers.com/)? It bridges the gap between local and in-memory database and is easy to integrate.

**Comment by deen13** [comment]
[Testcontainers](https://testcontainers.com/) is also a good solution for bridging the gap between in-memory and local databases. Perhaps it could be helpful :)
