### ISSUE TITLE
Add function hexQRCodeFromProtobuf

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#1321]
**Is your feature request related to a problem? Please describe.**
For the csv export to datev we need to embedd the qrcode in a csv file. We found that a hex representation of the qrcode uses the least space in a string data format.

**Describe the solution you'd like**
A function that can convert a protobuf qrcode to a hex qrcode string. E.g.
1. generate protobuf qrcode 
2. convert to [qrcode matrix](https://github.com/digitalfabrik/entitlementcard/blob/03a0499a469610b16b215616d2cec7b5d93cb279/administration/src/util/qrcode.ts#L183)
3. convert "bitmap" to hexmap to avoid creating very large bitstrings

Step 2 -> 3 could look like this:
1110100100
1010011010
1110111100
0011110011
1011101001
0110001011
1100101011
1110110111
1011001101
1110010111

becomes 

3a4-29a-3bc-f3-2e9-18b-32b-3b7-2cd-397

using this conversion:
`matrix.map(row => parseInt(row, 2).toString(16)).join('-')`

Also make sure to write tests for this.

**Describe alternatives you've considered**

- do all of that in the backend

**Additional context**
We sent several proposals of encodings to the datev. This one was the most favored one from our side. The reason we don't send the "raw byte content" to the datev is because we use a custom qrcode format (see qrcode.ts) and we should not entrust an "outside" company to use this.
We could have also offered to provide a "package/module/script" that implements the qrcode conversion, but decided against that.

**Comment by michael-markl** [comment]
Similarly important: QR codes can get as large as 177×177 (or larger?). This means a single row might have >64 bits, therefore **we need to use BigInt** for converting between binary and hex format of each row!

Thus, I suggest to use as encoding function:
```js
matrix.map(row => BigInt("0b" + row).toString(16)).join('-')
```

and as decoding:
```js
const rows = '3a4-29a-3bc-f3-2e9-18b-32b-3b7-2cd-397'.split('-') 
rows.map(hex => BigInt("0x" + hex).toString(2).padStart(rows.length, '0'))
```

**Comment by ztefanie** [comment]
Thanks for adding this valuable hints. 

I still have some questions.

> We should make sure, that Datev uses the right inverse function of this encoding. The hex codes must be padded with zeros at the start when converting back to binary, like so:
> 
> ```js
> const rows = '3a4-29a-3bc-f3-2e9-18b-32b-3b7-2cd-397'.split('-') 
> rows.map(hex => BigInt("0x" + hex).toString(2).padStart(rows.length, '0'))
> ```

I do not understand this. With this code (if i get it right), we
1) split the hex string to an array of hex-sub-strings
2) for each hex-sub-string:
 2a) we create a BigInt
 2b) we convert the BigInt to a binary sub-string
 2c) we pad the binary substring with the number of hex-substrings

Why with the number of hex substrings? Why is the padding needed anyways?

And in the end with your function we get a string[], but we need UInt8Array. I could not find an easy way to convert this. 
Do we really want to convert from the binary-substring-array to UInt8Array or wouldn't it be easier to create an UInt8Array in the first place?

**Comment by michael-markl** [comment]
> And in the end with your function we get a string[], but we need UInt8Array. I could not find an easy way to convert this.

True, my function returns an array of strings (consisting of the chars '1' or '0'), so basically the QR code matrix.

>  2c) we pad the binary substring with the number of hex-substrings

This is to ensure that the decoded matrix is actually a matrix (ie. every row has the same number of columns).

(Of course, after that, if it's necessary you can convert each row to a uint8Array with something like the following)
```js
  const hexRows = '3a4-29a-3bc-f3-2e9-18b-32b-3b7-2cd-397'.split('-') 
  const stringMatrix = hexRows.map(hex => BigInt("0x" + hex).toString(2).padStart(rows.length, '0'))
  const uint8Matrix = stringMatrix.map(stringRow => Uint8Array.from(stringRow, char => char == '1'))
```

**Comment by sarahsporck** [comment]
> Similarly important: QR codes can get as large as 177×177 (or larger?). This means a single row might have >64 bits, therefore **we need to use BigInt** for converting between binary and hex format of each row!
> 

Our QR-Codes are always 49x49, so technically no need to worry here.

**Comment by michael-markl** [comment]
> Our QR-Codes are always 49x49, so technically no need to worry here.

So far, yes. But we should probably make it robust to qr code size changes. (Especially as JS can only represent integers up to ~2^53 safely and the next bigger size of qr codes would be 53bits.)
