### ISSUE TITLE
QR-code not working

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1341]
**Describe the bug**
The QR-code created in staging environment can't be activated in the app.
This is true for Nuremburg and Bavaria in Android as well as in ios

**To Reproduce**
1. create an entitlement card in staging environment.
2. Make shure your app is switched to staging environment
3. Try scanning the QR-code
4. See error "Fehler beim Lesen des Codes"

**Comment by f1sh1918** [comment]
which app version are u using? @Docmale

**Comment by Docmale** [comment]
2024.3.4

**Comment by f1sh1918** [comment]
> 2024.3.4

we didn't make an official beta release so far. So no need to test. It may also be related to the fact that the staging environment and the app beta are not that the same version

**Comment by Docmale** [comment]
Anyway, the bug has been fixed. Tested several QR-codes in version 2024.3.16
