### ISSUE TITLE
Add english store descriptions

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/entitlementcard#1343]
We have received in new list for the Akzeptanzpartner: https://nextcloud.tuerantuer.org/index.php/f/6040252
Maybe the data need to be formatted before. For the first time we also received the english translations.

**Comment by dkehne** [comment]
The englisch translations are only delivered/maintain for the description so we might just add the englisch text below the german text for now.

**Comment by f1sh1918** [comment]
@dkehne should i add some filler text link?

// english version
<english description>

i really prefer some proper implementation (financed)

**Comment by dkehne** [comment]
i will clarify that.

**Comment by f1sh1918** [comment]
![image](https://github.com/digitalfabrik/entitlementcard/assets/37902063/c47e292c-7770-40aa-84ba-c9d88af8a9f8)

@dkehne

**Comment by dkehne** [comment]
@f1sh1918 perfect

**Comment by f1sh1918** [comment]
@dkehne we have to wait until next release with english description import until i can update the store data.
If we need them faster, i have to create a separate data import file that excludes the english translations but can be imported immediately
