### ISSUE TITLE
Update used node version

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/entitlementcard#1361]
**Is your feature request related to a problem? Please describe.**
Currently some jobs (especially the ones using debian bullseye image) use node 12. Update so at least node 14 is used.
Check the install_toolbelt step finishes without warnings about a wrong node version.
Use a separate command for this, so future version updates only need to be done at one place.

**Comment by michael-markl** [comment]
Probably updating debian to bookworm will be enough [(they package version 18)](https://packages.debian.org/bookworm/nodejs). Related to #1362
