### ISSUE TITLE
strip spaces around names before comparison

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1381]
**Is your feature request related to a problem? Please describe.**
The comparison of the applicant's name with the name of the contact person in the organization fails if a name is accompanied by a space.

**Describe the solution you'd like**
Leading and trailing spaces should be removed before comparison

**Describe alternatives you've considered**
Leave as is.

Consider removing all non word character(hyphens, dots) and convert to lowercase letters before comparison:
Dr. Hans-Peter Müller Lüdenscheid -> drhanspeterüllerlüdenscheid 
Dr Hans Peter müller Lüdenscheid ->  drhanspeterüllerlüdenscheid

**Comment by michael-markl** [comment]
Where does this comparison take place?

**Comment by f1sh1918** [comment]
> Where does this comparison take place?

https://github.com/digitalfabrik/entitlementcard/pull/1252/files#
