### ISSUE TITLE
Add category 'Andere' (other)

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1388]
**Is your feature request related to a problem? Please describe.**
There is no icon for category 'Andere' on filterpage therefore I cannot ask for : What else?

**Describe the solution you'd like**
- add a filter icon button to the search page

**Comment by f1sh1918** [comment]
> @f1sh1918 is there a suitable icon for the category?

Currently we are using the normal marker icon as you can see on the map. Not sure if we want to use this. We also have to check if in the styles.json of the map repository this filter applies on the store symbol layer. I think currently this icon is used as a fallback if not category will be applied as filter

**Comment by seluianova** [comment]
@f1sh1918 ah, right, I didn't notice that we have this category already. Thanks.
But I assume it should display not only the items, that fall into this category, but all the items, that do not fall into the categories available in the panel, right?
