### ISSUE TITLE
Statistics created cards chart

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1399]
As a user i want to get an overview about created cards and activated cards

## Acceptance Criteria:
 - a region admin can see the activated and overall cards of the particular region
 - a project admin can see the activated and overall cards of the project
 - it should be filterable f.e. all/current year/last year
## Technical Tasks:
 - create query functions for statistic card information
 - implement a proper library for visualization
 - create a filter bar
 - activate for ehrenamt (via project config)
 - create a bar chart with region(s) --> y-axis and activatedCards/createdCards on x-axis (???)
 
 Some suggestions for open-source libraries if we want to display charts
 - https://recharts.org/en-US
 - https://github.com/reactchartjs/react-chartjs-2
 - https://github.com/plouc/nivo#readme

**Comment by f1sh1918** [comment]
Since the data would have been aggregated at lot until we could make nice charts or something, i think it would be sufficient to show a table?!
I mean we can not bring 93 regions into one chart so the question is what do we want to display in the chart

**Comment by michael-markl** [comment]
I guess Chart.js is the usual choice here (so I'd likely choose the react wrapper for chart.js), but if it works it works :D

**Comment by f1sh1918** [comment]
i was checking all the libraries mentioned above @michael-markl for (maintenance, functionality, package size and majority) and decided against charts.js (react-chartjs-2) because there was no release for more than a year and no progress in the repo for a while.
I decided to use nivo, since you can import the package for every chart type separately and its well maintained and documented

**Comment by f1sh1918** [comment]
To leverage the issue a little bit, i created a separate issue for the data csv export
https://github.com/digitalfabrik/entitlementcard/issues/1409
