### ISSUE TITLE
Activate card confirmation mail per region

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1400]
**Is your feature request related to a problem? Please describe.**
As a region i may not want to make the card earlier usable and not send an activation mail.

**Describe the solution you'd like**
- add a section in the administration where region admins can activate/deactivate the card confirmation mail
- send only card confirmation mail if the its activated
- set the confirmationFeatureFlag true

**Comment by dkehne** [comment]
@f1sh1918 description text for the checkbox is approved and should be in German
"Nach der Erstellung einer Karte verschickt das System eine E-Mail-Bestätigung an den Antragsstellenden mit einem Link zur Vorab-Aktivierung"
