### ISSUE TITLE
Adjust text for "wrong/broken link or not existing proposal"-page

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/entitlementcard#1404]
<img width="932" alt="Screenshot 2024-04-18 144247" src="https://github.com/digitalfabrik/entitlementcard/assets/4182469/b912a896-bf9b-4390-8079-8154ae3c69f0">

After a organization employee openend an approval link for a proposal that was already processes he was was confused by the text on the error page. 

Therefore I suggest do make some small adjustments of the content:

- Der Link wurde fehlerhaft [...]  ---> can stay as it is
- Ihr Antrag wurde bewillig [...] ---> change to    Für Antragsstellerinnen und Antragssteller: Ihr Antrag wurde bewilligt und die Karte [...] 
- Für Organisationen des ehrenamtlichen Engagements: Der Antrag wurde bereits abschließend bearbeitet oder von Ihnen genehmigt/abgelehnt. --> should be added as a new point
- Die Berechtigungen für den Erhalten [...] --> can stay as it is.

Please also adjust the headline to "Ihr Link ist nicht (mehr) gültig"

**Comment by f1sh1918** [comment]
What do mean with activation link @dkehne
An organization employee never receives an activation link

**Comment by dkehne** [comment]
I meant approval Link. Sorry for the misunderstanding
