### ISSUE TITLE
Clustering is too sparse

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#141]
**Describe the bug**
The map zoomed out pretty far (showing 1/4 of Bavaria) shows only very few clusters, which gives the impression that some cities don't have any accepting stores at all.

**Expected behavior**
Show more clusters, such that there is a point for each larger city

**Screenshots**
![Screenshot_20201230-155143](https://user-images.githubusercontent.com/7025199/103359051-68a44a00-4ab7-11eb-94ec-371e3f1d24ce.jpg)

**Comment by maxammann** [comment]
I think it looks way better now :)
