### ISSUE TITLE
Create endpoint for user data

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1416]
**Is your feature request related to a problem? Please describe.**
Create an http put endpoint that receives user data.
**Describe the solution you'd like**
- create new table: userHash, startDate, endDate, invalid, lastUpdated (timestamp)
- create a endpoint and function that receives data with a csv body
- check data validity: hash length, valid date format

**Comment by seluianova** [comment]
Input data example:
```
userHash, startDate, endDate, valid
dashj21sasd32, 12.05.2024, 12.10.2028, true
```

**Comment by seluianova** [comment]
Do we want to have 'koblenz' in the name of the table? Like, `koblenzusers` ?

**Comment by seluianova** [comment]
Might be nice to know how much data we expect in the CSV.
The processing time for 1000 lines takes about 2.82 seconds on my machine locally.

**Comment by michael-markl** [comment]
Regarding hash validity checks: We could also require that the first entry is a dummy entry with a hash deduced from dummy data. I think for other hashes we can only check their length. (as I've written in #1499 I think we should not add these parameters to the hashes).

**Comment by michael-markl** [comment]
> Re-tested for 20000 entries:
29.13 sec before warming up
17.78 sec after warming up
>
> We might want to think about the performance optimization then?

I don't think 30s would be a problem. It should only run once a week and we may require that it only runs at night for example.

**Comment by seluianova** [comment]
**Another open question:**
Do we want to receive userHash as a full argon2id-encoded value?
Example: `$argon2id$v=19$m=16,t=2,p=1$MTIzNDU2Nzg5QUJD$UIOJZIsSL8vXcuCB82xZ5E8tpH6sQd3d4U0uC02DP40`
Or maybe it would make more sence to receive only the hash-part?
Considering that the params are static (are they?)
