### ISSUE TITLE
Implement authentication for user data endpoint

### ISSUE THREAD

**Issue by seluianova** [digitalfabrik/entitlementcard#1417]
**Is your feature request related to a problem? Please describe.**
Client authentication must be implemented for the user data endpoint. 
It should be only valid for one ProjektID.

**Describe the solution you'd like**
Authentication method is to be defined.
Possible options:
- TLS Client Certificate (preferred)
- HTTP Basic Authentication

**Describe alternatives you've considered**
TBD

**Additional context**

#blocked by #1491

**Comment by f1sh1918** [comment]
@seluianova i added blocked since we can not create tokens yet, but it could also be done with a hardcoded token for the moment if we don't enable it for production
