### ISSUE TITLE
Create createCard endpoint

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1421]
**Is your feature request related to a problem? Please describe.**
Create a new endpoint (or adjust existing one) that receive the user data from the self service portal

**Describe the solution you'd like**
- add a function that receives user data: Name, Aktenzeichen and Birthday
- Hash this data and check if the user is permitted or not
- if not permitted throw an error
- if permitted send the cardData (Name, Aktenzeichen, Birthday, StartDate, and the other general needed data)
- rate limiting: since this endpoint is not protected, it should be ensured that IPs with too many requests should be blocked, especially because the argon2id calculation is expensive.

**Describe alternatives you've considered**
We could extend the current createCard mutation and allow creating without jwt token if its a particular projectId (not sure if that is secure enough)

blocked by https://github.com/digitalfabrik/entitlementcard/pull/1499

**Comment by seluianova** [comment]
> add a function that receives user data: Name, Aktenzeichen and Birthday

@f1sh1918 I guess the user would also need to select a region, wouldn't they?

**Comment by seluianova** [comment]
> rate limiting: since this endpoint is not protected, it should be ensured that IPs with too many requests should be blocked, especially because the argon2id calculation is expensive.

just got a sudden idea.
what if instead of a web form to issue a card, we create such form in the flutter app?
I believe this would solve the issue above and may also be more convenient for users because there would be no need to download and scan pdfs

**Comment by f1sh1918** [comment]
Its a good idea but we have lots of existing functionality in the "administration" like the card extensions, deeplinks which we can reuse. Further more we could also provide additionally a pdf if a service user supports a user that can not create the card by him/herself and just pass the pdf to him/her.

Normal use case is that the user doesn't have to scan or download the pdf but just create the card and then click a button with a `custom_scheme` deeplink which opens the app and activates the card.

**Comment by seluianova** [comment]
@f1sh1918 is a BUT that doesn't make sense to discuss or doch? :)

> which we can reuse
but is it bad if we don't have to?

> the card extensions
is it applicable to Koblenz? is it something that an unauthorized user does? (I'm not familiar with this process)

> Normal use case is that the user doesn't have to scan or download the pdf
right, but still an extra action and extra browser interaction.

**Comment by seluianova** [comment]
@f1sh1918 is a no-way but or to be discussed?

> which we can reuse

is it bad if we won't have to? I assumed it could mean for us to do less, not more

> the card extensions

is it applicable to Koblenz? is it something that an unauthorized user does? (I'm not familiar with this process)

> if a service user supports a user that can not create the card

is it a plausible case when the form has 3 fields?

> Normal use case is that the user doesn't have to scan or download the pdf

right, but still an extra action and extra browser interaction.

**Comment by seluianova** [comment]
> is it bad if we won't have to? I assumed it could mean for us to do less, not more (or am I missing something?)

Just found an answer here and it seems to me that both actions could be done through the app 
https://github.com/digitalfabrik/entitlementcard/issues/1430

**Comment by f1sh1918** [comment]
I think we discussed the process we gonna go with the customer. All projects have a separate "beantragen" function in the browser. But anyway:

If we move the function in the app we can not easily use the pdf creation and we might need that.

Additionally we have an easy extendable card configuration in the administration where we already have All fields with validation except the referenceNumber.

We had a quite strict budget for this project and i don't see that the improvement is that huge that it's worth the additional effort

**Comment by f1sh1918** [comment]
Ah and one thing I forgot was that we should keep the possibility to create a static printed pass

**Comment by seluianova** [comment]
Do we want to have a column userentitlements_id (or any-better-name) in the cards table?
