### ISSUE TITLE
Create PDF for Koblenz Pass

### ISSUE THREAD

**Issue by seluianova** [digitalfabrik/entitlementcard#1422]
**Is your feature request related to a problem? Please describe.**
If a service user has to support the customer, it should be possible to download a pdf after card creation and provide it to the customer

**Describe the solution you'd like**
- fill pdf template for koblenz pass
- the pdf creation will be triggered here https://github.com/digitalfabrik/entitlementcard/issues/1419
- pdf template has to be provided by ui/ux
- use the koblenz custom font TeX Gyre Heros

**Additional context**
TBD

**Comment by f1sh1918** [comment]
@hauf-toni 
you can base the pdf template on nuernberg
- replace Nürnberg with Koblenz
- download link will be "download.koblenz.sozialpass.app" instead
- get logos, card background and missing texts from daniel
- we don't need an address field and also not the D-Ticket area (talk to daniel about that)

**Comment by dkehne** [comment]
@hauf-toni you can find the resources here: https://nextcloud.tuerantuer.org/index.php/f/6094223

**Comment by hauf-toni** [comment]
[240811-Ehrenamtskarte-Koblenz.pdf](https://github.com/user-attachments/files/16578245/240811-Ehrenamtskarte-Koblenz.pdf)

@f1sh1918 please review the attached pdf

**Comment by f1sh1918** [comment]
@hauf-toni there is the deeplink activation by clicking on the qr code missing. For Koblenz you can do both as we have in bavaria

**Comment by hauf-toni** [comment]
@f1sh1918 yes, I'll be happy to add to it as soon as the content + design have been approved. do you have any feedback an that?

**Comment by f1sh1918** [comment]
@hauf-toni for me the design looks good to me. The primary color for the project will be purple right?
I think @dkehne has to let the customer approve what will be printed on the pass f.e. "Amt für Existenzsicherung.." Probably this has to be adjusted

**Comment by dkehne** [comment]
@hauf-toni just 2 things:
1. Can you remove the "Amt für Existenzsicherung und soziale Integration - Sozialamt" text
2. Is the gray background intentionally placed behind the logos?

**Comment by hauf-toni** [comment]
@dkehne @f1sh1918 pdf now available [here](https://nextcloud.tuerantuer.org/index.php/apps/files/files?dir=/Projects/Digitale%20Berechtigungskarte/Stadt%20Koblenz/Releasedokumente), hyperlink and feedback are included

**Comment by f1sh1918** [comment]
@hauf-toni 
i still can not find the instruction of the deeplink activation as we have them in the bavarian pdf.
And is there any hint which primary color (hex) we gonna have?

**Comment by dkehne** [comment]
Ah right, we need the adjustments for the deep linking as well. @hauf-toni i will wait with sending it to koblenz until this is implemented as well.

**Comment by hauf-toni** [comment]
[240827-Ehrenamtskarte-Koblenz.pdf](https://github.com/user-attachments/files/16757910/240827-Ehrenamtskarte-Koblenz.pdf) - link will be added when the pdf is approved
Primary color: Koblenz-Lila #a34b97
@f1sh1918 @dkehne

**Comment by ztefanie** [comment]
@dkehne any update here on this?

**Comment by dkehne** [comment]
no, it's the last deliverable missing and i have just asked again and put the deadline to deliver on 8th Nov

**Comment by ztefanie** [comment]
Koblenz delivered the final PDF, see here:
[240811-Ehrenamtskarte-Koblenz.pdf](https://github.com/user-attachments/files/17674712/240811-Ehrenamtskarte-Koblenz.pdf)
