### ISSUE TITLE
Extend card

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1430]
As a app user i want to be able to extend my card

## Acceptance Criteria:
 - If a card is extendable the user will get a notification
 - the card is extendable if its expiry date is earlier than the endDate of the associated user entitlement
 - on click "extend" the user gets forwarded to the self service portal and the user data form will be prefilled

## Technical Tasks:
- [x] add a notification area when a card is extendable https://github.com/digitalfabrik/entitlementcard/pull/1772
 - [x] provide a link with queryParams to the self service portal, fill the form with the passed data https://github.com/digitalfabrik/entitlementcard/pull/1749
 - [ ] add queryParams to applicationUrl in native app

**Comment by seluianova** [comment]
Couple questions:

> if the card can be extended

how exactly do we define it? expirationDate >= today, or?

> If a card is extendable the user will get a notification

should it be a push-notification?
or should the user only see it when the app is opened?

should it be shown immediately when the application is opened - so, over the map, or on the Ausweisen tab?

> the user gets the new (updated) card

do we want to create a new card or update an existing one?
if we create a new card - what do we do with the static code?

**Comment by f1sh1918** [comment]
i talked to daniel and card extension via self service portal via link with query params is okay. We can just implement this

**Comment by seluianova** [comment]
@hauf-toni could you propose how best to display a notification in the app that a card extension is available?
it is better to display the notification immediately after the application is launched (so - over the map), or when the Ausweisen tab is opened? how should the notification look like?

**Comment by hauf-toni** [comment]
You can find the design [📍 here](https://www.figma.com/design/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?node-id=792-3416&t=kUofvHMqh07BbICq-1).

**Comment by seluianova** [comment]
@hauf-toni thanks, I have a couple more questions:
what would you recommend for the case, when the card has already expired?
currently it looks like this:
![image](https://github.com/user-attachments/assets/b1b94c8d-d5ea-4c61-b393-ab46863dde87)
should we leave it as it is and just open the pre-filled form when the user clicks on "KoblenzPass beatragen oder verlängern"?
the only concern in this case I have:
the item says “beatragen ODER verlängern”, and if the user actually wants to request a pass with other data, he will still get a pre-filled form with the previous card's details.

**Comment by ztefanie** [comment]
> 2. regarding the text "your card is about to expire".
>    what if the card can be extended, but it expires in 1 year, for example. do we want to show this notification in such case?
>    maybe we want to show it only when a card can be extended AND expire no later than in 3 month, or something like this?
>    tagging @f1sh1918 @ztefanie if you have an opinion on that

I agree, this sounds like a good way to go :+1: 

> 3. what would you recommend for the case, when the card has already expired?

I think for this issue of extending it seems fine. In general I think it would be nice, if expired cards are displayed differently, e.g. in grey, to make it clear at the first look, that they are expired.

>    we could pre-fill the form when a user clicks on "KoblenzPass beatragen oder verlängern", but is it necessary?
>    the item says “beatragen ODER verlängern”, so what if a user wants to create a card with the new data, but a pre-filled form with the previous card's details will be opened and the user will have to clear it first. do you think it's fine?
>    or do we need a different view for expired but extendable cards?

I think it would be nice to prefil the form, because a user may need to look up his/her reference number somewhere which is annoying, so just prefilling it seems fine, but I agree it should still be possible to edit the data in case the user wants to change something.

**Comment by hauf-toni** [comment]
2. Agreed!
3. I have added a design proposal for that case, see [📌 here](https://www.figma.com/design/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?node-id=812-34&t=Fe79X9Evb5Dhb4YG-1).
