### ISSUE TITLE
Add store categories for koblenz

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1434]
**Is your feature request related to a problem? Please describe.**
As a user i want to have different categories for my acceptances stores to better be able to filter for stores and show different icons on the map to distinguish

**Describe the solution you'd like**
- add the same store categories as nuernberg in the buildConfig

**Comment by f1sh1918** [comment]
To make things not more complicated as needed, we could just provide the current categories we have and let the customer select 10 of the them. If the customer needs additional categories which we don't have we can create them. These categories have only fixed icons and a description in the database which will not be displayed in the app, since we use translations. The category names can be adjusted in the particular translations of each project.

Does anyone see any problems in that?

**Comment by ztefanie** [comment]
Yes i added the store categories already
