### ISSUE TITLE
Bulk Csv card export fails

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1468]
**Describe the bug**
When multiple csv input data is used for csv data export the export results in an unknown error

**To Reproduce**
1. Karten erstellen
2. Mehrere Karten erstellen and choose csv
3. Click CSV Export

**Expected behavior**
Csv card data will be exported

**Comment by ztefanie** [comment]
Also the pdf export for multiple cards is broken, same error.
