### ISSUE TITLE
Black screen when changing to 'allow location'

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1483]
**Describe the bug**
If I switch in system settings from location not allowed to allow and go back to app Ehrenamtskarte the map vanishes and a black sreen is shown. Removing app from Background list and restart app heels the situation.

**To Reproduce**
1. in system settings don't allow location
2. start app
3. in system settings allow location ( important: not ba using the setting in the app)
4. go back to app
5. see black screen

All fine when using the setting in the app.

**Comment by f1sh1918** [comment]
we have to check if this is a duplicate to [#1462](https://github.com/digitalfabrik/entitlementcard/issues/1462)

**Comment by f1sh1918** [comment]
this not related to allow location change but to #1462 and a general problem. If #1462 is fixed and the issue is still there, we can open the issue again
