### ISSUE TITLE
Improve sorting store list

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1487]
**Is your feature request related to a problem? Please describe.**
As a user i want to sort the store item either alphabetically or by distance. In the current implementation the sorting is not clear and can not be changed

**Describe the solution you'd like**
- Indicate in the headline of the store list (currently "Suchergebnisse" ) whether its sorted alphabetically or by distance by adding the particular label
- Show the FAB button (that only will be displayed once after permitting location) permanently.
- Sort the store list by default alphabetically if location permission is not given
- Sort the store list by store distance if location permission is given
- Depending on which sorting is applied, give the user the ability with the FAB button to change the sorting

**Additional context**

**Comment by f1sh1918** [comment]
For me the button only disapears if it was clicked once.
I agree that it might be confusing that there is no "indicator" which sorting was used.
I think we should sort them automatically nearby if user location is available and alphabetically if user location is disabled and indicate the sorting somewhere

**Comment by f1sh1918** [comment]
i think if we implement option 2 an option could be.

1. Default label for search results "Suchresultate (alphabetisch sortiert)
2. Click on in meiner Nähe suchen 
3. The label "Suchresultate" will change to "Suchresultate (in der Nähe)
4. FAB Button changes to "Alphabetisch suchen"
5. Click on it sorting changes to default and label changes to 1.

What do you think about that @Docmale , @ztefanie , @michael-markl  and @seluianova 
I could also ask toni for help

**Comment by michael-markl** [comment]
Yeah it's a tough one, because (as far as I can see) there's really no reason to sort alphabetically except if there is no location available. so having a huge button just for sorting Alphabetically seems bad to me.

**Comment by michael-markl** [comment]
I removed the `bug` flag because it's not a bug (the button only displays if the location permission was not given at the time of app startup), but I admit it might be confusing to the user

**Comment by f1sh1918** [comment]
Maybe we ask @hauf-toni for her opinion

**Comment by f1sh1918** [comment]
@hauf-toni thx for your input. I updated the task description and the task is ready to go
