### ISSUE TITLE
Add a possibility to create a token for api requests

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/entitlementcard#1491]
**Is your feature request related to a problem? Please describe.**
A user that is logged in should be able to create a token which than can be used to make api requests to the protected "user data uploading" endpoint

**Describe the solution you'd like**
- Think about / discuss which role should have the rights to create such a token, either the project admin or a special role we introduce for this
- Add a function to create this token, decide which algorithm is good for this (secure)
- this token must be saved to the database hashed
- Add a section to the settings in the digitale druckerei, where an authenticated user can create this token and delete it, but not few it, as it is hashed and this is not possible, add a hint about this to the ui

Edit: For Koblenz it is ok if the existing admin role can create the api tokens.

**Comment by f1sh1918** [comment]
@ztefanie are you working in this or can i take it since you are soon on vacation and so other issues depend on it
