### ISSUE TITLE
Mobile scanner does not recognize barcodes

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1507]
**Describe the bug**
On some Android 14 devices like Samsung Galaxy A23 5g the mobile scanner does not recognize barcodes

**To Reproduce**
1. Use Samsung Galaxy A23 5G
2. Activate Card
3. Scan the activation barcode
4. Nothing happens

**Expected behavior**
The barcode will be recognized and the card can be activated

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A23 5G
 - OS: Android 14

**Additional context**
Related issue: https://github.com/juliansteenbakker/mobile_scanner/issues/1077

Update: This issue comes from upstream android camera issue and is device related
https://github.com/juliansteenbakker/mobile_scanner/issues/698

**Comment by ztefanie** [comment]
Issue was again reported with these details:
Samsung Handy A 23 5 G.
Die Android Version ist 14.
Die Version der App ist 2024, 3.16 (die aktuellste über Play Store verfügbar)

**Comment by ztefanie** [comment]
Happend again:
goldene Ehrenamtskarte.
Kaufbeuren 
App-Version 2024.5.5

**Comment by vthejay** [comment]
The problem exists with the Version 2024.5.5. as well (the latest Version)
Device Samsung A23 5g
Android 14

**Comment by vthejay** [comment]
with the test device Samsung A23 5G, I can reproduce the problem. The scanner does not recognize the QR code at all.
I have already activated the Developer Options on the Samsung A23.
I can get the logfiles through ADB later today.  :grinning: 
So, finally, we can reproduce this problem....
BTW, interesting: The test device has Android 13

**Comment by f1sh1918** [comment]
There is a patch mentioned to get more logs but it looks like we first have to ugrade to recent version v5.1.1 which has some breaking changes

**Comment by f1sh1918** [comment]
fixed by #1507
