### ISSUE TITLE
Leading comma in the 1st line

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1508]
**Describe the bug**
Missing Region befor aleading comma in the headline

**To Reproduce**
1. export statistic
2. open CSV-file
3. see no Region

**Expected behavior**
Title 'Region' is set befor leading comma

**Screenshots**
![image](https://github.com/digitalfabrik/entitlementcard/assets/21236324/e2a113f0-d7b8-40fe-9b8e-4dfdb4ce036e)

**Comment by michael-markl** [comment]
The comma is fine but there should be a name for the column like "Stadt" or so in front of it :D
