### ISSUE TITLE
emails not sent

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1527]
**Describe the bug**
When I fill out and submit an application I get the message 'Email konnte nicht an...'. However, the application appears in the list of received applications. Neither the contact nor the applicant receives an email.

**To Reproduce**
1.See the last applicatins in Augsburg

![image](https://github.com/digitalfabrik/entitlementcard/assets/21236324/0aca53ab-8410-42c5-900c-6d0e0d437f21)

**Comment by f1sh1918** [comment]
Here are the server logs
```js
Jul 03 09:25:39 entitlementcard-test.tuerantuer.org backend[1446911]: [JettyServerThreadPool-21] ERROR app.ehrenamtskarte.backend.mail.Mailer - Failed to send email [Subject: 'Antrag erfolgreich eingereicht'], reason: Third party error
Jul 03 09:25:39 entitlementcard-test.tuerantuer.org backend[1446911]: [JettyServerThreadPool-21] ERROR app.ehrenamtskarte.backend.common.webservice.GraphQLExceptionHandler - Exception while fetching data (/result) : null
```
