### ISSUE TITLE
Typo in invalid card information

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1529]
**Describe the bug**
When a card becomes invalid the message "Ihr Pass ist ungülig. **_Sie_** wurde entweder widerrufen oder...". It should be changed to "Ihr Pass ist ungülig. **_Er_** wurde entweder widerrufen oder..."

**To Reproduce**
1. Make pass invalid by re-activate it on another device
2. restart Nürnberg Pass on the 1. device
3. view invalid message

**Comment by ztefanie** [comment]
Hint: This needs to be adjusted on a project level, as it is "die Ehrenamtskarte" (bayern) und "der Pass" (nürnberg)
