### ISSUE TITLE
Update Android Target API

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/entitlementcard#1531]
**Is your feature request related to a problem? Please describe.**
Google requirement: Deadline August 31 2024

- New apps and app updates must target Android 14 (API level 34) to be submitted to Google Play

- Existing apps must target Android 13 (API level 33) or higher to remain available to new users on devices running Android OS higher than your app’s target API level. Apps that target Android 12 (API level 31) or lower ( Android 10 or lower for Wear OS and Android 11 or lower for TV OS), will only be available on devices running Android OS that are the same or lower than your apps’ target API level.

See more here:
https://support.google.com/googleplay/android-developer/answer/11926878?hl=en#:~:text=Starting%20August%2031%202024%3A,target%20Android%2013%20or%20higher).

**Comment by f1sh1918** [comment]
We already use api level 34 as target sdk
<img width="869" alt="image" src="https://github.com/user-attachments/assets/a35c96fd-bc39-4328-8e16-b87103fb032d">

**Comment by f1sh1918** [comment]
already done

**Comment by f1sh1918** [comment]
already done
