### ISSUE TITLE
Fix missing metadata for ios promotion

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1543]
**Is your feature request related to a problem? Please describe.**
For the promotion of the current ios app version some meta data is missing. Looks like the whats new wasn't provided anymore

**Describe the solution you'd like**
- add whats new f.e. ("Wir haben die App weiter für Sie verbessert und einige Fehler entfernt. Helfen Sie mit die App zu verbessern, indem Sie uns Feedback geben.")

**Additional context**
[Add any other context or screenshots about the feature request here.](https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/5925/workflows/df2066eb-a8c9-472d-9bb2-8de0793be8df/jobs/42586)

**Comment by f1sh1918** [comment]
@ztefanie 
maybe my issue since i restructured the metadata here https://github.com/digitalfabrik/entitlementcard/pull/1503
But not sure why "whats new" was deleted in the store
I wonder whether we need release notes in the metadata since they are static in the moment and i think we could just delete them and maintain in the store or set `skip_metadata` in fastlane, since its `false` in moment from testflight to production.

**Comment by f1sh1918** [comment]
Unfortunately the issue still exists
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/6250/workflows/68924037-acd2-443b-8231-e7b6bbb628c4/jobs/44369

**Comment by ztefanie** [comment]
I think the path is set wrongly. i think it should be "metadata_path: `./fastlane/#{build_config_name}/metadata`
As we agrred to have all the metadata in the repo (like screeshots) it makes sense to fix this issue.
I would prefer to also have the release notes in the repo, but I am also fine if you move it, but the metadata-folder structure should be fixed anyways especially because of the screenshots

**Comment by steffenkleinle** [comment]
> I think the path is set wrongly. My first thougths are: maybe the path is wrong, maybe this will work: "metadata_path: `./fastlane/#{build_config_name}/metadata`

Yes, that would be my guess, too. In integreat we use the path: `./ios/fastlane/#{build_config_name}/metadata`. Accordingly, the path here should probably be:
`./ios/fastlane/#{build_config_name}/metadata`.

> or it is because nuernberg is also available in english and therefore english release notes are mandatory.

Seems not to be the case, checked in AppStoreConnect, app is only available in German.

**Comment by f1sh1918** [comment]
alright. thx for all your help :)
