### ISSUE TITLE
Nürnberg Pass - replace Link

### ISSUE THREAD

**Issue by FritjofK** [digitalfabrik/entitlementcard#1545]
**Is your feature request related to a problem? Please describe.**
Daniel aksed me to foward you this e-mail from the city of Nuremberg as an issue to replace the link mentioned here. 

**Describe the solution you'd like**
Hallo Herr Kehne,
ich schicke Ihnen den neuen Link für die N-P Beantragung und die neue Liste

https://online-service2.nuernberg.de/intelliform/forms/n/500_sha/500_sha_d_formup_nuernberg_pass/index

Schöne Grüße
Stadt Nürnberg

**Describe alternatives you've considered**

**Additional context**

**Comment by dkehne** [comment]
I will going to ask for time schedule/urgency of the replacement...

**Comment by f1sh1918** [comment]
@dkehne i think the links is already in use?
https://beantragen.nuernberg.sozialpass.app -> forward to the correct link

**Comment by f1sh1918** [comment]
the link is already the correct one
