### ISSUE TITLE
Provide data privacy text

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1548]
**Is your feature request related to a problem? Please describe.**
As a user i have to accept the data privacy text before creating a card

**Describe the solution you'd like**
- update the template `/koblenz/ dataPrivacyBase.tsx` with the content of the docx file

Additional information:
data privacy text: https://nextcloud.tuerantuer.org/index.php/apps/files/files/6510700

**Comment by f1sh1918** [comment]
@dkehne we need a data privacy text
You can use this file as a base
https://github.com/digitalfabrik/entitlementcard/blob/main/administration/src/project-configs/nuernberg/dataPrivacyBase.tsx

**Comment by dkehne** [comment]
I have already created a template from nuremberg and placed it on 21th May to Koblenz. Still now response because they are internally clarifying...
[Datenschutzerklärung-Koblenz-Pass-Entwurf.docx](https://github.com/user-attachments/files/16747316/Datenschutzerklarung-Koblenz-Pass-Entwurf.docx)
