### ISSUE TITLE
Create store entry for android and ios

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1549]
**Is your feature request related to a problem? Please describe.**
Create a store entry for the koblenz pass for ios and android

**Describe the solution you'd like**
- create in play store
- create in appstoreconnect

TODO: add screenshots
adjust name to: KoblenzPass

**Comment by f1sh1918** [comment]
blocked until we get a response from koblenz if the data privacy issues are solved

**Comment by ztefanie** [comment]
Store entries for apple and google are created. 
A new key is added to the keystore, see the PR in the credentials repo.

For google a view forms need to be filled out, i already started doing it and we only need to finish it before publishing. 

both store entries now mainly need a first upload.

**Comment by ztefanie** [comment]
Finished this task, both store entries are set up and a first betra release is done.
