### ISSUE TITLE
Create verein360 application data endpoint

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1620]
**Is your feature request related to a problem? Please describe.**
As a verein360 user i want to be able to send application data from our system to the entitlementcard api

**Describe the solution you'd like**
- create a mutation that receives:
- personal data: name, surname, street, houseNr, postalCode, location, country, additionalAddressInformation, email, telephone (optional), dateOfBirth
- organization data: name, street, houseNr, postalCode, location, country
- contact person data(organization): name (incl. surname), email, telephone
- function data: responsibility, workSince, amountOfWork
- regionIdentier (customer will get a list postalCode -> regionIdentifier `plz_ort_bayern.csv`)
https://github.com/digitalfabrik/entitlementcard/blob/main/backend/src/main/resources/import/plz_ort_bayern.csv

Infos: Types of the fields can be found in the database : applications->jsonValue
- Validation will be done in a separate ticket
- Endpoint protection will be done in a separate ticket (userRole, api token)

**Comment by dkehne** [comment]
function data: they should also deliver amountOfWork (number) so that the municipality can check if they really meet the requirements (>=5h work per week)
