### ISSUE TITLE
Add role and option to create api tokens for verein 360

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1624]
**Is your feature request related to a problem? Please describe.**
If the mutation to add applications is called with the "isAlreadyVerified" flag it needs to be protected with the api token. These api tokens should be created by a user with a specific role.

**Describe the solution you'd like**
- create a separate role "Verein 360" that can create api tokens
- check if the api token has the correct access rights (is role Verein360 and project eak)

**Comment by f1sh1918** [comment]
@ztefanie not sure if we also have to add the possibility to create a user with this role via administration gui or it is sufficient to create it via runConfig and backend command, since we probably will only need one. Please check if there is anything to add in this ticket :)

**Comment by seluianova** [comment]
@f1sh1918 @ztefanie just for my better understanding, could you please clarify why we decided to add a new role for that?
why not allow tokens to be created by project admin, for example?

**Comment by seluianova** [comment]
@ztefanie right, makes sense, thanks for the reply!
