### ISSUE TITLE
Show Verein360 icon in application overview

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1625]
**Is your feature request related to a problem? Please describe.**
As a service user i want to get a quick overview if the application is from verein360

**Describe the solution you'd like**
- show an verein360 icon next to the application that have the `applicationType` value "Verein360"

**Comment by f1sh1918** [comment]
One question from my side. Do we need a separate field in the application table like "Source" or is it sufficient to use the "applicationType"
I mean for the display of the icon in the frontend it should be sufficient but if we may want to use it for statistics or sth similar it might be easier to also save information in a "source" field or sth

**Comment by f1sh1918** [comment]
@dkehne
We need a particular icon that we should display. It would be good to have a similar format
<img width="119" alt="image" src="https://github.com/user-attachments/assets/5b0dcf50-d850-42ce-9fb4-30116f81cfc0">

**Comment by ztefanie** [comment]
I think this should definitely be a new separate "source" field. As if we reuse the "ApplicationType" field we cannot  save if an application is an first or renewal application. And it is just something completely different.
