### ISSUE TITLE
Improve the Geburtsdatum field in the card creation form

### ISSUE THREAD

**Issue by seluianova** [digitalfabrik/entitlementcard#1672]
**Describe the bug**
As a koblenz pass user i want to type in my birthday as easy as possible on my mobile device

Acceptance Criteria:
- user can click in the date field and type in the date with the keyboard
- user can select the date from the datepicker if the icon was clicked
- user can clear the input via clear button or using backspace on desktop
- if the date is in the future the user gets "Error Message" below the field

Check here the MUI components (desktop version)
https://mui.com/x/react-date-pickers/date-picker/

**Comment by f1sh1918** [comment]
@seluianova maybe we also think about a general improvement task for the birthday field.
Also placeholder is not used as it should because of styling issues
I think it would be better to also be able to type in the date, in mobile mode since picking the day, month and year might be annoying and some people reported not to know how to select the year. (Even this is just standard date picker html component)

**Comment by seluianova** [comment]
> I think it would be better to also be able to type in the date

not sure if I understand this part, because I think I can currently type in the date 🤔

**Comment by seluianova** [comment]
just an idea to consider:
we could also use 3 dropdowns to select birthday (day, month, year).
I would solve some of the issues I believe

**Comment by seluianova** [comment]
just an idea to consider:
we could also use 3 dropdowns (day, month, year) to select birthday, with the ability to type in.
or just 3 text fields with the validation.
it would solve some of the issues I believe.
(_I just agree too that looking up the year on the calendar isn't as convenient. maybe we don't actually need a calendar there?_)

**Comment by f1sh1918** [comment]
> It might make sense to use a date as default/placeholder that clearly indicates the date format, i.e. a day > 12, e.g. 31.01.1980 or something. Especially helpful if your device is using mm/dd/yyyy or dd/mm/yyyy.

this is now already applied `tt.mm.yyyy` for german localization

**Comment by f1sh1918** [comment]
@hauf-toni we currently have the issue that the user on the mobile device needs a lot of effort to select the birthday due to scrolling the years, etc. Can you provide a proper proposal for that how to implement the "birthday" picker :)

**Comment by hauf-toni** [comment]
@f1sh1918 I really like this one: https://mui.com/x/react-date-pickers/date-calendar/
What do you think? Would you like a design proposal as well?

**Comment by f1sh1918** [comment]
@hauf-toni  this is just a calendar but we need also a form field.
This would be an option
https://mui.com/x/react-date-pickers/date-picker/

**Comment by hauf-toni** [comment]
@f1sh1918 you're right, I would recommend [this slightly customized version ](https://www.figma.com/design/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?node-id=766-959&t=IaQ6ViFoI7WdeR4r-1)instead 📆

**Comment by f1sh1918** [comment]
> @f1sh1918 you're right, I would recommend [this slightly customized version ](https://www.figma.com/design/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?node-id=766-959&t=IaQ6ViFoI7WdeR4r-1)instead 📆

Where did you find this picker?
Its not like we can highly customize these view from MUI that base on standard html components @hauf-toni f.e. showing month and year next to each other. I at least have no clue how to access and override these basic html components
