### ISSUE TITLE
Could not parse date from string ''. RangeError: Parameters do not form a valid PlainDate.

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1673]
**Describe the bug**
We are facing a parsing error when we try to parse the input to PlainDate

**To Reproduce**
1. Login as region admin or region manager for nuernberg
2. Go to create card
3. Type a "0" in the Birthday field
4. See error in console

**Expected behavior**
Parsing works without errors

**Comment by steffenkleinle** [comment]
I think this was only a `console.log` anyway, but I think I already fixed it with #1667.
