### ISSUE TITLE
Add the ability to delete an old card during deeplink activation

### ISSUE THREAD

**Issue by seluianova** [digitalfabrik/entitlementcard#1685]
**Is your feature request related to a problem? Please describe.**
When a user already has a card in the app and tries to activate a new card via a deep link, he receives the message `Ihr Kartenlimit wurde erreicht. Bitte entfernen Sie vorher eine Karte, damit Sie eine neue aktivieren können.` and is forced to first delete the old card and then repeat the activation.

It would be nice to remove the old card during the deeplink activation, instead of forcing the user to do it manually.

**Describe the solution you'd like**
- display the message like 'You already have an activated card on this device. If you proceed with the actvation, the old card will be removed.'
- remove the old card, if the user wants to proceed, then add a new one.

**Describe alternatives you've considered**
Leave as is

**Additional context**

**Comment by f1sh1918** [comment]
@seluianova
We may consider that this can also happen for activation via scanning activation code. So maybe this can be implemented for both cases or a seperate issue  should be created

**Comment by seluianova** [comment]
> We may consider that this can also happen for activation via scanning activation code. So maybe this can be implemented for both cases or a seperate issue should be created

Scanning of the new code is currently not available until you remove the old card, and you don't have to switch between pdf/app/browser to do that, so not sure if that makes sense.

**Comment by seluianova** [comment]
Cards amount will be increased instead https://github.com/digitalfabrik/entitlementcard/issues/1741

**Comment by seluianova** [comment]
oops, thanks @steffenkleinle
