### ISSUE TITLE
Fix qr code invalid for ios deep links

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/entitlementcard#1686]
**Describe the bug**
When opening an activation deep link for Koblenz all data is displayed properly, but then the error "qr code is invalid" is shown.

**To Reproduce**
Create a card via /erstellen
open the deep link
see all valid data in the preview
click button to activate
get error "qr code invalid"

**Expected behavior**
Card should be activated

**Additional context**
iOS, Koblenz

**Comment by f1sh1918** [comment]
As described in my issue. Deeplinks are not configured properly in administration for koblenz because build Config from app is missing.

There is already an issue for that
https://github.com/digitalfabrik/entitlementcard/issues/1647

**Comment by f1sh1918** [comment]
this should be already fixed with #1431
