### ISSUE TITLE
Two cards are created in card creation from

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/entitlementcard#1687]
**Describe the bug**
When creating a Koblenz card, there are two entries in the database

**To Reproduce**
1. Go to /erstellen
2. Create a card
3. Check database
4. See duplicated entries

**Expected behavior**
only one card is created in the database

**Screenshots**
![image](https://github.com/user-attachments/assets/69e68d3f-314a-43c5-8f6e-166504823dc1)

**Additional context**
Happend both on macbook and my linux laptop

**Comment by f1sh1918** [comment]
The creation of a static and dynamic card is the expected behavior
