### ISSUE TITLE
Verify imported Anmeldecodes

### ISSUE THREAD

**Issue by PaulaWi** [digitalfabrik/entitlementcard#17]
As an EAK owner, who received an anmeldecode (QR code), I want to authorize myself in the app to prove my status as EAK owner at accepting businesses.

Acceptance Criteria: 
- [x] Generate a OTP from the anmeldecode before persisting it and verify the card.
- [x] Use the query ` fun verifyCardInProject(project: String, card: CardVerificationModel): Boolean `
- [x] Validate that anmeldecode is valid, maybe make a request to the server with a generated hash to check that it actually works
- [x] Owner name, expiry date, random string and otp secret are saved locally in the app

**Comment by RoAnBu** [comment]
> Option to provide recovery information (email address)
@PaulaWi 
I would move that to a separate user story. For the beginning it might be a bit too much here.

An additional criteria could be: Tell the user that validation was succesful or that it failed

**Comment by maxammann** [comment]
pdf generation: #166, #172

**Comment by maxammann** [comment]
I think this is quite important. We should warn users if the QR code which was imported is not valid.

**Comment by maxammann** [comment]
This is now high priority because Nuernberg wants to be use the Anmeldecode for verifying that somebody is entitled.

**Comment by michael-markl** [comment]
@maxammann Are you still working on this?
I think this would be a good starter task for @f1sh1918 or @sarahsporck

**Comment by maxammann** [comment]
It would be a shame if I would work on this since 2 months :D

**Comment by michael-markl** [comment]
Cool, @f1sh1918 and @sarahsporck : feel free to grab it if you re out of work :P

**Comment by michael-markl** [comment]
The issue description might is quite old but still largely valid. I think you can ignore the third checkbox, if you don't understand its meaning (I am having a hard time too) :D

**Comment by sarahsporck** [comment]
Well, then this ticket belongs to me now! :)

**Comment by michael-markl** [comment]
We'll most likely get many merge conflicts with #717 . I will help you in fixing them :)
