### ISSUE TITLE
Filters should remain visible when the list is scrolled

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1704]
**Describe the bug**
In the search mask for acceptance points in the app, the filters  scroll along with the list of results.

**To Reproduce**
1. Go to Search page in the app
2. Scroll the list of acceptance points
3. View filter moving out of screen

**Expected behavior**
In the search mask for acceptance points in the app,  the filters stay visible while scrolling the list.

**Comment by michael-markl** [comment]
It's not a bug. I personally think it's better that the filters do not scroll, especially for landscape mode and (and tablets).

**Comment by ztefanie** [comment]
As this aligns with our current designs, this will be closed.

**Comment by seluianova** [comment]
Duplicate https://github.com/digitalfabrik/entitlementcard/issues/1540
