### ISSUE TITLE
Cleanup qr code parsing error handling

### ISSUE THREAD

**Issue by RoAnBu** [digitalfabrik/entitlementcard#263]
While working on #261 it again became clear that the current error handling when parsing identification and verification qr codes is ugly to read and hard to maintain.

This concerns these two files:
https://github.com/ehrenamtskarte/ehrenamtskarte/blob/main/frontend/lib/identification/identification_qr_content_parser.dart
and
https://github.com/ehrenamtskarte/ehrenamtskarte/blob/main/frontend/lib/verification/scanner/verification_qr_content_parser.dart

**Comment by elKei24** [comment]
I already kind of started working on that
