### ISSUE TITLE
Don't transmit plain text passwords to the server

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#322]
Currently, when logging in, plain text passwords are sent the server. We should try to avoid this.

**Comment by maxammann** [comment]
Check here for inspiration: https://medium.com/@harwoeck/password-and-credential-management-in-2018-56f43669d588

I would classify this as low priority though. It is standard practice to do it like we do: https://security.stackexchange.com/questions/110415/is-it-ok-to-send-plain-text-password-over-https

**Comment by Schedulaar** [comment]
If we had a `very low prio` tag I'd give it that :D

**Comment by sarahsporck** [comment]
Everyone does this :)
