### ISSUE TITLE
(Placeholder) Do not send verbose errors to frontend

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#324]
Currently the backend sends the plain error objects to the frontend when an error occurs. This is not a good behavior, because it can leak internal data.
![image](https://user-images.githubusercontent.com/905221/111870258-f2133c00-8983-11eb-865d-66f1f7d4e312.png)

TODO: Add a solution.

**Comment by Schedulaar** [comment]
@maxammann I think this is not a bug in production, is it?

**Comment by maxammann** [comment]
Probably not, but I'd leave this task open until someone checked a crash like this again.

**Comment by maxammann** [comment]
I just observed this again on the current deployment

**Comment by michael-markl** [comment]
A solution to this issue should introduce a general concept of how to treat errors in the GraphQL backend (& interface)

**Comment by maxammann** [comment]
Yes absolutely! Now that we know why these messages show up in the frontend this is a technical task.

**Comment by maxammann** [comment]
Very much related to #659

**Comment by sarahsporck** [comment]
Should be resolved due to #873, as all backend exceptions have their own error message now.
