### ISSUE TITLE
Avoid vulnerable file uploads

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#329]
Currently, any files can be uploaded and are accepted by the backend.
The administration backend will download the files (with their original filenames) on an administrator's computer.
This might be a vulnerability, as `virus.pdf.exe` might get uploaded and an administrator might think it's just a legit pdf file.

**Comment by maxammann** [comment]
Very important, if we plan to use applications.

**Comment by Schedulaar** [comment]
*If we plan to support file uploads when we use applications :)

**Comment by maxammann** [comment]
high priority under the condition that we use uploads ;)

**Comment by michael-markl** [comment]
After #622 is merged, only PDFs, PNGs and JPGs with at most 5MB can be uploaded. The filename is overriden (the original filename is discarded). This improves security a bit but it might not be sufficient.

**Comment by maxammann** [comment]
As long as extensions are correct we are probably fine. Users are already downloading PNGs and PDFs from the web.

We should test this though.

**Comment by maxammann** [comment]
Alternatively we can only allow PNGs/JPGs and then reencode them.

**Comment by maxammann** [comment]
Or setup ClamAV on directory: https://wiki.ubuntuusers.de/ClamAV/

**Comment by maxammann** [comment]
We are running now clamavv and blocking file access on files which are viruses.

The follow config for running the watcher is used:
```
[Unit]
Description=ClamAV On-Access Scanning
After=clamav-daemon.service
Wants=clamav-daemon.service

[Service]
ExecStart=/usr/sbin/clamonacc --foreground --fdpass
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

https://bugs.launchpad.net/ubuntu/+source/clamav/+bug/1881761

**Comment by maxammann** [comment]
This is not saltified!
