### ISSUE TITLE
Switch from autoincrementing ids to UUIDs for applications (Security)

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#333]
Avoid using autoincrementing ids for applications. Else it is trivial to check how many applications there were. Also it is easier to guess paths to files in that case.

**Comment by maxammann** [comment]
Because the attack is not absolutely clear I classify this as low-priority.

**Comment by maxammann** [comment]
I dont know which severity this has to lets add both labels.

**Comment by michael-markl** [comment]
As discussed, we don't believe that this is a security vulnerability.
We only expose this ID to (very few) authenticated users who could make conclusions about the number of applications sent to other regions/projects (which is okay).
