### ISSUE TITLE
jsPDF does not support utf8 out of the box

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#354]
**Describe the bug**
jsPDF does not support utf8 out of the box.
Nevertheless, we should be able to render names from different countries from all over the world.
Also we'd like to have the German quotation marks for the sentence in the manual
```
1. Laden Sie sich die App "Ehrenamtskarte" herunter.
```

**To Reproduce**
1. Go to Administration, Karten drucken, Name etwa عائشة
2. Click on 'Karten drucken'
3. See errorneous PDF:

**Expected behavior**
The PDF should render the arabic name fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/7025199/116404076-93689a00-a82e-11eb-87c0-bf033750c62c.png)

**Comment by maxammann** [comment]
Solution is to add a TTF font to the PDF: https://github.com/parallax/jsPDF#use-of-unicode-characters--utf-8

This is quite a whacky solution as we never know which glyphs we will need. Sending a 200Mb TTF file to the client is  not a solution..

**Comment by maxammann** [comment]
I see a few options:
* Just use the most wildly used Glyphs: Noto Sans
  * People with Japanese/Chinese names properly have some latin translations for their names. Are there internaptional passports with for example chinese characters?
* Create PDF on Server - no option because of privacy?
* Fetch needed TTFs dynamically based on the used glyphs
  * very complicated 
  * leaks information about glyphs in the names of people

**Comment by maxammann** [comment]
Haha lets download the 2GB texlive distro into cookies :D

**Comment by Schedulaar** [comment]
haha it's actually not that much:
The live demo only uses up to 10MB to produce this PDF. 
If you remove the usages of the packages (amsmath and graphicx) it is actually quite light weight and also fast enough for production^^

http://manuels.github.io/texlive.js/#open_pdf

**Comment by maxammann** [comment]
Latex also needs to get the fonts somewhere :D So the issue is not any different with latex vs. pdfjs.

**Comment by Schedulaar** [comment]
Huh, good question how that would work then... But if it works well enough, it would be worth a try 😅  this would also improve the layout a lot (and make it easier) I guess.

**Comment by maxammann** [comment]
Download 1GB of font files :D There is no other way actually. In order to generate arbitrary PDFs with arbitrary glphys, you need to have all the glyphs available in the environment from which the PDF is generated.
