### ISSUE TITLE
Remove the slide about asking for the location

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#356]
**Is your feature request related to a problem? Please describe.**

The integreat app got rejected recently because we put text, which asks for permission before showing the permission dialog.

It is not 100% clear in my opinion whether the ehrenamtskarte app violates this. The integreat app clearly did, as we used terms like "Allow" there.

https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/accessing-user-data/#displaying-custom-messaging-before-the-alert

This is a discussion instead of a ready task.

**Comment by Schedulaar** [comment]
I'd postpone this until we have problem with it 🙈
