### ISSUE TITLE
Upgrade to flutter 2.2.0

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#372]
We should upgrade to flutter 2.20 soon. I'm currently working around issues on iOS which have been fixed already some time ago.

**Comment by Schedulaar** [comment]
I think we should already run flutter 2.0.6? At least that's what I set flutter version manager to do... 🤔 
What kind of issues are you working around?

**Comment by maxammann** [comment]
Sorry i meant 2.20.

Issues with compiling the project on a m1 e.g.
