### ISSUE TITLE
Please make the app and POIs available

### ISSUE THREAD

**Issue by IzzySoft** [digitalfabrik/entitlementcard#373]
**Is your feature request related to a problem? Please describe.**
Being a volunteer and having been awarded the Ehrenamtskarte, I'd like to use the resources – but cannot find any download source.

**Describe the solution you'd like**
* releases could be tagged and the corresponding APK attached to the release
* POIs could be made available e.g. in GPX format (I'd really like this, as I could simply add it as layer to e.g. OsmAnd). This would not only be ideal for devices with limited resources (where the owner cannot "afford" adding many apps), but also allow for use on other devices like laptops, PCs or even dedicated navigation devices.

**Describe alternatives you've considered**
Adding the app to the [F-Droid](https://f-droid.org/) catalog. The license would permit this, but this would at least require releases to be tagged. I might be able to help with the also needed [Fastlane structures](https://gitlab.com/snippets/1895688) for this.

**Additional context**
Resources one can find on the web (looking for Akzeptanzstellen) are usually not well structured and often also outdated. Going by the screenshots, your app allows easy filtering – and POIs as GPX would allow easy navigation even without the app. This would be a great help.

Thanks for considering!

**Comment by maxammann** [comment]
First of all, thank you for reaching out to us! We are a team out of students and we are looking forward to the official release in the next few weeks. This project is the open-source successor of the previous app.

> but cannot find any download source.

I would love to do this but we have to see whether we (the team of developers) are allowed to do this. The data is generally available to download for anyone as XML (given that you know the link). This could already be seen as a way to protect the data. We will reach out to the ministry and ask them whether we can release the data of the app under an open source license.

Sadly, I highly doubt it that we can release this data under an open source license. That would require all municipalities in Bavaria, to agree that their data can be used freely. But lets see what we can do here.

> Adding the app to the [F-Droid](https://f-droid.org/) catalog.

That would be awesome indeed! Right now we also do not have any dependency which classifies as non-free.

> I might be able to help with the also needed [Fastlane structures](https://gitlab.com/snippets/1895688) for this.

That is actually an open issue right now. We also need fastlane to deploy to the App Store and Play Store. As I can see in your Gist you already have some experience with it. Would be awesome to collaborate on this somehow.

**Comment by IzzySoft** [comment]
> That would require all municipalities in Bavaria, to agree that their data can be used freely.

Wasn't there some OpenData initiative announced a little while ago? Didn't the Munich meir (OB Dieter Reiter) state they want to go that path? Well, this is their chance to prove they mean it, wouldn't you agree?

* [Open-Data-Portal München](https://www.opengov-muenchen.de/)
* [Open Data der Landeshauptstadt München](https://www.muenchen.de/rathaus/Stadtverwaltung/IT-Referat/Projekt-E--und-Open-Government/eoGov-Dienste-und-Basiskomponenten/Basiskomponenten/Offene-Daten-der-LHM.html)
* **[OpenData - Bayern](https://ldbv.bayern.de/produkte/weitere/opendata.html)** (matches our request; especially check the BayernAtlas there, where this would fit in nicely)
* [Open Data Initiative der Bayerischen Staatsregierung](https://www.ldbv.bayern.de/aktuell/archiv/473.html)
* [München beschließt neue Open-Source-Strategie](https://www.behoerden-spiegel.de/2021/05/06/muenchen-beschliesst-neue-open-source-strategie/)

Maybe these links can help convincing them :smile:

> Right now we also do not have any dependency which classifies as non-free.

Provided state and communities agree – else it might mean the NonFreeAssets flag. But nothing that would stop the app from being published at F-Droid I'd say. If you want a "test drive" first (and provided the APK is not too big), there's also [my repo](https://apt.izzysoft.de/fdroid). For adding the app here, I'd have to setup Fastlane anyhow, so that would be a good match. There are hundreds of apps on F-Droid which went this path, first going online in my repo and then moving on to F-Droid.org.

Disclosure: I'm one of the maintainers at F-Droid (which also was the main argument for my blue card). And from above context and its focus you might already have guessed what city I'm located in :smile:

**Comment by maxammann** [comment]
> Wasn't there some OpenData initiative announced a little while ago? Didn't the Munich meir (OB Dieter Reiter) state they want to go that path? Well, this is their chance to prove they mean it, wouldn't you agree?

I definitely agree. I also think that some municipalities in Bavaria would agree. The only problem is that **every** municipality would have to agree. The reason for this is that the data is not collected in a centralized way, but is provided by each municipality individually. We will see what we can do to get some kind of consent to release the data, but I highly doubt it that we can release the data under a free license. So far nobody questioned the license of the data. Therefore, I expect that this will take some time to clarify. 

We are already exposing an API which delivers all "Akzeptanzstellen" of Bavaria. That way users could actually generate a GPX file.

> Provided state and communities agree – else it might mean the NonFreeAssets flag.

True, lets see what we can find out about the license of the data.

> There are hundreds of apps on F-Droid which went this path, first going online in my repo and then moving on to F-Droid.org.

Cool, what is the advantage of release there first?

> I'm one of the maintainers at F-Droid (which also was the main argument for my blue card). And from above context and its focus you might already have guessed what city I'm located in

Very cool :) It is good to hear that open-source work is being valued :)
Yes, actually you probably don't live far from where the dev team lives. The app is developed at Tür an Tür - Digitalfabrik in Augsburg: https://tuerantuer.org

**Comment by IzzySoft** [comment]
> That way users could actually generate a GPX file.

I unfortunately lack the time to explore that myself. With all the projects I'm working on it's almost a question what consumes more time: the work-for-living or the living-for-projects :see_no_evil: Should there be a script for that (so one could pull an updated version from time to time), I'd gladly accept that – even when asked to "keep it private".

> Cool, what is the advantage of release there first?

It becomes available almost the same day, has faster updates (as I don't need to build as F-Droid does; I just take your APK) – and scanner results show you if there are any show stoppers for F-Droid inclusion (the library scanner I use became part of F-Droid's scanning engine). More details in [this FAQ](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ).

> Very cool :) It is good to hear that open-source work is being valued :)

Yes, I was excited as well. They even knew F-Droid, so I had not much to explain. If I understood correctly, the time I spend on F-Droid alone would be sufficient for multiple cards :rofl: Should ask for a second one to give to my wife…

> Yes, actually you probably don't live far from where the dev team lives.

Still too far to "just walk over" (I'm in Munich)…

**Comment by maxammann** [comment]
> Still too far to "just walk over" (I'm in Munich)…

I'm actually in munich now so maybe that is actually possible :D

> It becomes available almost the same day, has faster updates

Here is the first APK: https://cloud.maxammann.org/index.php/s/MPp33MdCT2qMBW4
Can add it to the repository? After that I will see how we can automate the process :)

> I unfortunately lack the time to explore that myself.

We will see what we can do :)

**Comment by IzzySoft** [comment]
> I'm actually in munich now so maybe that is actually possible :D

I'm open to meet – in the open :smile:

> Here is the first APK … Can add it to the repository? After that I will see how we can automate the process :)

Well, my updater cannot work with such URLs, so that would mean manual maintenance. I see the APK exceeds the 30M limit – the general curse of many Flutter apps, because Flutter has to add its own huge libs and does so for multiple architectures. Would it be possible to have a "armeabi-v7a only" APK (that architecture covers 90% of existing Android devices, as most armv8 can deal with that, too)? That would probably be around 15M then and thus fit in again, so I even could keep 2 versions. And maybe you could attach that to `releases/` here (keep something like `armeabi-v7a` in the file name to make it identifyable, so my updater can pick the right one)? That would make it possible to have updates fetched automatically.

In my repo, I'd have to flag the app with 2 Anti-Features: NonFreeDep (GMS is a non-free dependency) and Tracking (Mapbox Telemetry) – for F-Droid.org GMS would be a show-stopper:

```
Offending libs:
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Mapbox SDK Telemetry component (/com/mapbox/android/telemetry): Tracking
```

Maybe you could disable the Telemetry component? And do you really need GMS?

> We will see what we can do :)

Thanks a lot! Maybe we can talk about it in person one day. You can find one of my mail addresses in any of my commits :wink:

**Comment by maxammann** [comment]
> Mapbox SDK Telemetry component 
Telemetry is disabled, we can remove this by switching to https://github.com/maplibre/ 
This will take some work though which is not feasable in the short term.

> Google Mobile Services 
This is weird but expectable. We are not depending expclitly on it but some sub dependency (likely https://pub.dev/packages/geolocator/) adds it.
As far as I can see the geolocator requires GMS as a compile time dependency. Not sure whether we can build without a reference to GMS....



> Would it be possible to have a "armeabi-v7a only" APK

should be possible, we will see whether we can decrease size in a different way though.



>  And maybe you could attach that to `releases/` here

We will do this in the future, yes :)

**Comment by IzzySoft** [comment]
> Telemetry is disabled, we can remove this by switching to @maplibre

That would be great! Just let me know when done so I update metadata here.

> This is weird but expectable. We are not depending expclitly on it but some sub dependency (likely pub.dev/packages/geolocator) adds it.

Bingo. And [here is how to avoid that](https://gitlab.com/-/snippets/1896503#note_575517348) (simply replace Geolocator by its libre fork, pretty much a drop-in replacement).

And thanks for placing the APK in `releases/` in the future! Please let me know when that was done, so I can enable auto-updates.

As you might have guessed reading between the lines, I've made an exception with the 30M limit (you're working on that anyway and chances are good to get below that; further the *technical* issues only kick in when reaching 32M). With the next sync in about 6 hours from now, your app [becomes available here](https://apt.izzysoft.de/fdroid/index/apk/de.nrw.it.giz.ehrensache.bayern.android) – so be welcome linking to that URL and, if you like, [using this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for that. Matches the look of similar badges, e.g. that for Google Play you certainly will want to add as I saw your app already being available there :smiley:

**Comment by maxammann** [comment]
> Bingo. And here is how to avoid that (simply replace Geolocator by its libre fork, pretty much a drop-in replacement).

Cool! Sadly, we still should provide a way to create builds with Google Services. The location API of it is much faster as it uses additional information like wifis and cellular networks (also possible with microg).

So we need to build it conditionally. That is afaik not supported. Maybe we just use `sed` to string replace before compilation in a CI.

**Comment by maxammann** [comment]
I think we will replace the current signing key soon when we switch to app bundles. Do you know whether that is fine for your fdroid repository?

**Comment by IzzySoft** [comment]
> So we need to build it conditionally. That is afaik not supported.

Flutter supports build flavors. So you could have a flavor `foss` with the libre replacement, and another `google` flavor for that walled-garden variant. And as you speak of microG: I recently saw an app that had some microG libs inside, so maybe you can get that "fossed", too.

> I think we will replace the current signing key soon when we switch to app bundles. Do you know whether that is fine for your fdroid repository?

Ouch. That's not fine for the end-users as it will make updating from an APK signed with the previous key to one with the new key impossible – unless you sign with both keys for a while until everyone has updated. Same for Google Play. Otherwise Android refuses to update, and users will have to uninstall and reinstall in order to get to the new version.

If you really need to switch keys (as you're already in Play, you're not forced to but can still stick with APKs, right? I wouldn't hand out a private key to any 3rd party, it's called "private" for a reason. You never know what Google might add to your APKs when it can – and users might blame you for it as it's signed by you), make sure to have an export/import feature available so users can migrate.

**Comment by maxammann** [comment]
> You never know what Google might add to your APKs when it can

I assure you that we value security a lot. For the Google Play delivery I think that the benefits like app bundles and simplified deployment are worth it. In fact on a mobile which uses Google Services Google already controls the OS. Users already lost here :D

For your Fdroid repository I would like to generate a separate key and sign the apk again. I will upload a new signed version tomorrow to the releases section. For the main fdroid repo the key of fdroid is used.

As we did not yet advertise your repository I think there will not be a lot of users who have to reinstall.

**Comment by maxammann** [comment]
> Flutter supports build flavors

I suspect that it is possible to use flavors. I will try to depend on both geolocators and then configure the gradle build system to exclude a specific geolocator in the Android build.
In dart we can use conditional import to import either of the geolocators.

I think this should work. At least it would in React Native.

**Comment by IzzySoft** [comment]
> In fact on a mobile which uses Google Services Google already controls the OS. Users already lost here :D

That's a way to put it – and I cannot even blame you as, at least to a degree, it's too true… :cry:

> As we did not yet advertise your repository I think there will not be a lot of users who have to reinstall.

Ahem… I did advertise it already [at Mastodon](https://mastodon.technology/@IzzyOnDroid/106908643192902711). Considering you finally target F-Droid.org anyway, the listing in my repo would be temporary (apps are usually removed from my repo once they've reached F-Droid, given an overlap of about 10 days). So maybe we could check if the 2 replacements would make it meeting F-Droid's inclusion criteria and, it it's "that easy", just stay with the "old key" for my repo for the few remaining weeks? The issue disappears then by itself, as you've pointed out:

> For the main fdroid repo the key of fdroid is used.

"The" key being unique for your app again, btw. F-Droid generates a new key for each new app, so each app uses its own signing key.

> I think this should work.

If you want me to check the resulting APKs with my library scanner to confirm, just "ring ma bell" :wink:

**Comment by maxammann** [comment]
Its happening :) https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10382

**Comment by maxammann** [comment]
Its now released on F-Droid. Right now we do not plan to make the data downloadable. But feel free to use the following API:

https://api.ehrenamtskarte.app/graphiql/

**Comment by IzzySoft** [comment]
Thanks! Took me a little to figure out how it works, but finally I'm getting results. Managed to set up a query returning all physical stores with address, description and coordinates – and should be able to turn that into a GPX if I find time to script it. Just didn't manage to filter by region (no regionId as query parameter, nor in store or address or coordinates – neither a searchByRegion), so it will be a huge GPX I guess (3.8 MB JSON) :smile:

Is there a way to retrieve the results directly as JSON (e.g. using `curl`)? If not, guess I'm fine copy/pasting that from time to time.

**Comment by Schedulaar** [comment]
Currently, we cannot (reliably) assign an accepting store to a specific region. If it helps: You can query by coordinates (using the searchAcceptingStores query) to query accepting stores sorted by distance to the coordinates.

In the future we might get a regionId for all accepting stores. Then it might be possible to query stores by region.
But this will probably take at least a few months I guess :)

**Comment by maxammann** [comment]
The data should be quite easily transformable to a GeoJSON using `jq`. After that it the GeoJSON can be converted to a GPX:
`ogr2ogr -f GeoJSON coords.json -dsco GPX_USE_EXTENSIONS=YES out.gpx`.

Here is a curl query copied from firefox devtools:

```bash
curl 'https://api.ehrenamtskarte.app/' -X POST -H 'Content-Type: application/json'  --data-raw '{"query":"{\n  physicalStores {\n    store {\n      name\n    },\n    coordinates {\n      lat,\n      lng\n    }\n  }\n}","variables":null}'
```
