### ISSUE TITLE
Add feedback when clicking on an already selected Akzeptanzstelle

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#381]
As a user I want to get some feedback when I click on an already selected location on the map.

Acceptance Criteria:
 - [ ] When clicking on an already selected Akzeptenztelle, then it should get deselected

**Comment by maxammann** [comment]
Discussion: https://github.com/ehrenamtskarte/ehrenamtskarte/pull/379/files#r706602682

**Comment by maxammann** [comment]
I don't know whether this is what I would expect. I'd say we leave it as it is. @Schedulaar any objections?

**Comment by Schedulaar** [comment]
It would be nice to have some splash effect on click, but I guess that's technically not really possible. We can close this issue if you want.
