### ISSUE TITLE
Unable to switch between Akzeptanzstellen on map if they are close

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#382]
**Describe the bug**
Selecting Akzeptanzparner works nicely after the latest changes. The only issue is when multiple Locations are very close and we try to switch between them. Then it does no longer works. Maybe the Symbol layer is blocking clicks.

**To Reproduce**
1. Go to Gräfelfing
2. Try to click swtich between the Locations in Bahnhofstrasse

**Smartphone (please complete the following information):**
 - iPhone 5 and iPad 2016

**Comment by maxammann** [comment]
Low priority because it is possible to zoom in and then select the other icon.

**Comment by Schedulaar** [comment]
I cannot really reproduce this on Android. Was this iOS only?

**Comment by maxammann** [comment]
I'm quite sure this was iOS only, but I'll try to reproduce again

**Comment by klinzo** [comment]
At least on iOS simulator still reproducible, couldn't reproduce it on android.

**Comment by maxammann** [comment]
Thank you for reproducing!
