### ISSUE TITLE
Use NürnbergPassNumber in Digitale Druckerei (administration frontend)

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#384]
As a user I want to identify my card uniquely. The people who create cards should assign me an ID. ~~A way to automatically generate globally unique IDs could be useful.~~ The id  should be entered in the digitale druckerei.

Pass number is provided by nürnberg.

Acceptance Criteria:
 - [x] Should contain exactly 8 (numeric) digits (nürnberg) and should not start with 0.
 - [x] An ID Should be unique (at least in the nürnberg project) (we don't need to enforce this)
 - [x] Is only set for the nürnberg project
 - [ ] No need to add this to the canonical data format.

**Comment by michael-markl** [comment]
It's still somewhat unclear, for what the Id will be used and where it should come from and how it should look like. Need to discuss with customer.

**Comment by michael-markl** [comment]
It's now clarified. (I adjusted the description).

**Comment by maxammann** [comment]
related to #698
