### ISSUE TITLE
No addional information in Akzeptanzstellen list

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#390]
**Describe the bug**

**To Reproduce**
1. Go to 'Suche'
2. See the Suchresultate

**Expected behavior**
The description should be shown in each line

**Screenshots**
![image](https://user-images.githubusercontent.com/905221/137978001-32b0b36e-bbe0-4717-b2d2-c222adedfd45.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 5s (iphone a1457)
 - iOS 12....

**Comment by klinzo** [comment]
@maxammann I think you were just unlucky that the three results don't have a description. It's the same on my device. Should I add a placeholder text like `Keine Beschreibung verfügbar`?
