### ISSUE TITLE
Create a landing page on ehrenamtskarte.app

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#418]
**Is your feature request related to a problem? Please describe.**
There should be something visible on ehrenamtskarte.app. The most simple configuration would be to redirect to our github project.

**Comment by f1sh1918** [comment]
do we still need this ticket. we have a landing page on https://berechtigungskarte.app/ @maxammann
@dkehne i think we should refer from this page to github

**Comment by michael-markl** [comment]
sozialpass.app
