### ISSUE TITLE
Rethink the navigation

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#420]
**Is your feature request related to a problem? Please describe.**
There are two major ways to implement navigation: iOS Way and Android Way

**iOS**:
Each tab has a separate navigation context. This means the navigation within Tab 1. does not influence navigation in Tab 2.
This is maybe sub-optimal for our app because it leads to https://github.com/ehrenamtskarte/ehrenamtskarte/issues/173

**Android**:
There is a single navigation context in the root. This is for example how the CWA is handling navigation.
This means that when you open a new route and push it onto the root navigator it is shown above the bottom navigation bar.

I think of favor the **Android** way because it is simpler to implement and avoid the bug #173. From a user experience point of view I would be fine with both.

**Comment by Schedulaar** [comment]
We could also (with a major refactoring) use the Google Maps way and unify tabs "Map and Search" into one.

**Comment by maxammann** [comment]
Do you want to remove the bottom navigation bar completely? If not then we still need a concept for the third tab.

**Comment by Schedulaar** [comment]
So, basically without a huge refactor I'm also fine with both versions :)

**Comment by klinzo** [comment]
I think #173 does not occur anymore.

Not sure what material design says (and I did not research how other apps behave here) but for me the current behavior is not really intuitive:
Hitting back button if another tab is selected (like Suche or Über) closes the app. I would expect to always go back to `Karte` and only closing if already in that tab. Probably that is the default though.

**Comment by maxammann** [comment]
I never used the back button on android when there was a tabbed view, but some apps at least bring you back to the very first tab. That is reasonable in my opinion and could be added.  This is something we can do for both approaches I mentioned above.

#173 is currently circumvented. Currently implemented is a mix of Andoidish and iOSish navigation. This is not very ideal, but actually avoid the #173 right now.

**Comment by maxammann** [comment]
This should be changed/decided soonish

**Comment by michael-markl** [comment]
Is this really high prio?

**Comment by maxammann** [comment]
It was, no longer is 😃

**Comment by sarahsporck** [comment]
We discussed this and decided it makes sense to push routes to the root navigation stack in the search and map tabs. Will be done in another clean ticket.
