### ISSUE TITLE
Delete older builds in the backend

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#426]
**Describe the bug**
We send finished .deb files to our production server for installation. After uploading new ones, older ones should be deleted.

**Comment by Schedulaar** [comment]
Is it not possible to delete them straight after installation?

**Comment by maxammann** [comment]
> Is it not possible to delete them straight after installation?

Yes, I think that is what we should do. We could add it to the weekly cron job which installs the debs.

**Comment by maxammann** [comment]
Done via bash magic:

`find /srv/local-apt-repository -type f -printf "%T+ %p\n" | sort -r | tail -n +25 | awk '{print $2}' | xargs rm -f
`
