### ISSUE TITLE
Enable use_build_context_synchronously linting rule

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/entitlementcard#435]
**Is your feature request related to a problem? Please describe.**
The rule [use_build_context_synchronously](https://dart-lang.github.io/linter/lints/use_build_context_synchronously.html) seems quite important and may prevent bugs.

**Describe the solution you'd like**
Enable the rule, set its severity to `error` and fix all occurrences.

**Comment by maxammann** [comment]
Looks promising, right now this is experimental lint though. So I would wait.

**Comment by f1sh1918** [comment]
still experimental
