### ISSUE TITLE
Exclude graphql and protobuf files from formatting

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/entitlementcard#437]
**Is your feature request related to a problem? Please describe.**
The files lib/graphql/graphql_api*.dart and lib/identification/protobuf/*.dart are autogenerated and should not be formatted.

**Describe the solution you'd like**
* Revert the changes to those files done in https://github.com/digitalfabrik/ehrenamtskarte/commit/f44993429b934e2cf9dc67ed829e15069d2eeb57 and https://github.com/digitalfabrik/ehrenamtskarte/commit/434de1458f4d1ba79b89cef5757355df151dff35
* Exclude those files from auto formatting in the pre-commit hook

**Comment by maxammann** [comment]
Excluding specific files does not work: https://github.com/dart-lang/dart_style/issues/864

Instead we should gitignore the generated code.

**Comment by maxammann** [comment]
The code is already gitignored.
