### ISSUE TITLE
Set map camera by searching for locations

### ISSUE THREAD

**Issue by elKei24** [digitalfabrik/entitlementcard#44]
As a EAK owner, I want to be able to easily get an overview over the accepting businesses in a specific area without having to manually scroll the map there.

Acceptence criteria:
* [ ] user can move map by entering zip code
* [ ] user can move map by entering city names
* [ ] user cam move map by entering accepting business name

Optional:
* [ ] user can move map by entering names of other POIs

**Comment by maxammann** [comment]
Low priority because we were not asked by anyone to implement something like this. 
This would make the app more usable though.

**Comment by Schedulaar** [comment]
I think there was one review on some App/GPlay Store that asked for this (and the legacy supported something similar).
