### ISSUE TITLE
Filter stores outside of state

### ISSUE THREAD

**Issue by klinzo** [digitalfabrik/entitlementcard#447]
**Is your feature request related to a problem? Please describe.**
We should decide whether we want to have stores outside the boundaries of the current state (bavaria for now) or whether we want to filter them out.

**Possibilities**
* Filter out all stores not inside the state using
  * the state bounding box (relatively inaccurate, bbox is a rect)
  * using the `state` address property of the postal code feature
* Filter out all stores not inside the state using the state bounding box plus a threshold (e.g. 100km)
* Don't filter at all

See discussion https://github.com/digitalfabrik/ehrenamtskarte/pull/439#discussion_r779918096

**Comment by maxammann** [comment]
I think we should filter on the map, because we only have map data for Germany right now.

In the search we should not filter. Ofc this would raise new questions like: `What happens if a user jumps to the Akzeptanzstelle on the map?`

**Comment by Schedulaar** [comment]
Personally, I'd rather not filter at all and simply expand the map tiles we serve to europe.
Filtering on the "tiles" level to make stores outside Bavaria disappear on the map seems to involve too many edge cases imo...

**Comment by klinzo** [comment]
I'd either filter on the map and in the search or not at all as well. Everything else is way too difficult for way too few stores and needs too many modifications/edge cases.

**Comment by maxammann** [comment]
Works for me

related #462

**Comment by maxammann** [comment]
So I think we can close this with https://github.com/digitalfabrik/ehrenamtskarte/issues/462

**Comment by maxammann** [comment]
Europe is now available as tiles.

**Comment by maxammann** [comment]
Yes can be removed
