### ISSUE TITLE
Migrate from martin to t-rex

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#458]
**Is your feature request related to a problem? Please describe.**
Our current tile server martin seems unmaintained since some time.

**Describe the solution you'd like**
There is t-rex which is actively maintained: https://t-rex.tileserver.ch/

**Describe alternatives you've considered**
None

**Comment by michael-markl** [comment]
As far as I understand, we won't migrate, as Martin seems to be maintained again. ?

**Comment by maxammann** [comment]
Yes, lets put this on hold at least :) t-rex has still some quality-of-life benefits.


onhold = closed until its opened again
