### ISSUE TITLE
Add a way to disable geocoding when importing

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#463]
**Is your feature request related to a problem? Please describe.**
Right now the import will always fail if no geocoding service is defined or it is down.

**Describe the solution you'd like**
Geocoding should be disable in both cases:

- ~geocoding server is down~
- geocoding server is not configured

In the former case a warning should be shown.

**Comment by Schedulaar** [comment]
On production, I think the importer should simply fail if the geocoding server is down and the server should continue to work with the "old" data (from the last import run)

**Comment by maxammann** [comment]
You are right, probably only if the latter case is interresting

**Comment by klinzo** [comment]
I think this should be configured in the build config during our whitelabeling process. We also probably need more configuration options than just disabling/enabling geocoding: Data source, mapping, enabling/disabling specific steps, database configuration to be able to retrieve the right data matching the current build config.

**Comment by maxammann** [comment]
Yes that makes sense. We should also think about runtime vs compile time flags. The build config contains compile time flags and runtime flags in integreat.

Maybe it could make sense to split this up. Independent of the used build config it should be possible to run an import without geocoding if the nominatim server is offline.

Another thing to keep in mind: the backend propably wont have a build config, but just a normal configuration. Settings in this config should be overridable by a command line argument.

**Comment by maxammann** [comment]
Closed because it is disablable and failures in the geocoding lead to failed imports.
