### ISSUE TITLE
Sanitize street and house number

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/entitlementcard#467]
**Is your feature request related to a problem? Please describe.**
Some stores have streets which include house numbers. There are also some stores that have house numbers that include streets or locations.

**Describe the solution you'd like**
Remove digits from street and location and letters from house numbers.

**Comment by klinzo** [comment]
> Not sure if I understand your solution correctly. I think if e.g. `Musterstraße 31` is the value of the `street` field, we might simply transfer the housenumber over to the final address, right? Maybe adding some examples to the problem and solution description might help here.

Maybe I should not yet have created an issue for this. I am still looking into it. Will update once I have more info.

**Comment by klinzo** [comment]
Another thing that this MIGHT be important for (did not look into it yet): we have lots of duplicates in our data, i.e. multiple stores in the data for the same actual stores. If we have sanitized sanitized addresses, it might be easier to decide which duplicates are redundant.
