### ISSUE TITLE
Collapse subsequent whitespace in name field

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#469]
**Is your feature request related to a problem? Please describe.**
Some names have subsequent whitespace.
An example can be seen here for the accepting store "Möbel Keser" whose registered name is
```
MÖBEL KESER -                     Küche + Wohnen
```
https://api.ehrenamtskarte.app/graphiql/?query=query%20%7B%0A%20%20searchAcceptingStores(params%3A%20%7BsearchText%3A%20%22M%C3%B6bel%20Keser%22%7D)%20%7B%0A%20%20%20%20name%0A%20%20%7D%0A%7D

This leads to glitchy looking app behavior:

![image](https://user-images.githubusercontent.com/7025199/150660774-da617409-8163-430f-896a-8aaaab2fcffe.png)

**Describe the solution you'd like**
I think we should be able to collapse any subsequent whitespace into a single one in the name field (and possibly also in many other fields).

**Additional context**
@klinzo Maybe you already have done that in which case we can close this issue again.

**Comment by klinzo** [comment]
@Schedulaar not yet done, but would look into it
