### ISSUE TITLE
Title of Akzeptenzstellen gets scrambled 

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#471]
**Describe the bug**
Umlaute are not shown correctly. Firefox shows it correctly in the initial XML.

**To Reproduce**
Open Zweck Gardinen ...

**Screenshots**

![image](https://user-images.githubusercontent.com/905221/150754407-cc357231-2de5-4730-bdf2-f23fbd8006dd.png)
![image](https://user-images.githubusercontent.com/905221/150754448-394c6378-2915-450e-b000-db4bf5c2a1c8.png)

**Desktop (please complete the following information):**
 - OS: [Android

**Comment by klinzo** [comment]
The store is present twice in the data

**Comment by maxammann** [comment]
Hm alright, do its at least not our fault. Then the question is whether we can fix something like that.

Another questions which arises from this is whether we should add a sanitation step which filters dupplicates. This could be done quite easily by comparing long/lats after initial sanitation.

**Comment by klinzo** [comment]
> Another questions which arises from this is whether we should add a sanitation step which filters dupplicates. This could be done quite easily by comparing long/lats after initial sanitation.

Yes, that is the last sanitation topic on my todo for now. Not sure if comparing long/lats is sufficient though, e.g. in malls the coordinates of different stores may match.

**Comment by maxammann** [comment]
It seems like this issue can be solved by the IT department. See email.

**Comment by klinzo** [comment]
Seems like we still have some issues:
Umlaute are still not handled correctly sometimes, e.g. `NÃ¤hArt !` or `KlosterschÃ¤nke Kloster Banz`, `100,00 Euro ErmÃ¤ÃŸigung auf das Startpaket`.

I think this is relatively critical, perhaps we should not do an import on Thursday? @maxammann There are over 500 occurrences of this only for `ä`

**Comment by maxammann** [comment]
Issue has been escalated :)

**Comment by maxammann** [comment]
Closing because its no longer our business :)
