### ISSUE TITLE
Show additional address information in frontend

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/entitlementcard#479]
**Is your feature request related to a problem? Please describe.**
In #468 we removed additional address information like `im Hauptbahnhof`, `Ecke xyz`, `2.OG` from the street/house number properties and therefore from the `street` property saved in the DB. Therefore this piece of information is not shown to users anymore.  

**Describe the solution you'd like**
Store the property `additionalAddressInformation` separately in the DB and show it to users.

**Comment by maxammann** [comment]
low priority: I think this is a nice feature, but definitely not required. The initial goal way to only display addresses and not additional (helping) information.

**Comment by Schedulaar** [comment]
I guess it's a very small change to the frontend (simply append it to the address with a space) and as it is given in the data source, I'd vote for addressing this issue quickly and not pushing it too far into the future.

**Comment by maxammann** [comment]
Yes, its a small issue, but other issues are also small and have a higher priority imo

**Comment by sarahsporck** [comment]
It seems we already show the additional address information in our app, as we import the [app-daten.xml](https://www.lbe.bayern.de/engagement-anerkennen/ehrenamtskarte/akzeptanzstellen/app-daten.xml) as it is. And if there are additional information, they are injected into the `<hausnummer> field. Check out this entry in the app:
```
<anbieter>
<name>Turm der Sinne</name>
<strasse>Kappengasse / Ecke</strasse>
<hausnummer>Westtor</hausnummer>
<>...</>
</anbieter>
```

**Comment by michael-markl** [comment]
@steffenkleinle stated in the issue description that we remove the additional information based on our sanitizing steps from the street / hausnummer field and move them into a separate field called `additionalAddressInformation` (see [here](https://github.com/digitalfabrik/entitlementcard/blob/f2d59cf42184291658c4817d301ee7b4bbd3ff6b/backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/common/steps/SanitizeAddress.kt#L75..L86)) . We do not store this field into the DB yet.

It might be still relevant to check if this `additionalAddressInformation` field is ever populated. Maybe you can check this @sarahsporck ?

**Comment by sarahsporck** [comment]
No it is never populated. I've already tried implementing this, when i realized that we don't actually need it. Orginally we parsed the address from a string, but now we parse it directly from the fields in the html and don't change/sanitize anything anymore. Therefore, I suppose this issue becomes obsolete.

**Comment by steffenkleinle** [comment]
Just double checked and seems like additional address parts (like a,b,c) are indeed shown in the app. Maybe we should then clean up the sanitize step though and remove stuff that is not needed/executed anymore?
