### ISSUE TITLE
Check and validate password policies

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#482]
Do we have a password policy? Is it good?

**Comment by Schedulaar** [comment]
Afaik our current password policies are:
* Every user has to to have a password
* He/she cannot choose a password
* He/she cannot change a password
* The password can be any string
* 2FA is not a thing

So there's a lot to improve :)

**Comment by maxammann** [comment]
Im not a fan of over restrictive policies, but lets just forbid empty string at least. :D

**Comment by maxammann** [comment]
> mindestens 12 Zeichen, dabei muss mindestens ein Kleinbuchstabe, mindestens ein Großbuchstabe und mindestens ein Sonderzeichen verwendet werden
