### ISSUE TITLE
Add 2FA (two step verification)

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#489]
As a user I want to be able to use 2FA.

Acceptance Criteria:
 - [ ] It should be possible to use appls like Google Authentificatior

Note: this task is low prio because the majority of uses do not use 2FA yet and if they use it they only use it where they have to.
I would make this this task only high-prio if we force 2FA.

**Comment by sarahsporck** [comment]
maybe we should start with 2fa via email. Check back with the cms team, as they already use 2FA.

**Comment by sarahsporck** [comment]
This is a duplicate of #1217 therefore I'll close this issue.
