### ISSUE TITLE
Possibility to zoom in until nothing is shown anymore

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/entitlementcard#498]
**Describe the bug**
It is possible to zoom in until icons and buildings on the map vanish. Streets are still visible. This should probably not be possible.

**To Reproduce**
1. Open the map
2. Zoom in as far as possible
3. Buildings and icons are not visible anymore on the map

**Expected behavior**
There is a max zoom level where everything is still visible.

**Screenshots**
https://user-images.githubusercontent.com/29095487/155735404-90f63fdc-449e-4856-9c6a-c17e5df2433f.mp4

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi Mix 2
 - OS: Android 11
 - Version 2.1.1

**Additional context**
According to the [mapbox documentation](https://docs.mapbox.com/help/glossary/zoom-level/) there are 23 zoom levels (0 to 22). We set the maxZoom level of the store icons to 24 though: https://github.com/digitalfabrik/ehrenamtskarte-maplibre-style/blob/e6bf0c9de22a415b9d3ada35298ac15c7d7b4dff/style.json#L1602

**Comment by maxammann** [comment]
Fixed in #568
