### ISSUE TITLE
Avoid caching graphql responses

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#501]
**Describe the bug**
Right now the IDs of Akzeptanzstellen change after every import. While the app is running the GraphQL cache is caching responses.
The cache in the map view is more aggressive. Every time the user moves the viewport tiles are refreshed.

**To Reproduce**
1. Open the app
2. Trigger an import on the server
3. Click on results in the search tab
4. You see an error

**Expected behavior**
No error should happen and akzteptanzstellen should keep their original ID if possible. Maybe we should refresh if an ID is not found?

**Comment by Schedulaar** [comment]
Maybe we should start working on a "diff" approach (where we only apply the changes to the DB) rather than completely deleting and readding every accepting store.
It's really annoying that the stores don't come with an id...

**Comment by maxammann** [comment]
Yes, but this is also very difficult and out of scope for now. The simpler fix would be to reload the list of stores every time the user opens/suspends the app.

**Comment by Schedulaar** [comment]
Ah, does graphql also cache on permanent storage?
Maybe even a simple solution like http cache header with expiration every thursday (or whenever our pipeline does the data import) would suffice? That probably depends on whether the client respect these cache headers...

**Comment by maxammann** [comment]
Its an in-memory cache buts its still relevant. If you open the app on wednesday and then put it to sleep, you will get errors on thursday.
