### ISSUE TITLE
Backend Whitelabeling

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#502]
As a developer I want to be able to attach to each request a project reference such that it is possible to create multiple frontend apps which can act independent of each other

## Acceptance Criteria:
 - [x] A single GraphQL API is available at api.entitlementcard.de
 - [x] We are backwards compatible to already deployed apps (Ehrenamtskarte Bayern)
 - [x] We have a general backend configuration
 - [x] We have a per-project configuration
 - [x] The tile server is able to serve multiple data sets
 - [x] The import process is able to run per project

## Technical Tasks:
 - [x] #505
 - [x] #506
 - [x] #508 
 - [x] #509
 - [x] #510 
 - [x] #507
 - [x] #519

**Comment by michael-markl** [comment]
@maxammann Can we close this?
