### ISSUE TITLE
Visualize a birthday on the card in frontend

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#525]
**Is your feature request related to a problem? Please describe.**
Similar to #384  we also need to add a birthdate to the card.

**Describe the solution you'd like**

TODO. It is unclear how we handle differences between requirements for cards between bavaria and nürnberg.
The card ID can be useful for every project I think. The birthdate propably not.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by maxammann** [comment]
Nuernberg requires a birthdate. Implement through a birthday extension in protobuf.

**Comment by maxammann** [comment]
This is already done, execpt for the serialization to a stable & hashable data blob.

**Comment by michael-markl** [comment]
Are you working on this @maxammann ? Otherwise please unassign yourself :)

**Comment by michael-markl** [comment]
Ah, is this issue about adding the birthday in the administration frontend, or visualizing it in the flutter frontend? If it's the latter, then this issue should also include adding the NürnbergPassNumber to the flutter frontend.

**Comment by f1sh1918** [comment]
@michael-markl i think this task is about adding birthday and cardId for nuernberg on the card in flutter frontend
