### ISSUE TITLE
Set up continuous deployment for production

### ISSUE THREAD

**Issue by elKei24** [digitalfabrik/entitlementcard#53]
As a developer, I want to have changes to the source code automatically be deployed, so that I do not have this by hand on and on.

As we are not in production mode yet and everything on main should have been reviewed, we can safely do so without a separate staging environment for now.

Accepting criteria:
* [x] all the backend services are automatically updated to match the code that currently is on main
* [ ] both app versions are build in production mode, signed, and can be downloaded (at least as a build artifact)

Even if we do not publish the app yet, we should also try to deploy it automatically already.

Optional:
* [ ] updated android app is pushed to the play store 
* [ ] updated iOS app is pushed to the app store
* [x] web version of the app is deployed

**Comment by maxammann** [comment]
Recap what is missing:

* Signing Android in CI (floss and playstore)
* Creating a signed IPA for iOS
* Uploading to Google Play
* Uploading to Apple

**Comment by Schedulaar** [comment]
Maybe "automatic release notes handling" is missing as well?

**Comment by maxammann** [comment]
low priority right now because releasing is not a demanding process for me right now.

**Comment by Schedulaar** [comment]
May become more relevant once we have whitelabeled apps.

**Comment by ztefanie** [comment]
Moved all open tasks to https://github.com/digitalfabrik/entitlementcard/issues/1158
