### ISSUE TITLE
Add a back end auth log

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/entitlementcard#535]
## Motivation

To mitigate brute force attacks, IPs with multiple login attempts should be blocked. A common tool to implement this is fail2ban. fail2ban parses an auth log and blocks mentioned IP addresses with iptables or netfilter. Additionally, an auth log creates an audit trail that can be used in case of problems.

The back end should write all failed an successful login attempts to a syslog facility. The logged message should contain the username and source IP address.

Alternatively, the application can implement its own brute force mitigation.

## TODO

On each failed login, log the IP address + username with a log level INFO.
If there is no logging library then add it.

`8.8.8.8 sven.seeberg failed to login.`

**Make sure what you log the IP address of the corresponding client/browser and not from 127.0.0.1 if a reverse proxy is used: https://gist.github.com/rponte/f1946007003f46a30b98**

**Comment by maxammann** [comment]
I think this is a high-severity issue! Thanks for bringing it up!
