### ISSUE TITLE
Backend: Enable a (minimal) linter auto autoformatter

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#539]
**Is your feature request related to a problem? Please describe.**
The backend currently does not enforce to have optimized imports or a uniform formatter.

**Describe the solution you'd like**
A minimal solution which follows the Kotlin community defaults.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by michael-markl** [comment]
Closed by #575
