### ISSUE TITLE
Send the project ID with each request

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/entitlementcard#542]
**Is your feature request related to a problem? Please describe.**
Each app belongs to a single project. The currently used graphql backend endpoints do not resemble that situation, were deprecated in #508 and only work for bayern.ehrenamtskarte.app.

**Describe the solution you'd like**
The project id will be available in dart using the build config made available in #513. The currently used deprecated graphql endpoints are replace with project specific ones by sending that project id as param in the request.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by michael-markl** [comment]
Closed by #556
