### ISSUE TITLE
Use updated GraphQL API with added projectId in frontend

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#555]
**Is your feature request related to a problem? Please describe.**
Since #508, the backend API requires a projectId in each request made by the frontend.
Hence, the GraphQL requests in the frontend need to be updated and the code needs to be regenerated.
For now, we use the hardcoded projectId "bayern.ehrenamtskarte.app".

**Additional context**
This is a subtask of #516

**Comment by maxammann** [comment]
I think this is a duplicate of: https://github.com/digitalfabrik/entitlementcard/issues/542

**Comment by michael-markl** [comment]
Closed by #556
