### ISSUE TITLE
Setup SMTP in backend

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#583]
To send password reset emails, we need to have some SMTP client setup in the backend.

We need separate SMTP configs for each project (to have project-specific email addresses).
We ordered an SMTP server from hetzner for Nürnberg and Bayern. Logins are in our PW manager.

- [ ] Add a config entry for one SMTP server per project.
- [ ] Setup keine-antwort@sozialpass.app in backend
- [ ] Setup keine-antwort@ehrenamtskarte.app in backend
- [ ] Send @maxammann the config you used for testing the email

SimpleJavaMail is a promising first try: https://www.simplejavamail.org/configuration.html#section-transport-strategy-tls

If authentication does not work on the second try using SMTP + TLS then contact @maxammann (we will create a SMTP relay server in that case).

**Comment by maxammann** [comment]
This is ready. The SMTP for sozialpass.app is in the PW manager. We use this one for bavaria and nürnberg for now.
