### ISSUE TITLE
[Application] Show all applications, regardless of state

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#586]
As a civil servant in a Kommune I would liek to see all applications regardless of state.
The states are:
- waiting for verification from oranisations
- ~waiting for verification from Kommune~
- accepted
- rejected
- withdrawn
- deleted (not a state)

Note that an application stay in the state `waiting for verification from Kommune` if multiple organisations are involved and need to approve.

For each of the states (except delted) we want to list the corresponding applications. For each state there should be a seciton. The most important state is "waiting for verification from Kommune" as this requires direct input from the Kommune.

## Acceptance Criteria:
 - [ ] 4 categories should be visible in the Applications tab of the administration tool
 - [x] deleted applications are non-existant and should not be shown.
 - [ ] ~For now, do not create buttons which move the applications between states.~

**Comment by maxammann** [comment]
@michael-markl I added text here, open for discussion. Low-prio as it is not required for launch.

**Comment by f1sh1918** [comment]
@maxammann should this be moved to after launch?

I think in addition to show all state which could be marked with a `Badge` or sth we could add a filter like `show only verified`

**Comment by f1sh1918** [comment]
i created a new task where i updated the acceptance criteria, so this will be closed
https://github.com/digitalfabrik/entitlementcard/issues/1216
