### ISSUE TITLE
Update "Data safety" in Google Play Console for Nuernberg and Bayern

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#599]
**Is your feature request related to a problem? Please describe.**
We need to update the "Data safety" form in Google Play Console as soon as we update our apps.

Right now we do not share or collect any data from the users: https://support.google.com/googleplay/android-developer/answer/10787469?hl=en#types&zippy=%2Cdata-types

As soon as we publish the "whitelabel" update we will collect personal data through:

* Applicaitons (Name, Address etc through the WebView)
* User IDs with the cards.

**Comment by michael-markl** [comment]
I guess this is no longer blocked? @maxammann

**Comment by maxammann** [comment]
For Bayern this is blocked until we update the app. Until that we can not update the form.

For Nürnberg I filled it out today. But we should look over it again.

**Comment by maxammann** [comment]
Both apps have the same data safety. Closing.
