### ISSUE TITLE
Birthday Surprise

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#603]
As a user I want to be positively surprised by the app, if I open it.

## Acceptance Criteria:
 - [ ] Be happy
 
 ## Technical Tasks:
 - [ ] Don't worry

**Comment by maxammann** [comment]
I can still close and reopen!

**Comment by steffenkleinle** [comment]
I don't have birthday but it is still a really nice suprise, thank you guys 😊 I am definitely happy and don't worry :)

**Comment by michael-markl** [comment]
We need virtual balloons for when it's the user's birthday (as taken from their sozialpass). however, we should definitely also include an Easter egg on Steffen's birthday 🎂🎉🥳
