### ISSUE TITLE
[Applications] Add an option to "withdraw" applications for users

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#604]
As a user I want to be able to withdraw applicaitons. That will make the application enter the "withdrawn" state.

After succesfully submitting the application form, add sth like "Für Rückfragen zum Vorgang notieren Sie sich bitte folgende Bearbeitungs-ID [REGIONID]-XXXX".

## Acceptance Criteria:
 - [ ] Advertise the feature to users as "Delete"/"Löschen"
 - [ ] Admins in the backend can see withdrawn application

## Technical Tasks:
 - [ ] TODO

**Comment by maxammann** [comment]
@michael-markl I marked this as low prio because we can also deliver this feature after the release.

**Comment by michael-markl** [comment]
Readding high-prio label, as it's one of the highest prio remaining task I think.

**Comment by f1sh1918** [comment]
does it make sense to send an additional e-mail with a withdrawal link with a similar view like application verification but just different buttons/action. Not quite sure if we should a different accessKey than in verification

After submitting the the application we can just say you can find additional information like withdrawal in your mail account

**Comment by michael-markl** [comment]
> does it make sense to send an additional e-mail to the user with a withdrawal link with a similar view like application verification but just different buttons/action

Yes, that's the idea!

> Not quite sure if we should a different accessKey than in verification

We should definitely have a different access key for withdrawing the applicaiton (otherwise an organization would be able to do that).


> After submitting the the application we can just say you can find additional information like withdrawal in your mail account

Yes, that sounds good!
We **might** also add some reference number to the text, so that the applicant can contact a Kreis-Mitarbeiter and communicate more efficiently. However, for that we would also have to show this number in the adminsitration frontend.
