### ISSUE TITLE
setup download-links (dynamic download links)

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/entitlementcard#606]
For marketing reasons we want to communicate 
https://download.bayern.ehrenamtskarte.app
https://download.nuernberg.sozialpass.app

Same method as in Integreat: opening the link from Apple leads to Apple Store, from Android leads to PlayStore.
Fallback if not apple/android: first to GitHub, later on to the landing pages (ehrenamtskarte.app / sozialpass.app)

**Comment by maxammann** [comment]
I'll work on this today

**Comment by maxammann** [comment]
I will also try to add a redirectory from nürnberg to nuernberg
