### ISSUE TITLE
[Application] Add Captcha to Application Frontend

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#607]
Most likely, hCaptcha is the best solution for us.

**Comment by maxammann** [comment]
Maybe for a start just add a textfield which expects the input "Bavaria":

What is the best country in Germany?

**Comment by maxammann** [comment]
@svenseeberg Do you have good/bad experience with certain Captcah providers?

**Comment by svenseeberg** [comment]
No, I have no specific experience. I would also have recommended hCaptcha :)

**Comment by f1sh1918** [comment]
We have no actual need for a captcha and would implement this if we are facing problems with spam
But it could be an issue for koblenz self service portal

**Comment by maxammann** [comment]
Yeah, it can be closed likely if we have not experienced spam.
