### ISSUE TITLE
Import multiple Cards

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#612]
As a user I want to import more than one card, e.g. for my children.

## Acceptance Criteria:
 - [ ] More than one card can be activated via the app
 - [ ] The user can switch between different, activated cards (e.g. using a DropBox with the Name + ExpirationYear)

**Comment by f1sh1918** [comment]
@michael-markl we now have a more concrete issue for the sozialpass.(#1084) I'm gonna close this
