### ISSUE TITLE
Cards should have a creator assigned in the DB

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#615]
This enables us to invalidate cards created by a single user (eg. if their account has been compromised).

**Comment by sarahsporck** [comment]
For clarification who is the creator of a card?
We currently don't persist any users in the DB and as far as I know there is no User Id, also, who is the creator of a card? Is it sufficient to use the User name here or any auto incrementing id? Any ideas? :)

**Comment by michael-markl** [comment]
With `user` we actually mean the `administrator` that creates the card.

**Comment by maxammann** [comment]
Confirmed!
