### ISSUE TITLE
Ease copy-paste workflow for applications

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#621]
As a Kommunen-Mitarbeiter I want to have very few work with transferring data from applications to my own Ehrenamtlichen-DB (e.g. Freinet). 

## Acceptance Criteria:
 - [ ] Add a small copy button to each field in the application
 - [ ] Text should be copied on click of the button

**Comment by f1sh1918** [comment]
@michael-markl probably we can close this issue due to the fact that there will be an export csv function for application. These exports can be imported in freinet.

**Comment by michael-markl** [comment]
Cannot really tell. I am not aware of the recent discussions with the customers. "Freinet CSV export" seems like a very specific use case for only a part of the customers. Not all of them have/use Freinet.

**Comment by f1sh1918** [comment]
since we don't have the requirement todo and there are open issues to get api access to freinet and push the data to them. i don't think this will be needed
