### ISSUE TITLE
[Application] End Screen

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#625]
Currently, after submitting the application form, the screen does not change.
Add a final screen that  
* [x] Inform that the application has been received
* [x] Inform about the next steps

For now we don't have a back to the app button, because there is no deep linking. We have to discuss if this is needed.
Find issue here https://github.com/digitalfabrik/entitlementcard/issues/661

**Comment by f1sh1918** [comment]
was solved by https://github.com/digitalfabrik/entitlementcard/pull/648
