### ISSUE TITLE
[Application] Implement Organization-Verification PingPong

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#627]
To verify that an applicant actually works as a volunteer, we need to implement an email-based verification with the organization.
Each organization that the user has entered during the application process should be contacted via mail with a verification link.
Clicking on this link, the organization can Verify that the applicant has worked as a volunteer in their organization.
Once all organizations have verified the applicant's work, the application is shown more prominently in the administration frontend.

**Comment by sarahsporck** [comment]
- [ ] sending e-mail after creating the application
- [ ] a view to verify an application for an "organization" employee
- [ ] split organization information from application in the database
- [ ] reflect the "organization" verification state in administration frontend
- [ ] inform the applicant, whether the application was **not successful** (maybe allow the region manager, etc. to decide whether an email should be sent)
