### ISSUE TITLE
Enforce administrator's region belongs to the administrators's project

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#645]
**Describe the bug**
It is possible to create an administrator in a region which does not belong to the administrators's project. We should not allow to create such administrators. The region should always be part of the project.

**To Reproduce**
Execute: `./gradlew run --args="create-admin nuernberg.sozialpass.app PROJECT_ADMIN admin@example.com Administrator!" 9`

9 is Augsburg in Bavaria.

**Expected behavior**
An error should be shown

**Comment by michael-markl** [comment]
I think this was fixed some time ago. Running

`./gradlew run --args="create-admin nuernberg.sozialpass.app PROJECT_ADMIN admin@example.com` yields

`Exception in thread "main" java.lang.IllegalArgumentException: Specified region is not part of specified project.
