### ISSUE TITLE
Avoid transaction fails

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#662]
**Describe the bug**
In our current deployment of the entitlementcard we have duplicate stores. This can only happen if a transaction fails half way. For example the deletion fails, but the insertion of new stores succeeds.

**Comment by michael-markl** [comment]
I believe this is already fixed by https://github.com/digitalfabrik/entitlementcard/pull/1055.

**Comment by f1sh1918** [comment]
this was fixed. we have no duplicates afaics
