### ISSUE TITLE
Make sure that cards  are generic over card extensions (frontend)

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#674]
**Is your feature request related to a problem? Please describe.**
Currently the card code in the frontend expects for example a BavarianCardType. We need to make it generic such that it works without such a card type. It also should work e.g. with birthday extensions.

The goal of this task is to access data of QR codes in a dynamic way and not to assert on the existance of extensions.

**Describe the solution you'd like**

Depending on the presence of the BavarianCardType the card is valid until the expiration data or for ever.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by sarahsporck** [comment]
So one way to achieve this is by adding dart extensions to the CardInfo. Is that what you mean? Not sure what to do here otherwise.

**Comment by michael-markl** [comment]
I also don't know what this issue is about. Is it just some refactoring issue that can be done after launch, @maxammann?

**Comment by maxammann** [comment]
The idea was that in this task we make sure that cards issues for nuernberg only work in nuernberg and cards only issues for bavaria only work in bavaria.

**Comment by michael-markl** [comment]
I am still not sure what *exactly* this means. It is already not possible to activate a card from a different project. Can you clarify?

**Comment by michael-markl** [comment]
Closing as issue description is unclear.
