### ISSUE TITLE
Support static QR codes

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#675]
**Is your feature request related to a problem? Please describe.**

# Option A: Using Anmeldecodes with fake OTP

The 3rd static QR code (verify code, Anmeldecodes and static verify code exist) should be identical to the anmeldecode. We can do include some tagging mechanism to differentiate between an Anmeldecode and a verification code.

This would depends on #17, in order to be able to have a way of verifying anmeldecodes.

# Option B: Introducing custom endpoints

We want to introduce a new verification code, the StaticVerifyCode. It is similar to the DynamicVerifyCode.

The schema of the new codes look like that:

```proto
message QrCode {
  oneof qr_code {
    DynamicActivationCode activation = 1;
    DynamicVerifyCode dynamic_verify = 2;
    StaticVerifyCode static_verify = 3;
  }
}

message DynamicActivationCode {
  CardInfo info = 1;
  bytes pepper = 2;
  bytes totp_secret = 3;
  bytes ec_signature = 4;
}

message DynamicVerifyCode {
  CardInfo info = 1;
  bytes pepper = 2;
  uint32 otp = 3;
}

message StaticVerifyCode {
  CardInfo info = 1;
  bytes pepper = 2;
  bytes ec_signature = 3;
}
```

We purposely introduced the "enum" QrCode which enforces that clients check for the QR code purpose.

For verifying the StaticVerifyCode we use the `info` and `pepper`. The frotnend creates a hash from the data. The backend will verify if the hash exists in the DB.

This is basically identical to Option A, except that it is completely independent of the OTP mechanism. A new endpoint needs to be introduced to verify hashes without OTPs.
The backend needs to be able to store static cards by setting the OTP secret to null in the database.

## Option B.1: Add optional signatures

Additional to B we want to generate signatures in the administration frontend. The signature is created in the backend and sent to the administration frontend during generation.

**Describe the solution you'd like**
We will go with solution B and B.1.

**Describe alternatives you've considered**
Option A.

We want to go with Option B because it is less hacky.
We also want to directly implement B.1 to be able to perform offline verifications in the future.

**Additional context**
None

**Comment by sarahsporck** [comment]
So what exactly needs to be done here?

- [ ] create a hash from card info and pepper in frontend
- [ ] in the backend create a query for static qr codes that:
- [ ] checks whether a card with the corresponding hash exists in the database

anything missing?

**Comment by michael-markl** [comment]
* [ ] Add a backend endpoint that allows to create static qr codes
* [ ] Add administration code that automatically generates both static and dynamic qr codes for nürnberg
* [ ] Add static qr code to nürnberg's pdfs

**Comment by maxammann** [comment]
- [ ] Add backend endpoint that checks static qr codes
- [ ] Add code to the frontend which can deal with static QR codes

**Comment by sarahsporck** [comment]
> both static and dynamic qr codes for nürnberg

That means each card has both a static and dynamic verify code qr code?

**Comment by michael-markl** [comment]
> That means each card has both a static and dynamic verify code qr code?

Not entirely sure what you mean.

There are three types of QR codes: A StaticVerifyCode, a DynamicActivationCode, and a DynamicVerifyCode.
Nürnberg-Pass-people will get both a StaticVerifyCode and a DynamicActivationCode printed on their PDF/letter.

In the backend, for each such PDF, two independent cards will be added to the DB (with different secrets / pepper / etc. but with the same CardInfo (including name, card extensions, ...)): One for the StaticVerifyCode and one for the DynamicActivationCode.

Does this clarify your question?

**Comment by sarahsporck** [comment]
Jep, that's exactly what I was wondering. Thank you for the clarification.
