### ISSUE TITLE
Handle "No Internet" for verification gracefully

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#676]
**Is your feature request related to a problem? Please describe.**
When verifying a card and there is no connection to api.entitlementcard.app then show that the users should retry in 5 minutes. Make sure that people understand that this does not mean that the card is invalid, but that there is a technical issue.

Do not display a ❌ but instead a 🔧 .

**Describe the solution you'd like**
Quickly implement a api.entitlementcard.app/ping orapi.entitlementcard.app/health which returns a 200 HTTP code and the string "OK".

Call that endpoint in the app to verify that internet works.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by maxammann** [comment]
Might be low-prio, depending on how it behaves right now.

**Comment by f1sh1918** [comment]
@maxammann 
some general questions
`api.entitlementcard.app/ping ` 
Does this mean that there shouldn't be a new graphql webservice but a separate endpoint?

**Comment by maxammann** [comment]
yes, but actually I'm no longer sure if we really want to implement a new endpoint. We can also just add error handling to the existing api calls.
