### ISSUE TITLE
(Placeholder) Demo setting for importing Anmeldecodes

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#678]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maxammann** [comment]
@michael-markl @sarahsporck @f1sh1918 do you remember what this task was for? It might be what I did in #680

**Comment by michael-markl** [comment]
I think so too. Let's close it.
