### ISSUE TITLE
Switch from QR codes to Aztec codes

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#691]
**Is your feature request related to a problem? Please describe.**
Aztec codes offer to encode more information in less 2D code. They are more efficient in terms of bytes/block: https://stackoverflow.com/questions/27857718/aztec-barcode-vs-qr-code

Though the library support is not as good as with QR codes. We postpone this feature for the future, as we are not sure if Aztec codes work sufficiently well in practice.

The ZXing library supports Actec codes sufficiently well.

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
None
 
**Additional context**
None

**Comment by f1sh1918** [comment]
i don't we gonna switch since we don't have bigger issues yet
