### ISSUE TITLE
Add a version for hashes

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#699]
**Is your feature request related to a problem? Please describe.**
We should introduce a version for hashes. That way we can decide during hash comparision whether the comparision failed because of the hashed data or an invalid hasing algorithm/method.

**Describe the solution you'd like**
This version should be included in the DB and also in the QR codes.

This is related to #673 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by michael-markl** [comment]
AFAICS, The version does not need to be included in the DB; it suffices if it's included in the QR codes.

**Comment by michael-markl** [comment]
I would even say that *versioning* the hash algorithms is a low prio task and can be done after release.

**Comment by maxammann** [comment]
True
