### ISSUE TITLE
Refactor frontend card code aka. The "Drüberbügeln" Task

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#703]
**Is your feature request related to a problem? Please describe.**
* [x] Store the protobuf in the secure storage instead of storing everything individually
* [x] Rename "identification" to "activiation" where appropriate
* [ ] ~Rename identification tab to card tab~ https://github.com/digitalfabrik/entitlementcard/issues/721
* [x] Introduce card module. Contains:
  * [x] Global card state
  * [x] Card persistence
  * [x] models related to cards
  * [ ] extension handling (#674)

**Comment by maxammann** [comment]
related to: https://github.com/digitalfabrik/entitlementcard/issues/674

**Comment by michael-markl** [comment]
I am fine with `Identification` tab (literal translation of "Ausweisen"). We already overload the term `card` quite a lot in flutter, so I'd like to keep `identification` (only for the tab name) here. In the same way, I think "Ausweisen" is still a good title for the tab (which goes along nicely with both Bayern's Ehrenamtskarte and the Nürnberg-Pass).

**Comment by maxammann** [comment]
I think we should still remove the term identification from the code base. We can use verification for it instead. This would just remove one term from our glossary.

So on the verification tab you would add anemdecodes and verify a card.

**Comment by michael-markl** [comment]
I am still slightly against this, as both terms (`card` and `verification`) are already overloaded a lot.
Let's keep this issue open to discuss this matter.
I'll mark it as low prio.

**Comment by michael-markl** [comment]
Closing, as remaining tasks have a separate issue.
