### ISSUE TITLE
Create Detail Icon for Apotheken

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#711]
**Is your feature request related to a problem? Please describe.**
Each store item has a detail header depending on the category therefore we need a detail icon.

**Describe the solution you'd like**
Create an icon, add it to assets and map it in the category_assets

**Comment by hauf-toni** [comment]
Icon can be found [📍 here](https://www.figma.com/file/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?type=design&node-id=256%3A632&mode=design&t=bWnrHsINvUVRyvg5-1)
since I don't have access to the original icon files I've made a proposal based on my interpretation of the properties of the svg 👀
