### ISSUE TITLE
Add Nürnberg's data privacy

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#714]
Nürnberg has devlivered their data privacy text.
You can find it here:
https://nextcloud.tuerantuer.org/index.php/f/3523433

The data privacy policy of bayern is available at https://bayern.ehrenamtskarte.app/data-privacy-policy
Similarly, we should make Nürnberg's policy available at https://nuernberg.sozialpass.app/data-privacy-policy

Siehe https://github.com/digitalfabrik/entitlementcard/blob/whitelabel/administration/src/constants/dataPrivacyBase.tsx für die konvertierung von word -> react :smile:.

**Comment by f1sh1918** [comment]
sollte man die nicht in die build config packen?

**Comment by michael-markl** [comment]
Jap, du kannst z.B. die Data-Privacy-React-Componenten für Bayern&Nürnberg in die jeweilige project config schieben.
