### ISSUE TITLE
Whitelabel the Ausweisen Tab

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#719]
Currently, the Ausweisen tab still shows a lot of Ehrenamtskarten-related terminology.
We should adjust the terminology (probably we'll have to make some strings configurable via build config.)

**Comment by maxammann** [comment]
We should also redesign it. In its current state it  is hard to digest. Maybe we can improving it a lot with minor changes.

**Comment by michael-markl** [comment]
Alright, I'll work on a proposal :)

**Comment by maxammann** [comment]
We need to keep the terms though, they are already used in advertisement material

**Comment by michael-markl** [comment]
Proposal was merged in #726

**Comment by maxammann** [comment]
Closing then
