### ISSUE TITLE
Discuss a better name for `identification`-tab.

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#721]
Currently, the frontend has a folder `identification` (for the "Ausweisen" tab) which contains all code related to the activation, application and verification of an entitlement card.

@maxammann does not like "identification". @michael-markl doesn't like renaming it to "card" or "verification".

Maybe a better name is "entitlement_card"?
 
Related: https://github.com/digitalfabrik/entitlementcard/issues/703.

**Comment by f1sh1918** [comment]
we will keep identification
