### ISSUE TITLE
Map is unusable on Android / Map is buggy on iOS

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#727]
**Describe the bug**

* Android:
  The map stays a lot of times white/light brownish (background color of the map style)
  Another issue is that part of the map is not responsible (see https://github.com/m0nac0/flutter-maplibre-gl/issues/54) This bug is again happening.
  The Ehrenamtskarte as it is deployed in the store is less affected. The deployed Nürnberg-Pass app in the play store is unusable. 

* iOS:
  1 out of 100 times the map stays black when opening the app.
  We suspect it is because the map failed to load the style.json because of network issues.

**To Reproduce**
Android:
* Start the app and only 1 out of 5 starts will render a usable map

**Expected behavior**
Map should display

**Comment by maxammann** [comment]
@michael-markl I changed the milestone. The app is pretty much unusable on Android right now.

**Comment by michael-markl** [comment]
@maxammann Interestingly, it works  (reasonably) stable on my phone, so it might relate to the Android Version.

**Comment by maxammann** [comment]
You have an iphone?!

It's definitely Android as I updated in the issue above.

**Comment by michael-markl** [comment]
>You have an iphone?!

Nope :D OnePlus 6 with Android 11

**Comment by michael-markl** [comment]
Maybe related to https://github.com/mapbox/mapbox-gl-native-android/blob/main/CHANGELOG.md#962---july-7-2021

**Comment by maxammann** [comment]
We still use the older maplibre: https://github.com/m0nac0/flutter-maplibre-gl/blob/main/android/build.gradle#L42

**Comment by maxammann** [comment]
That was updated last on 24. Mai 2022
