### ISSUE TITLE
Whitelabel Map config

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#736]
**Is your feature request related to a problem? Please describe.**
Since we have a different area size and location for nuernberg, we have to adjust the map config via buildConfig

**Describe the solution you'd like**
- adjust zoom level (closer than bavaria) since smaller area
- adjust init position to center of nuenberg

**Comment by maxammann** [comment]
I think @michael-markl said he did that already.

**Comment by michael-markl** [comment]
Yep, this should be done already

**Comment by f1sh1918** [comment]
ok then i'm gonna close the issue
