### ISSUE TITLE
Add proper PDF templates for Nürnberg and Bayern

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#744]
**Is your feature request related to a problem? Please describe.**
We switched from manually typesetting icons and instructions in the PDF to using a template.
This task is concerned with creating two .pdf files which will be used when generating PDFs.

**Describe the solution you'd like**
See below how such a template looks like:

![pdf_template](https://user-images.githubusercontent.com/905221/214042678-14bb9987-3fa1-44b6-ae1e-ec7050011b13.svg)

Based on this template two .pdf files should be created for Nürnberg and Bayern. Ideally the PDFs are created using Inkscape because then we developers can make adjustments. Any other tool is fine though.

The template uses mm units for defining the content areas. The mm can be checked when inspecting the following file using inkscape: https://user-images.githubusercontent.com/905221/214042678-14bb9987-3fa1-44b6-ae1e-ec7050011b13.svg

For example the top QR Code has the following spacing: X=105mm, Y=70mm, Width=90mm, Height=90mm

**For Bayern ignore the two content areas at the bottom.**

Here is an sketch of the information which should be on the PDF for Nürnberg. Note: This is just a quick preview crafted by Daniel. You do not need need to make the PDF look similar! Just the information must be preserved!

![nbg-pass-idee](https://user-images.githubusercontent.com/905221/214043922-a98a5b2d-647a-4504-91fe-e5d08ad47f84.png)

* The border of the PDF should be about 1cm, not 2cm! Most printers can print a 1cm border!
* Remove the name after the "Guten Tag". We do not want to change this for every print.

A few more assets useful for this task:

* Google and Apple Badges:
![apple-app-store-badge](https://user-images.githubusercontent.com/905221/214043473-24a7cdc4-4aed-4808-b239-8774732de076.png)
![google-play-store-badge](https://user-images.githubusercontent.com/905221/214043476-fd471f1e-ed14-4bbe-9eba-1a931eecc371.png)

Add the following line at the bottom of the file: Google Play und das Google Play-Logo sind Marken von Google LLC.

* Nürnberg Assets:
![pdf-logo](https://user-images.githubusercontent.com/905221/214043807-872ebf9c-f8ee-4b8f-b3bb-27e9cc5d9b42.png)
![pdf-static-card-background](https://user-images.githubusercontent.com/905221/214043817-c17d039c-da56-4111-8588-14194a0582dd.png)
![pdf-static-card-logo](https://user-images.githubusercontent.com/905221/214043820-ad58ceb7-d256-4b39-9a4b-53c0786b10c8.png)

```
    issuer: 'Stadt Nürnberg',
    appName: 'Sozialpass',
    appDownloadLink: 'https://download.nuernberg.sozialpass.app',
    greeting: (fullName: string) => [`Guten Tag, ${fullName}`, 'Ihr digitaler Nürnberg-Pass ist da!'],
    disclaimer: [
      'Bitte beachten Sie, dass der Nürnberg-Pass nur in Verbindung mit einem amtlichen und gültigen Lichtbildausweis gültig ist.',
    ],
```

* Bayern Assets:
![pdf-logo](https://user-images.githubusercontent.com/905221/214043768-e3fc7574-2434-4f72
![icon](https://user-images.githubusercontent.com/905221/214050250-19ce34f8-7285-4735-b36f-cad09bc39882.png)
-b91b-87d6035c9c06.png)

```
    issuer: 'Bayerische Staatsministerium für Arbeit und Soziales, Familie und Integration',
    appName: 'Ehrenamtskarte Bayern',
    appDownloadLink: 'https://download.bayern.ehrenamtskarte.app',
    greeting: (fullName: string) => [`Guten Tag, ${fullName}`, 'Ihre digitale Eherenamtskarte ist da!'],
    disclaimer: [
      'Bitte beachten Sie, dass die Ehrenamtskarte nur in Verbindung mit einem amtlichen und gültigen Lichtbildausweis gültig ist.',
    ],
```

**Describe alternatives you've considered**
Typesetting the document using jsPDF did not work.

**Additional context**
None

**Comment by michael-markl** [comment]
We should probably add a hint somewhere on the PDF:
"Der Nürnberg-Pass ist nur in Verbindung mit einem amtlichen Lichtbildausweis gültig."
bzw.
"Die Bayerische Ehrenamtskarte ist nur in Verbindung mit einem amtlichen Lichtbildausweis gültig."

(cc: @dkehne, @maxammann )

**Comment by hauf-toni** [comment]
here is a draft for the two pdf's @maxammann
let me know if this works for you or if changes need to be made

[230129-ehrenamtskarte-bayern.pdf](https://github.com/digitalfabrik/entitlementcard/files/10530424/230129-ehrenamtskarte-bayern.pdf)
[230129-entitlement-karte.pdf](https://github.com/digitalfabrik/entitlementcard/files/10530425/230129-entitlement-karte.pdf)

**Comment by maxammann** [comment]
@hauf-toni sieht richtig gut aus! Die reservierten Boxen müssen nur komplett frei bleiben. Also da darf kein Text wie "Ausgestellt am" rein.

Die "content areas" für die nürnberg karte sind bei der Karte noch nicht ganz richtig.

**Comment by michael-markl** [comment]
Sieht schon sehr gut aus 😊 Was mir gerade aufgefallen ist beim "Drüberfliegen":

Bei "[230129-ehrenamtskarte-bayern.pdf](https://github.com/digitalfabrik/entitlementcard/files/10530424/230129-ehrenamtskarte-bayern.pdf)":
1. steht in der Anleitung im ersten Schritt noch "Nürnberg-Pass" statt "Ehrenamtskarte Bayern" und der falsche Link (sollte https://download.bayern.ehrenamtskarte.app sein)
2. Beim 3. Schritt ist der bullet point irgendwie etwas zu weit nach unten gerutscht? :D
3. Nach der Anleitung steht nochmal "Beachten Sie, dass der Nürnberg-Pass..." statt "Beachten Sie, dass die Ehrenamtskarte..."


Bei "[230129-entitlement-karte.pdf](https://github.com/digitalfabrik/entitlementcard/files/10530425/230129-entitlement-karte.pdf)" (was ja für den Nürnberg-Pass ist):
1. Der Download beim ersten Schritt in der Anleitung sollte denke ich mit http**s** anfangen
2. Das Icon unter dem Download-Link ist das von der Ehrenamtskarte -- das müsste noch mit dem Nürnberg-Pass-Icon ausgetasucht werden (welches auch rechts oben auf dem PDF ist)

Minor: Muss man "Google Play und das Google Play-Logo sind Marken von Google LLC" da drauf schreiben? Muss man es beim App-Store nicht?

**Comment by hauf-toni** [comment]
danke euch @michael-markl @maxammann  i have revised both pdfs according to your comments: 
[230130-ehrenamtskarte-bayern-dig.pdf](https://github.com/digitalfabrik/entitlementcard/files/10533363/230130-ehrenamtskarte-bayern-dig.pdf)
[230130-Nürnberg-Pass-dig.pdf](https://github.com/digitalfabrik/entitlementcard/files/10533383/230130-Nurnberg-Pass-dig.pdf)

**Comment by maxammann** [comment]
[230130-Nürnberg-Pass-dig-content-areas.pdf](https://github.com/digitalfabrik/entitlementcard/files/10536610/230130-Nurnberg-Pass-dig-content-areas.pdf)

**Comment by hauf-toni** [comment]
@maxammann already shared the numbers for the content areas, here's the updated pdf for nürnberg:
[230129-Nürnberg-Pass-digital-V2.pdf](https://github.com/digitalfabrik/entitlementcard/files/10538061/230129-Nurnberg-Pass-digital-V2.pdf)

**Comment by maxammann** [comment]
New measurements for contenet areas:

[230206 Ehrenamtskarte_content areas.pdf](https://github.com/digitalfabrik/entitlementcard/files/10662054/230206.Ehrenamtskarte_content.areas.pdf)
