### ISSUE TITLE
Clarify "App access"

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#751]
**Is your feature request related to a problem? Please describe.**
Google and Apple wants an entitlementcard! What do we do?
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maxammann** [comment]
Yes, that would be one option. Though we somehow have to provide them with access in the production builds. We can not upload pictures though.

I explained in a free text field that providing cards is not possible because card holders have to live in Nürnberg. Let's see if they complain. If they do not complain I guess we can risk it.

Worst things which can happen is that app updates are hold back.

**Comment by michael-markl** [comment]
So, in the case of rejection, one option would be to add an easter-egg which lets them activate a hardcoded, (clearly indicated) invalid card (without doing server verification)?

**Comment by michael-markl** [comment]
Blocked until we know whether further action is required.

**Comment by michael-markl** [comment]
Closing as it seems no further action is required.
