### ISSUE TITLE
Add Checkbox when Verifying Static QR Code

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#753]
**Is your feature request related to a problem? Please describe.**
As the Static QrCode is could be used by anyone actually further verification makes sense.

**Describe the solution you'd like**
In the case, a static card is being verified, the user (the verifier) should be asked "more thoroughly" to check the personalausweis (for example, once the server has verified the static card, a checkbox labeled "Ich habe die Daten mit einem amtlichen Lichtbildausweis abgeglichen" should be shown, and only once this checkbox is checked, it should show "Nürnberg-Pass ist gültig".)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by maxammann** [comment]
I think we can deliver this also after the 01.03
