### ISSUE TITLE
Imported data has wrong city

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#759]
**Describe the bug**
On the following screenshot the road and house number is displayed where the city should be.

**Screenshots**
![rn_image_picker_lib_temp_a9f8bd36-78b6-4ec8-986e-9d6a8ff82543](https://user-images.githubusercontent.com/905221/214821772-bdfbaa20-499a-4b53-9502-eba5bac7a38f.jpg)

**Comment by f1sh1918** [comment]
already fixed
