### ISSUE TITLE
Improve PDF

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#783]
**Is your feature request related to a problem? Please describe.**
Let's collect here what we could like to change with the current PDF layout:

![Screenshot 2023-02-06 at 13-08-48 Nürnberg-Pässe - ehrenamtskarten pdf](https://user-images.githubusercontent.com/905221/216967645-9262b796-89c8-4ef3-a3f4-dda4d6a89e44.png)

**Comment by maxammann** [comment]
Size of a single print:

* Nürnberg: 280kb
* Bayern: 180kb

**Comment by dkehne** [comment]
why does it need this trademark-entry for Google Play?

**Comment by michael-markl** [comment]
It should probably not read "Einfach herauslösen" as we don't have perforiertes Papier. "Einfach ausschneiden, falten, kleben - und sparen!" Would be the alternative 😂

**Comment by maxammann** [comment]
> why does it need this trademark-entry for Google Play?

Google wants us to put it there. I don't have more information about the "why".

**Comment by maxammann** [comment]
A few more things came up during the standup:

* Remove second smaller static QR code: Else users might think they actually have 2 static cards which they can share with others.
* Include a 7-digit hash prefix of the card details (static & dynamic). That way we can find the card again in the database and revoke it
* console.log(base64): We should log the base64 of the QR codes in the administration frontend. That way we can copy&paste them to the app without QR code scanning
* Add a note: Bitte bewahren Sie das Dokument auf, damit Sie die Karte beim Smartphone wechsel/verlust aktivieren können.

**Comment by michael-markl** [comment]
Wofür brauchen wir das 7 Digit hash prefix? Wenn wir das PDF haben und die QR Codes, können wir den hash ja leicht ermitteln.

**Comment by maxammann** [comment]
> Wofür brauchen wir das 7 Digit hash prefix? Wenn wir das PDF haben und die QR Codes, können wir den hash ja leicht ermitteln.

Ja, tatsächlich kann man den Hash ermitteln wenn man den dynamischen QR code einscannt als Ehrenamtlicher.

Wir empfehlen ja aber glaube ich nicht dass die Städte die PDFs aufbewahren. D.h. nur der User kann den QR code noch einscannen. Der User soll ja aber den statischen QR code abtrennen. D.h. wenn der revoked werden soll, dann hat man ein Problem, weil der ja nicht auf der normalen PDF (die man aufbewaren soll) hinterlegt ist.

Das Problem stellt sich also nur bei Nürnberg und den statischen Codes. Allgemein ist es aber einfacher die 7 ziffern durchs Telefon durchzugegeben als einen QR code einzuscannen am PC.

**Comment by maxammann** [comment]
Also dass User die Karte revoken, können wir glaube ich ausschließen. 
Wenn aber eine Stadt was revoken will (falsch ausgestellt), und sie haben die PDF noch. Sollen wir da was anbieten?

**Comment by michael-markl** [comment]
Also, wenn sie die PDF haben, könnten wir das eben theoretisch via den QR-Codes machen. Wenn sie was revoken möchten, könnten sie uns also theoretisch einfach die PDF schicken und wir erledigen den Rest.
Sonst müssten wir zwei 7 digit hash prefixe drauf drucken, einen für den dynamic code und einen für den static code...

**Comment by michael-markl** [comment]
Imo könnten wir ohne starten, und uns eine lösung ausdenken sobald wirklich Bedarf da ist.

**Comment by michael-markl** [comment]
Related: #795 
We should probably use the word "Aktivierungscode" in the PDFs. Except @dkehne is against that because of existing marketing material? :D

**Comment by michael-markl** [comment]
Der Satz 
```
Starten Sie die App und tippen Sie auf „Ausweisen“.
Folgen Sie den Hinweisen zum Aktivieren des
Anmeldecodes.
```

sollte geändert werden in 
```
Starten Sie die App und tippen Sie auf „Ausweisen“.
Folgen Sie den Hinweisen zum Aktivieren des
Nürnberg-Passes.
``` 

Analoge Änderungen sind für die Ehrenamtskarte zu machen.

**Comment by hauf-toni** [comment]
[Ehrenamtskarte-Bayern](https://github.com/digitalfabrik/entitlementcard/files/10838346/230227-Ehrenamtskarte-Bayern-V1_0.pdf)
[Ehrenamtskarte-Nürnberg](https://github.com/digitalfabrik/entitlementcard/files/10838347/230227-Ehrenamtskarte-Nurnberg-V1_3.pdf)

@michael-markl these are the pdfs with the updated text

**Comment by f1sh1918** [comment]
we have two additional requirements for nürnberg

- add a placeholder for the nürnberg-pass-id on the pdf #900 
- add a letterhead with name, addresszeile1, addresszeile2, postal code + city which should be editable #903

**Comment by hauf-toni** [comment]
The additional requirements as well as the specifications of the city of Nürnberg are included **in this new version** [230515-Ehrenamtskarte-Nürnberg.pdf](https://github.com/digitalfabrik/entitlementcard/files/11484374/230515-Ehrenamtskarte-Nurnberg.pdf)

**content areas as visualized here**: 
(https://github.com/digitalfabrik/entitlementcard/assets/123894307/7b760b51-70c4-47d3-a8be-0d35d5e0ec3c)
_adress field_ (X: 25mm, Y: 61mm, B:73mm, H: 20mm)
_Nürnberg-Pass-ID for Deutschlandticket_ (X:129, Y:79, B: 44, H: 5)
_Anmeldecode QR big_ (X: 122, Y: 110, B/H: 63)
_Card QR big, left side_ (X: 53, Y: 222, B/H: 47)
_Text card right side, eg name & date of birth_ (X: 108, Y:243, B: 52, H: 26mm)
_Card QR small, right side_ (X: 164, Y: 243, B/H: 21)

**Comment by hauf-toni** [comment]
> The additional requirements as well as the specifications of the city of Nürnberg are included **in this new version** [230515-Ehrenamtskarte-Nürnberg.pdf](https://github.com/digitalfabrik/entitlementcard/files/11484374/230515-Ehrenamtskarte-Nurnberg.pdf)
> 
> **content areas as visualized here**: (https://github.com/digitalfabrik/entitlementcard/assets/123894307/7b760b51-70c4-47d3-a8be-0d35d5e0ec3c) _adress field_ (X: 25mm, Y: 61mm, B:73mm, H: 20mm) _Nürnberg-Pass-ID for Deutschlandticket_ (X:129, Y:79, B: 44, H: 5) _Anmeldecode QR big_ (X: 122, Y: 110, B/H: 63) _Card QR big, left side_ (X: 53, Y: 222, B/H: 47) _Text card right side, eg name & date of birth_ (X: 108, Y:243, B: 52, H: 26mm) _Card QR small, right side_ (X: 164, Y: 243, B/H: 21)

In addition to the content areas already described, the "Nürnberg-passport-ID" is to be displayed on the left side. the area for this is as follows: X:24, Y:222, W:7, H:47. for better understanding, here is a picture of the additional area
![230515-Ehrenamtskarte-Nürnberg-content-areas-V2](https://github.com/digitalfabrik/entitlementcard/assets/123894307/36d989d7-8e55-43d3-b086-bd6ce8c38845)
as well as the draft of the pdf (content placement not correct to the millimeter): 
[entitlementcard-pdf-nürnberg-content.pdf](https://github.com/digitalfabrik/entitlementcard/files/11490437/entitlementcard-pdf-nurnberg-content.pdf)
