### ISSUE TITLE
(Placeholder) Support EC signatures in StaticQRCode (and maybe add them to the activiation process)

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#785]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sarahsporck** [comment]
Technically the StaticVerificationCode does already have an ec_signature in the protobuf. Only DynamicVerificationCode is missing the signature.

**Comment by maxammann** [comment]
Let's remove the signature and do this if at some point an offline check is really required.

**Comment by sarahsporck** [comment]
So EC refers to error correction. How does EC refer to offline check?

**Comment by f1sh1918** [comment]
@maxammann if this is import, could you maybe add some context to this and why it's prio high

**Comment by maxammann** [comment]
As we already rolled out this is no longer high prio.

The idea was to add a signature to allow offline verification.
