### ISSUE TITLE
Avoid creating wrong production builds (mixes of Nürnberg an Bayern)

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#789]
**Describe the bug**
It is currently possible to create an production build where the dart code is whitelabeled for Nürnberg and the native part (app name) for Bayern.

I'm concerned that we roll out a wrong build in the future.

I dont have a plan yet how to solve this.

Additional:
- Set the default value to production (current: dev)

**Expected behavior**
Such builds should not be possible.

**Comment by f1sh1918** [comment]
What about checking the `flavor`(lowercase) against the `build_config_name` . This is not a good check but better than none?!

**Comment by maxammann** [comment]
A runtime check could also be the last resort to get some feedback from Google Dev console. If we just crash if something is odd, then we will notice earlier.
