### ISSUE TITLE
Improve QR code scanning when multiple codes are in view

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#790]
**Is your feature request related to a problem? Please describe.**
Currently as soon when a QR code is detected we interpret its data and directly afterwards close the QR code reader. Either a success message or an error is shown.

This is especially problematic in Nürnberg where we have a PDF which two different QR codes.

**Describe the solution you'd like**

I think this behavior can be improved. In the case of a parsing/decoding error the QR code scanner should stay active. This way when the QR code scanner returns invalid bytes (scanning error) or an unexpected card is read (static instead of dynamic code) the user can just continue to scan until it works (This actually was the behavior previously when scanning QR codes which contain binary data before #775).

This is way more convenient than pressing OK in the error dialog and start the scanner again.

We could actually never automatically close the scanner during verification, but just show a popup above the scanner. Then the verifying person can just continue with the next QR code, until the scanner is closed explicitly.

**Describe alternatives you've considered**
Keep the current state.

**Additional context**
None

**Comment by michael-markl** [comment]
Another alternative could be that the dialog that shows the verification result, shows the action buttons "Weiteren Code scannen" and "Fertig".

**Comment by maxammann** [comment]
> Another alternative could be that the dialog that shows the verification result, shows the action buttons "Weiteren Code scannen" and "Fertig".

But what would you do if a wrong QR code is scanned? e.g. when having the whole Nürnberg PDF in view or dragging the scanner over the page?

This happened to me yesterday. Even though I did not want to scan the static code I got multiple popups at the same time saying once the QR code is invalid and once the card could not be activated.

**Comment by michael-markl** [comment]
I believe there's not much we can do about that (if the scanner has multiple qr codes in view, I guess it is undeterministic behavior which qr code it chooses to scan). What would be your solution to that?

**Comment by maxammann** [comment]
> I believe there's not much we can do about that (if the scanner has multiple qr codes in view, I guess it is undeterministic behavior which qr code it chooses to scan). What would be your solution to that?
> 
> **Edit:** Also, if a wrong one is scanned, I would also show the action buttons "Weiteren Code einscannen" and "Fertig". Then, the user can at least try again more conveniently.

So my proposal in this issue is to just more silently ignore invalid QR codes. We could display a snackbar message or just display nothing. This is the same behavior when e.g. scanning a QR code which is damaged.

Else when just dragging your phone over the Nürnberg PDF, you will likely get a popup which says an error happened.

Also we neeed to disable scanning new codes while another popup is open. This is also a bug right now, as you will get multiple popups which cover each other.

**Comment by michael-markl** [comment]
Imo, displaying nothing would be bad UX. If the user tries to scan a wrong QR code, we should at least tell him (somehow) that we saw the QR Code, but could not do anything with it.
Snackbar sounds fine to me for wrong qr code types. I think we should not show a snackbar, if we have no internet connection, or if the qr code is of the correct type, but backend says it's invalid.

**Comment by f1sh1918** [comment]
the improvement or invalid qr code handling will be implemented here #1173
