### ISSUE TITLE
Bayern: Change contact data "Herausgeber" und "Haftung" with general data

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/entitlementcard#794]
Replaces the Contact details of Mr. Diener under Publisher and Liability by general data 
 ([Poststelle@stmas.bayern.de](mailto:Poststelle@stmas.bayern.de) and Durchwahl -01

**Comment by maxammann** [comment]
Forgot to do this in #801

**Comment by michael-markl** [comment]
@dkehne Should this also be adjusted in the datenschutzerklärung? https://bayern.ehrenamtskarte.app/data-privacy-policy

**Comment by dkehne** [comment]
@michael-markl please everywhere where he is mentioned.
