### ISSUE TITLE
Change wording "Anmeldecode" in PDF

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#795]
**Is your feature request related to a problem? Please describe.**
In our application we use "Aktivierungscode einscannen" in the PDF we use "Anmeldecode"

**Describe the solution you'd like**
We should agree on a wording.

**Comment by dkehne** [comment]
I have checked the marketing material from STMAS but the wording was not used somewhere. 

Use Aktivierungscode.

**Comment by hauf-toni** [comment]
Updated PDF can be found [here](https://nextcloud.tuerantuer.org/index.php/f/4338814).

**Comment by steffenkleinle** [comment]
> Updated PDF can be found [here](https://nextcloud.tuerantuer.org/index.php/f/4338814).

Thanks @hauf-toni. Do you have the same for the Bayerische Ehrenamtskarte? Couldn't find it in nextcloud.

**Comment by michael-markl** [comment]
> Updated PDF can be found [here](https://nextcloud.tuerantuer.org/index.php/f/4338814).

The instructions on the left still have two occurences of "Anmeldecode". Could you replace these too?

**Comment by hauf-toni** [comment]
The updated PDF for Nürnberg can be found [here](https://nextcloud.tuerantuer.org/index.php/f/4338814), for Bayern [here](https://nextcloud.tuerantuer.org/index.php/f/4496444)

**Comment by sarahsporck** [comment]
will be done in #903 as pdf updates either way in the corresponding pr
