### ISSUE TITLE
Limit count of Akzeptanzstellen in tile responses

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#799]
**Is your feature request related to a problem? Please describe.**
We currently allow martin to create tiles with over 5k entries: https://tiles.ehrenamtskarte.app/rpc/physical_stores/0/0/0.pbf

That tile takes 1s to load. This is a good target to bring our servers down 😅 

**Describe the solution you'd like**
Limit the amount of points in a tile to 100/200.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by michael-markl** [comment]
1s for just 5k entries seems pretty long to me 😅 Can we speed up things somewhere?

**Comment by maxammann** [comment]
Hmm to be honest I'm not sure if it's quick or slow. It's quite a large query which is encoded in an MVT.

The bottleneck is postgis definitely.
