### ISSUE TITLE
Salt password for administrators

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#817]
https://github.com/patrickfav/bcrypt#custom-salt-or-securerandom

Handle it just like the JWT secret file.

Abort the server execution if it does not exist.

**Comment by michael-markl** [comment]
Afaics, in your linked article it's possible to just use an instance of SecureRandom and it will automatically add a salt into the hashed password (and the salt will be different for each password). This seems more portable to me. Security wise: It's probably just as secure as having a single secret salt for the whole DB?

**Comment by michael-markl** [comment]
In fact, BCrypt.withDefaults (which we currently use) already generates a salt per password. So we might not need to do anything here.

**Comment by maxammann** [comment]
Yes, we were wrong. It is already done.
