### ISSUE TITLE
Don't require inserting the email address in the password reset form

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#825]
**Is your feature request related to a problem? Please describe.**
Currently, when the user resets their password (or sets it for the first time), they receive an email with a password reset link.
Clicking on that link, the user has to enter his email address. However, this should not be necessary. Instead, we can include the email address in the reset link as a URL param.

*Background*: If the user misspells his/her email, we cannot give him a proper error message. Avoiding these mistakes, can reduce a lot of confusion.

**Comment by f1sh1918** [comment]
implemented with https://github.com/digitalfabrik/entitlementcard/pull/878
