### ISSUE TITLE
Emails should not be case sensitive when logging in 

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#826]
**Describe the bug**
Currently, we allow emails to be case sensitive. However, users often expect that the field is case insensitive.
The user should be able to login/reset password when entering an email in the "wrong" case.

**Solution**
The best solution would probably be to use a case insensitive column in the DB.
We'd need to migrate the column though.

**EDIT**: Probably we should not use `citext` (or store the emails as lowercase), as the email spec actually allows case sensitive "local" parts (before the @). However, we should make the uniqueness constraint case-insensitive as well as all SQL queries that query by email.

**Comment by sarahsporck** [comment]
I don't get why we should not use `citext` as the text should actually stay case-sensitive. In the spec it states that the actual text will still stay case-sensitive. 
Neither `citext` (even though there exists a workaround) nor computed indexes are currently supported by exposed.

**Comment by michael-markl** [comment]
Hmm, I haven't thought about `citext` too long. "Case insensitive text" sounds to me as if it is undeterministic what case we would get out of it, once stored :D But it's probably up to the implementation, and postgres likely does behave as you say :)

A minor problem with citext might also be that we cannot define a max length like with varchar 🤔 Not sure what kind of DB implications on perf etc. this would have... Do you know?

> [not] supported by exposed

Maybe one more reason, to stay with varchar?

I'm not completely against citext, but would be cautious :D
