### ISSUE TITLE
Test small QR-Code variant on Nürnberg's static code.

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#829]
**Is your feature request related to a problem? Please describe.**
Nürnberg wants to only have the small QR code so that they can have a single-page card.

For that, we need to ensure that these very small sized QR codes actually work properly.

Test:
1. Print a PDF (with a pretty long name)
2. Cut out the static card with the small QR code
3. Try to scan the QR-code
4. Simulate some wear-off on the print-out (by folding/scratching/painting/etc.)
5. Try to scan the QR-code

**Comment by sarahsporck** [comment]
Actually Nürnberg already gave feedback that the small qr code was not scannable on their iPhone. We should of course still check how the bigger qr code performs...

**Comment by michael-markl** [comment]
Did Nürnberg agree to use the double-sided variant of the static card in the feedback meeting?

**Comment by sarahsporck** [comment]
Hmm. Tbh, not sure wether they had a clear opinion on this. We discussed the usage of the bigger and smaller qr-code. Maybe @dkehne can tell more about this.
Can shortly explain what you mean with double-sided? :)

**Comment by f1sh1918** [comment]
can we close this issue @michael-markl ?

**Comment by michael-markl** [comment]
I'm fine with closing. However, we don't really have a decision yet, so it might be good to keep it open, just to have it "auf dem Radar" ? :D

**Comment by f1sh1918** [comment]
so far nürnberg is using double sides pdfs with big qrCode on the back. So i think we can close this ticket
