### ISSUE TITLE
Better error handling for password-reset

### ISSUE THREAD

**Issue by michael-markl** [digitalfabrik/entitlementcard#830]
**Is your feature request related to a problem? Please describe.**
When clicking on a password reset link, the user does not know whether the link is still valid.
If it isn't and the user continues to submit the form, the user gets a very general error message.

Improve error handling (eg. better error message, check whether key is still valid, etc.)

**Comment by f1sh1918** [comment]
@michael-markl i recently implemented the link checker which returns if it's valid link in general and if it isn't expired. Think this can be closed as we have a general refactoring ticket #873
