### ISSUE TITLE
Filterbar text doesn't break correctly on small screens

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#831]
**Describe the bug**
When opening the search on small screens the category text is not wrapped correctly.

**Expected behavior**
If the text is too long then the word is broken into a new line.

**Screenshots**
See Dienstleistung
<img src="https://user-images.githubusercontent.com/28013368/221821936-b275efdf-001c-49d5-973e-b1edec3caafa.png" width=300 />

**Smartphone (please complete the following information):**
 - Device: iPhone 8

**Comment by michael-markl** [comment]
If this is really a concern (phones with a display of less than 5 inch are really rare these days), we could 
* Option A: Force a single line and use [FittedBox](https://api.flutter.dev/flutter/widgets/FittedBox-class.html) to shrink the label if necessary
* Option B: Do some hyphenation magic (for which Flutter offers bad support I guess: https://github.com/flutter/flutter/issues/18443)

**Comment by f1sh1918** [comment]
i think the fitted box is a good solution in this case

**Comment by michael-markl** [comment]
This package could be potentially used (or its source could be used): https://pub.dev/packages/auto_hyphenating_text
But might also be overkill to add another dependency just for that.

**Comment by f1sh1918** [comment]
until there is no report from users/customers we keep it as it is
