### ISSUE TITLE
[ApplicationVerification] Send verification E-Mails after creating an application

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#836]
**Is your feature request related to a problem? Please describe.**
The referenced organizations of an application need to be informed and verify an application.

**Describe the solution you'd like**
When a user submits an application and it is stored in the DB, the referenced organizations should each receive a verification e-mail. Think about the text. There already exists a utility to send e-mails in the backend. 

[EDIT] The url should be encoded, so that outlook can pick it up. See: https://github.com/digitalfabrik/entitlementcard/pull/828

Blocked by 
- #834

**Comment by michael-markl** [comment]
@sarahsporck What needs to be done to unblock this task from #837? I think, we only need to agree on a route, so that we can generate the links to the correct URL on which the organizations can verify/reject an application?

**Comment by sarahsporck** [comment]
Exactly. I am currently still struggeling to decode on the route in the other task. I guess what makes the most sense is sth. Like `/verifizieren/{application_verification_id}?accessKey={accessKey}`. Do you agree?

**Comment by michael-markl** [comment]
If it makes it any easier, we can also do `/verifizieren/{application_verification_id}/{accessKey}`.
However, we might actually want to rename `verifizieren` => `antrag-verifizieren`?

**Comment by sarahsporck** [comment]
Hmm. As far as I know there is no specific ruling when to use path and query params. Generally, [the path leads to a specific resource and then the query filters/sorts/... the resource](https://www.ibm.com/docs/en/cics-ts/5.1?topic=concepts-components-url). Therefore, I'd but the access key into the query param. Are you alright with `/antrag-verifizieren/{application_verification_id}?accessKey={accessKey}`?

**Comment by michael-markl** [comment]
Sorry for the late objection: As I wrote in your current PR #857 , we should probably avoid externalizing our interal ids. Also, I originally designed the accessKey to be unique. So we should be able to just omit the application_verification_id in the link and go with either `/antrag-verifizieren/{accessKey}` or `/antrag-verifizieren?accessKey={accessKey}` whatever suits you better. Feel free to speak against this :D
