### ISSUE TITLE
[ApplicationVerification] Verification view for applications

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#837]
**Is your feature request related to a problem? Please describe.**
A contact person of an organization needs to verify the correctness of an application. For that the contact person needs to:
- view the application
- verify the application ✅ 
- reject the application ❌ 

**Describe the solution you'd like**
Create a route in the administration frontend that displays an application. The route should be hidden behind (maybe?) the ~~application~~application verification hash or sth. so that it is not visible to any user. Further make sure these routes should definitely not be crawled or indexed by any search engine. 
The page displays the application, and a button to verify and reject an application. 

**Describe alternatives you've considered**

**Additional context**

**Comment by sarahsporck** [comment]
Not sure whether possible other organization should also be displayed. But for now probably not very important.

**Comment by michael-markl** [comment]
For simplicity, I'd probably just show the whole Antrag and then ask a question like 
"Können Sie die Angaben, die die Organisation {organizationName} betreffen, bestätigen?"
[Button: Bestätigen], [Button: Widersprechen]

**Comment by sarahsporck** [comment]
@maxammann @michael-markl I am actually unsure about how the authentication workflow is intended. More clearly, I am wondering what the access token is used for exactly. Should it be used as an authentication header as in Bearer authentication?

**Comment by michael-markl** [comment]
The access token is used for authentication.
I think originally the idea was that the verifyer gets the link with the access key encoded. He clicks on the link and the application frontend can extract the access token and forward it to the graphql interface.
Given the access key, the graphql interface allows to retrieve the application and allows to verify or reject the application.

Whether the key is transmitted via a header or not is probably not relevant. I think we should probably not put it into the header as it might be more complicated.

Does this clarify your question?

**Comment by sarahsporck** [comment]
Jep. So I basically just need to get rid of the id, and everything is fine? "Encoded" refers to urlencoding?

**Comment by michael-markl** [comment]
Yes!
