### ISSUE TITLE
Layout of IdCard slightly broken

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/entitlementcard#840]
**Describe the bug**
Padding on the screenshot is missing ~~and name should be "Alex Muster".~~

~~Relates to the play-/app-store screenshot~~

Maybe, the missing padding occurs when the text size is specified to some large value  in the system settings.

![Screenshot_20230302_144703_Nrnberg-Pass](https://user-images.githubusercontent.com/4182469/222708604-a46e7308-2c9b-4e5b-b6c8-66aed896b3c4.jpg)

**Comment by michael-markl** [comment]
For screenshots in the stores, make sure to use Demo mode on Android! 
https://developer.android.com/studio/debug/dev-options#general

**Comment by michael-markl** [comment]
As we don't have that screenshot in the stores, I will repurpose this issue to only address the padding issue.
