### ISSUE TITLE
Add application id to application overview

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#868]
Show in the header for the application overview an id

- format: {regionID}-{applicationId}
- show in ApplicationApplicantOverview, ApplicationVerification, ApplicationsOverview (internal view)

**Comment by sarahsporck** [comment]
applicationId refers to the id in the db? Not sure whether we want to expose that. @michael-markl @maxammann

**Comment by maxammann** [comment]
Ids are public in the entitlement card, as long as guessing ids is not a problem. E.g. by leaking the ID the amount of issued applications becomes public. I don't think that this is a problem.

**Comment by f1sh1918** [comment]
its not required yet and it can be found via name
