### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#873]
**Is your feature request related to a problem? Please describe.**
We are currently very inconsistent, how we handle errors in both backend and frontend.
A consistent error culture can improve the user experience and avoid any unwanted side effects (as errors shown in the frontend)

**Describe the solution you'd like**
- Consistent usage of Graphql errors: https://www.apollographql.com/docs/react/data/error-handling/ 
- Consistent error handling (not ignoring errors...)

**Describe alternatives you've considered**
Error return messages: 
```json
{
    "status": <http_status_like>,
    "message": <maybe_optional_because_of_translations>,
    "result": <only_for_queries>
}
```

**Additional context**
There are several related tickets for this: 
- #324 
- #836 
- #659 
- #830

**Comment by f1sh1918** [comment]
@sarahsporck do you think this is possible to implement within this week. I see that its import but i think maybe we have more urgent tasks, f.e. to add a backend switch to testing system, since we should be able to start testing very soon

**Comment by sarahsporck** [comment]
I think error handling **can** in fact also wait till after the release, but should be the issue we tackle directly after all other important tasks have been done. Such as e.g. a backend switch to a testing system. Not sure if i'll be able to finish this this week as this concerns backend, frontend and administration in the same way.
