### ISSUE TITLE
Logout does not redirect to default route

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#883]
**Describe the bug**
When a user logs out the route doesn't change to the default route. So if you login with user having different permission you can not reach the route because of missing permission

**To Reproduce**
1. Login with Region Admin
2. Go to Benutzer verwalten
3. Logout
4. Login with region manager
5. Error "Berechtigung fehlt"

**Expected behavior**
If i logout the user gets redirected to the default route.

**Comment by michael-markl** [comment]
Imo this is not a bug, as sometimes it is beneficial not to route to a default route when logging in.
A proper message like "Berechtigung fehlt" seems fine for me.

**Comment by michael-markl** [comment]
Logout should redirect to "/". Login should not redirect.

**Comment by michael-markl** [comment]
Logout should redirect to "/". Login should not redirect.
