### ISSUE TITLE
Application createDate timestamp wrong on production

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#886]
**Describe the bug**
On production system the createDate timestamp is UTC instead of UTC+1

**To Reproduce**
1.https://bayern.ehrenamtskarte.app/beantragen
2. Submit an application
3. Login with a region manager of the region that you submitted the application
4. Go to eingehende Anträge
5. Check if the creation date is correct

**Expected behavior**
When i create an application in UTC+1 it should be reflected in the database.
Note: It works locally. 
At 10:17 this creationDate was set in productionDB
`2023-03-22 09:17:58.083568`

**Comment by f1sh1918** [comment]
we should use a defined timezone for creation date

**Comment by maxammann** [comment]
I think the actual data stored in the DB is independent of timezones. We just need to evaluate the time according to our timezone (which is set in the project settings).

I think by default the DB connector tells the DB which timezone to choose. Or it just uses the system timezone.
