### ISSUE TITLE
Deactivate Ehrenamtskarte beantragen in App

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#888]
**Is your feature request related to a problem? Please describe.**
Since the implementation of the application process is not finished yet. The possibility to make an application inside the app should be disabled for now.

**Describe the solution you'd like**

- Create a link forwarding from '/beantragen' to https://www.lbe.bayern.de/engagement-anerkennen/ehrenamtskarte/antraege/index.php
- Add a button for reaching /beantragen after user is logged in

**Comment by maxammann** [comment]
This can also be done in the WebApps, for quicker deployment.

**Comment by michael-markl** [comment]
Good idea! We could also simply redirect /beantragen to https://www.lbe.bayern.de/engagement-anerkennen/ehrenamtskarte/antraege/index.php

**Comment by f1sh1918** [comment]
open pr here : https://git.tuerantuer.org/DF/salt/pulls/56
