### ISSUE TITLE
[Bayern] CSV bulk import card creation templates

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#891]
As a user i want to import multiple card templates via csv and print them

## Acceptance Criteria:
 - add a button in the create cards view to "Bulk Import" cards
 - add information about how the csv schema should look (name, date, cardType)
 - application pdf will be downloaded in a single pdf file

Related to 
- #902

**Comment by michael-markl** [comment]
I think we should not be talking about applications, but rather card creation templates.

**Comment by f1sh1918** [comment]
sorry my mistake
