### ISSUE TITLE
[Application] Add Physical Card Checkbox

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#894]
**Is your feature request related to a problem? Please describe.**
As an applicant i want to be able to choose if i want the entitlementcard digital and /or physical. 

**Describe the solution you'd like**
- Implement an additional checkbox for physical card
- Save the information in the database

**Comment by michael-markl** [comment]
Alternatively, three radio buttons would work as well... Probably up to the implementer :)

**Comment by f1sh1918** [comment]
@michael-markl 
i think we could just add one checkbox more and change the label and the description above. its the easiest way and users have a good overview.

- i want a physical card
- i want a digital card

just the question if we preselect both

**Comment by michael-markl** [comment]
> i think we could just add one checkbox more and change the label and the description above. its the easiest way and users have a good overview.
>
> * i want a physical card
> * i want a digital card

I am fine with that. We just need to make sure in some validation logic that the user does not deselect both, which increases complexity very slightly (but I'm fine with that^^)

> just the question if we preselect both or want to enforce digital solution because i think no one will deselect

I guess, that's up to you. I'm fine with preselecting both by default (I think the user would usually select both). I am also fine with not preselecting at all (then the user's choice is "more emphasized" :D ).
