### ISSUE TITLE
[Sozialpass] Additional Field Nürnberg-Pass-Id on PDF

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#900]
As a service user i want to have an additional field for the nuernberg pass id in the card creation form

## Acceptance Criteria:
 - add the additional field in the card creation form
 - show the pass id on the pdf imprint
 - the pass id will not be saved in the database

## Technical Tasks:
 - enable additional field only for nuernberg
 - adjust the pdf template
 - char field with 10 digits (even it should only contain 8-9 numbers)

**Comment by hauf-toni** [comment]
@f1sh1918  please specify where exactly in the document the additional field should be featured, e.g. in the lower content field on the right side of the card, thank you

**Comment by sarahsporck** [comment]
@hauf-toni probably next to the card information on the right side, where you also find the name and expiration date...

**Comment by f1sh1918** [comment]
I think Daniel is working on a Text where this is included like:
You can use this {PassId} to get a discount to the deutschlandticket. I think it's not finalized yet. You can contact hin and tell him to Update this ticket with the text

**Comment by dkehne** [comment]
I will get the final update on the text on 14th May latest. 
Please use this before "Bitte beachten Sie: Um das Deutschland-Ticket für den Verkehrsverbund Großraum Nürnberg (VGN) zu erhalten nutzen Sie bitte Ihren persönlichen Gutschein-Code: {{PASS-ID}}"
