### ISSUE TITLE
Create missing tables and columns in database setup

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#908]
**Is your feature request related to a problem? Please describe.**
If we add new columns to a database we want to to created when we the backend restarts

- implement `SchemaUtils.createMissingTablesAndColumns()` in every `setupDatabase()`

**Comment by f1sh1918** [comment]
Should we add this to every database setup or only if needed?

**Comment by michael-markl** [comment]
This should not be necesary once migrations are set up.

**Comment by f1sh1918** [comment]
will be handle with migrations #911
