### ISSUE TITLE
[Staging] Add CI workflow for staging environment

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#923]
**Is your feature request related to a problem? Please describe.**
As we want to have a staging system, we need a separate workflow that builds and deploys staging builds on the staging server

**Describe the solution you'd like**

- add env variable for staging api
- create separate workflow that will be triggered by merging in main
- adjust prod workflow to be only executed when a release branch was pushed

**Describe alternatives you've considered**
- trigger prod workflow manually

**Comment by michael-markl** [comment]
I think the prod deployment still needs to be tested?
