### ISSUE TITLE
Ausweisen section not shown

### ISSUE THREAD

**Issue by Juoper** [digitalfabrik/entitlementcard#961]
**Describe the bug**
The ausweisen section is not shown in the app

**To Reproduce**
1. Install the app on android 13
2. Open the app

**Expected behavior**
The ausweisen section should be shown

**Screenshots**
![Screenshot_20230506_153823_Ehrenamt](https://user-images.githubusercontent.com/62133932/236627774-cf8b9778-4777-460f-a0f7-aefab705f3f8.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung A32
 - OS: Android 13
 - Browser: in app
 - Version 3.0.5

**Comment by f1sh1918** [comment]
Hi @Juoper,

thx for creating an issue. The `Ausweisen` tab is not yet activated since the application process for requesting digital entitlementcard wasn't fully approved while we released that version. With the next version the tab will be shown.
