### ISSUE TITLE
[Bavaria] Provide SQL script to deactivate region

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#968]
**Is your feature request related to a problem? Please describe.**
As not all regions will use the new application process, we have to provide a script that deactivates these regions.

**Describe the solution you'd like**
We will get a list with all not participating regions from StMas. These list will be used once to deactivate these regions from the application process. Provide a sql script that deactivates these regions and execute it once on production database.

blocked by #967

**Comment by sarahsporck** [comment]
I guess we get a list of names from StMas, so for one region this should be sth like
```sql
update regions
set "activatedForApplication" = false
where prefix || ' ' || name = 'Landkreis Altötting';
```
And in the migration this should be sth like the following
```kt
val names = arrayOf("Landkreis Altötting", "Stadt Bayreuth", "...")
val condition = names.joinToString(separator = " or ") { "prefix || ' ' || name =" + it }
exec(
    """
    UPDATE regions 
    SET "activatedForApplication" = false
    WHERE $condition
    """.trimIndent()
)
```

**Comment by sarahsporck** [comment]
> Not sure what this does:
> `where prefix || ' ' || name = 'Landkreis Altötting';`

This will concatenate the prefix and th name with a space in between. But this depends on the format of the list they'll provide. Let's see :)

**Comment by f1sh1918** [comment]
I told Daniel to use a csv Export of the Region table to ensure names are fitting. I'm gonna provide it

**Comment by f1sh1918** [comment]
@dkehne the 13 regions where deactivated and can be activated from a region admin here:
https://bayern.ehrenamtskarte.app/region
