### ISSUE TITLE
[Bavaria] Notification settings shown for Project Admins

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#972]
**Describe the bug**
Notification for new applications and verification are available for every user. Since project admins are only used for creating new user, they have nothing to do with applications and are not assigned to a region. Therefore it makes no sense to let the activate notifications

**To Reproduce**
1. Log in as project admin
2. Click on 'Benutzereinstellungen'
3. Check "Benachrichtigungen" are configurable

**Expected behavior**
Notification Settings are only available for regions admins and region managers

**Comment by sarahsporck** [comment]
I can confirm that I mistakenly didn't check whether the logged in user is a project admin.
