### ISSUE TITLE
[Staging] Acceptance Stores not available

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#997]
**Describe the bug**
On staging the acceptance stores can't be opened. The popup doesn't show up and the detail view does not work

**To Reproduce**
1. Go to "Über"
2. Enable staging
3. Go to Map
4. Click on an acceptance store
5. Check no acceptance stores

**Expected behavior**
The popup opens and you can click on it to see details of the stores

**Comment by f1sh1918** [comment]
https://git.tuerantuer.org/DF/salt/pulls/70

**Comment by f1sh1918** [comment]
@michael-markl hm now we can see the stores under search but on the map are no clusters nor acceptance stores on staging. any ideas about that? I added the staging url in this salt pr above but this seem not to work?
Or is this related to the `mapStyleUrl` ?
https://api.staging.entitlementcard.app/project/bayern.ehrenamtskarte.app/map
The content seem to be fine

**Comment by michael-markl** [comment]
No, I am not sure what happens. However, I am bit confused: If I switch to the staging endpoint on the production app and restart the app, it does not keep using the staging endpoint. Is this a bug?

**Comment by f1sh1918** [comment]
hm are you on 3.1.4? just tested this on ios and i'm still on staging after restart

**Comment by michael-markl** [comment]
Oh, it does seems to work now. No idea, what happened, probably I was just somehow confused 😅

But the map does not show accepting stores for me too. Not idea why currently.

**Comment by f1sh1918** [comment]
this was fixed by @svenseeberg :)
related to some missing permission of the martin database
